# Translations template for nova.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 12.0.0.0b3.dev317\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-08-12 06:30+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: nova/block_device.py:103
msgid "Some fields are invalid."
msgstr ""

#: nova/block_device.py:113
msgid "Some required fields are missing"
msgstr ""

#: nova/block_device.py:129 nova/block_device.py:204
msgid "Boot index is invalid."
msgstr ""

#: nova/block_device.py:172
msgid "Unrecognized legacy format."
msgstr ""

#: nova/block_device.py:190
msgid "Invalid source_type field."
msgstr ""

#: nova/block_device.py:193
msgid "Invalid device UUID."
msgstr ""

#: nova/block_device.py:197
msgid "Missing device UUID."
msgstr ""

#: nova/block_device.py:209
msgid "Mapping image to local is not supported."
msgstr ""

#: nova/block_device.py:400
msgid "Device name empty or too long."
msgstr ""

#: nova/block_device.py:404
msgid "Device name contains spaces."
msgstr ""

#: nova/block_device.py:417
msgid "Invalid volume_size."
msgstr ""

#: nova/context.py:158
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: nova/crypto.py:57
msgid "Filename of root CA"
msgstr ""

#: nova/crypto.py:60
msgid "Filename of private key"
msgstr ""

#: nova/crypto.py:63
msgid "Filename of root Certificate Revocation List"
msgstr ""

#: nova/crypto.py:66
msgid "Where we keep our keys"
msgstr ""

#: nova/crypto.py:69
msgid "Where we keep our root CA"
msgstr ""

#: nova/crypto.py:72
msgid "Should we use a CA for each project?"
msgstr ""

#: nova/crypto.py:76
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""

#: nova/crypto.py:81
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr ""

#: nova/crypto.py:151
msgid "failed to generate fingerprint"
msgstr ""

#: nova/crypto.py:166
#, python-format
msgid "failed to generate X509 fingerprint. Error message: %s"
msgstr ""

#: nova/exception.py:103
msgid "An unknown exception occurred."
msgstr ""

#: nova/exception.py:145
#, python-format
msgid "Failed to encrypt text: %(reason)s"
msgstr ""

#: nova/exception.py:149
#, python-format
msgid "Failed to decrypt text: %(reason)s"
msgstr ""

#: nova/exception.py:153
#, python-format
msgid "Failed to revoke certificate for %(project_id)s"
msgstr ""

#: nova/exception.py:157
msgid "Virtual Interface creation failed"
msgstr ""

#: nova/exception.py:161
msgid "Creation of virtual interface with unique mac address failed"
msgstr ""

#: nova/exception.py:166
msgid "Virtual interface plugin failed"
msgstr ""

#: nova/exception.py:170
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr ""

#: nova/exception.py:175
#, python-format
msgid "Connection to cinder host failed: %(reason)s"
msgstr ""

#: nova/exception.py:180
msgid "Not authorized."
msgstr ""

#: nova/exception.py:185
msgid "User does not have admin privileges"
msgstr ""

#: nova/exception.py:189
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: nova/exception.py:193
msgid "Volume resource quota exceeded"
msgstr ""

#: nova/exception.py:200
#, python-format
msgid "Image %(image_id)s is not active."
msgstr ""

#: nova/exception.py:204
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: nova/exception.py:208 nova/exception.py:356
msgid "Unacceptable parameters."
msgstr ""

#: nova/exception.py:213
msgid "Block Device Mapping is Invalid."
msgstr ""

#: nova/exception.py:217
#, python-format
msgid "Block Device Mapping is Invalid: failed to get snapshot %(id)s."
msgstr ""

#: nova/exception.py:222
#, python-format
msgid "Block Device Mapping is Invalid: failed to get volume %(id)s."
msgstr ""

#: nova/exception.py:227
#, python-format
msgid "Block Device Mapping is Invalid: failed to get image %(id)s."
msgstr ""

#: nova/exception.py:232
msgid ""
"Block Device Mapping is Invalid: Boot sequence for the instance and "
"image/block device mapping combination is not valid."
msgstr ""

#: nova/exception.py:239
msgid ""
"Block Device Mapping is Invalid: You specified more local devices than "
"the limit allows"
msgstr ""

#: nova/exception.py:245
msgid "Ephemeral disks requested are larger than the instance type allows."
msgstr ""

#: nova/exception.py:250
msgid "Swap drive requested is larger than instance type allows."
msgstr ""

#: nova/exception.py:254
#, python-format
msgid "Block Device Mapping is Invalid: %(details)s"
msgstr ""

#: nova/exception.py:259
msgid "Block Device Mapping cannot be converted to legacy format. "
msgstr ""

#: nova/exception.py:264
#, python-format
msgid "Block Device %(id)s is not bootable."
msgstr ""

#: nova/exception.py:268
#, python-format
msgid "Attribute not supported: %(attr)s"
msgstr ""

#: nova/exception.py:277
#, python-format
msgid "Volume %(volume_id)s is not attached to anything"
msgstr ""

#: nova/exception.py:281
#, python-format
msgid ""
"Volume %(volume_id)s did not finish being created even after we waited "
"%(seconds)s seconds or %(attempts)s attempts. And its status is "
"%(volume_status)s."
msgstr ""

#: nova/exception.py:287
#, python-format
msgid ""
"Volume encryption is not supported for %(volume_type)s volume "
"%(volume_id)s"
msgstr ""

#: nova/exception.py:293
#, python-format
msgid "Keypair data is invalid: %(reason)s"
msgstr ""

#: nova/exception.py:297
msgid "The request is invalid."
msgstr ""

#: nova/exception.py:301
#, python-format
msgid "Invalid input received: %(reason)s"
msgstr ""

#: nova/exception.py:306
#, python-format
msgid "Invalid volume: %(reason)s"
msgstr ""

#: nova/exception.py:310
#, python-format
msgid "Invalid volume access mode: %(access_mode)s"
msgstr ""

#: nova/exception.py:314
#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr ""

#: nova/exception.py:318
#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr ""

#: nova/exception.py:323
#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr ""

#: nova/exception.py:327
#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr ""

#: nova/exception.py:331
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: nova/exception.py:335
#, python-format
msgid ""
"API Version String %(version)s is of invalid format. Must be of format "
"MajorNum.MinorNum."
msgstr ""

#: nova/exception.py:340
#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr ""

#: nova/exception.py:344
#, python-format
msgid ""
"Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s "
"and maximum is %(max_ver)s."
msgstr ""

#: nova/exception.py:352
#, python-format
msgid "%(err)s"
msgstr ""

#: nova/exception.py:361
#, python-format
msgid "Cannot add host to aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:366
#, python-format
msgid "Cannot remove host from aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:371
#, python-format
msgid "Cannot update aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:376
#, python-format
msgid "Cannot update metadata of aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:381
#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr ""

#: nova/exception.py:385
msgid "Sort key supplied was not valid."
msgstr ""

#: nova/exception.py:389
#, python-format
msgid "Invalid datetime string: %(reason)s"
msgstr ""

#: nova/exception.py:393
#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while"
" the instance is in this state."
msgstr ""

#: nova/exception.py:398
#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr ""

#: nova/exception.py:402
#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr ""

#: nova/exception.py:406
#, python-format
msgid "Instance %(instance_id)s cannot be rescued: %(reason)s"
msgstr ""

#: nova/exception.py:410
#, python-format
msgid "Instance %(instance_id)s is not ready"
msgstr ""

#: nova/exception.py:414
#, python-format
msgid "Failed to suspend instance: %(reason)s"
msgstr ""

#: nova/exception.py:418
#, python-format
msgid "Failed to resume instance: %(reason)s"
msgstr ""

#: nova/exception.py:422
#, python-format
msgid "Failed to power on instance: %(reason)s"
msgstr ""

#: nova/exception.py:426
#, python-format
msgid "Failed to power off instance: %(reason)s"
msgstr ""

#: nova/exception.py:430
#, python-format
msgid "Failed to reboot instance: %(reason)s"
msgstr ""

#: nova/exception.py:434
#, python-format
msgid "Failed to terminate instance: %(reason)s"
msgstr ""

#: nova/exception.py:438
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr ""

#: nova/exception.py:442 nova/exception.py:446
#, python-format
msgid "Failed to launch instances: %(reason)s"
msgstr ""

#: nova/exception.py:450
msgid "Service is unavailable at this time."
msgstr ""

#: nova/exception.py:454
#, python-format
msgid "Insufficient compute resources: %(reason)s."
msgstr ""

#: nova/exception.py:458
#, python-format
msgid "Connection to the hypervisor is broken on host: %(host)s"
msgstr ""

#: nova/exception.py:462
#, python-format
msgid "Compute service of %(host)s is unavailable at this time."
msgstr ""

#: nova/exception.py:466
#, python-format
msgid "Compute service of %(host)s is still in use."
msgstr ""

#: nova/exception.py:470
#, python-format
msgid "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""

#: nova/exception.py:475
msgid "The supplied hypervisor type of is invalid."
msgstr ""

#: nova/exception.py:479
msgid "The instance requires a newer hypervisor version than has been provided."
msgstr ""

#: nova/exception.py:484
#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""

#: nova/exception.py:489
#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr ""

#: nova/exception.py:493
#, python-format
msgid "The supplied device path (%(path)s) is in use."
msgstr ""

#: nova/exception.py:498
#, python-format
msgid "The supplied device (%(device)s) is busy."
msgstr ""

#: nova/exception.py:502
#, python-format
msgid "Unacceptable CPU info: %(reason)s"
msgstr ""

#: nova/exception.py:506
#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr ""

#: nova/exception.py:510
#, python-format
msgid ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN "
"tag is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""

#: nova/exception.py:516
#, python-format
msgid ""
"vSwitch which contains the port group %(bridge)s is not associated with "
"the desired physical adapter. Expected vSwitch is %(expected)s, but the "
"one associated is %(actual)s."
msgstr ""

#: nova/exception.py:523
#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr ""

#: nova/exception.py:527
#, python-format
msgid "Disk info file is invalid: %(reason)s"
msgstr ""

#: nova/exception.py:531
#, python-format
msgid "Failed to read or write disk info file: %(reason)s"
msgstr ""

#: nova/exception.py:535
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:539
#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:543
#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr ""

#: nova/exception.py:547
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: nova/exception.py:551
#, python-format
msgid "Invalid ID received %(id)s."
msgstr ""

#: nova/exception.py:555
msgid "Constraint not met."
msgstr ""

#: nova/exception.py:560
msgid "Resource could not be found."
msgstr ""

#: nova/exception.py:565
#, python-format
msgid "No agent-build associated with id %(id)s."
msgstr ""

#: nova/exception.py:569
#, python-format
msgid ""
"Agent-build with hypervisor %(hypervisor)s os %(os)s architecture "
"%(architecture)s exists."
msgstr ""

#: nova/exception.py:575
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: nova/exception.py:579
#, python-format
msgid "No Block Device Mapping with id %(id)s."
msgstr ""

#: nova/exception.py:583
#, python-format
msgid "No volume Block Device Mapping with id %(volume_id)s."
msgstr ""

#: nova/exception.py:587
#, python-format
msgid "No volume Block Device Mapping at path: %(path)s"
msgstr ""

#: nova/exception.py:592
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: nova/exception.py:596
#, python-format
msgid "No disk at %(location)s"
msgstr ""

#: nova/exception.py:600
#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr ""

#: nova/exception.py:604
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: nova/exception.py:608
#, python-format
msgid "Requested image %(image)s has automatic disk resize disabled."
msgstr ""

#: nova/exception.py:613
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: nova/exception.py:617
msgid "The current driver does not support preserving ephemeral partitions."
msgstr ""

#: nova/exception.py:623
#, python-format
msgid ""
"Image %(image_id)s could not be found. The nova EC2 API assigns image ids"
" dynamically when they are listed for the first time. Have you listed "
"image ids since adding this image?"
msgstr ""

#: nova/exception.py:630
#, python-format
msgid "Project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:634
msgid "Cannot find SR to read/write VDI."
msgstr ""

#: nova/exception.py:638
#, python-format
msgid "Instance %(uuid)s has no mapping to a cell."
msgstr ""

#: nova/exception.py:642
#, python-format
msgid "Network %(network_id)s is duplicated."
msgstr ""

#: nova/exception.py:646
#, python-format
msgid "Failed to release IP %(address)s with MAC %(mac_address)s"
msgstr ""

#: nova/exception.py:650
#, python-format
msgid "Network %(network_id)s is still in use."
msgstr ""

#: nova/exception.py:654
#, python-format
msgid "Network set host failed for network %(network_id)s."
msgstr ""

#: nova/exception.py:658
#, python-format
msgid "%(req)s is required to create a network."
msgstr ""

#: nova/exception.py:662
msgid "Maximum allowed length for 'label' is 255."
msgstr ""

#: nova/exception.py:666
#, python-format
msgid "%(key)s must be an integer."
msgstr ""

#: nova/exception.py:670
#, python-format
msgid "%(cidr)s is not a valid ip network."
msgstr ""

#: nova/exception.py:674
#, python-format
msgid "%(address)s is not a valid ip address."
msgstr ""

#: nova/exception.py:678
#, python-format
msgid "%(address)s is not within %(cidr)s."
msgstr ""

#: nova/exception.py:682
#, python-format
msgid "Detected existing vlan with id %(vlan)d"
msgstr ""

#: nova/exception.py:687
#, python-format
msgid "Requested cidr (%(cidr)s) conflicts with existing cidr (%(other)s)"
msgstr ""

#: nova/exception.py:693
#, python-format
msgid ""
"Network must be disassociated from project %(project_id)s before it can "
"be deleted."
msgstr ""

#: nova/exception.py:698
#, python-format
msgid "Network %(network_id)s could not be found."
msgstr ""

#: nova/exception.py:702
#, python-format
msgid "Port id %(port_id)s could not be found."
msgstr ""

#: nova/exception.py:706
#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr ""

#: nova/exception.py:710
#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr ""

#: nova/exception.py:714
#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr ""

#: nova/exception.py:718
#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr ""

#: nova/exception.py:722
msgid "No networks defined."
msgstr ""

#: nova/exception.py:726
msgid "No more available networks."
msgstr ""

#: nova/exception.py:730
#, python-format
msgid ""
"Either network uuid %(network_uuid)s is not present or is not assigned to"
" the project %(project_id)s."
msgstr ""

#: nova/exception.py:735
msgid ""
"More than one possible network found. Specify network ID(s) to select "
"which one(s) to connect to."
msgstr ""

#: nova/exception.py:740
#, python-format
msgid "Network %(network_uuid)s requires a subnet in order to boot instances on."
msgstr ""

#: nova/exception.py:745
#, python-format
msgid ""
"It is not allowed to create an interface on external network "
"%(network_uuid)s"
msgstr ""

#: nova/exception.py:750
#, python-format
msgid "Physical network is missing for network %(network_uuid)s"
msgstr ""

#: nova/exception.py:754
#, python-format
msgid "vhostuser_sock_path not present in vif_details for vif %(vif_id)s"
msgstr ""

#: nova/exception.py:759
#, python-format
msgid ""
"Parameters %(missing_params)s not present in vif_details for vif "
"%(vif_id)s. Check your Neutron configuration to validate that the macvtap"
" parameters are correct."
msgstr ""

#: nova/exception.py:766
msgid "Could not find the datastore reference(s) which the VM uses."
msgstr ""

#: nova/exception.py:770
#, python-format
msgid "Port %(port_id)s is still in use."
msgstr ""

#: nova/exception.py:774
#, python-format
msgid "Port %(port_id)s requires a FixedIP in order to be used."
msgstr ""

#: nova/exception.py:778
#, python-format
msgid "Port %(port_id)s not usable for instance %(instance)s."
msgstr ""

#: nova/exception.py:782
#, python-format
msgid "No free port available for instance %(instance)s."
msgstr ""

#: nova/exception.py:786
#, python-format
msgid "Fixed ip %(address)s already exists."
msgstr ""

#: nova/exception.py:790
#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr ""

#: nova/exception.py:794
#, python-format
msgid "Fixed ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:798
#, python-format
msgid "Instance %(instance_uuid)s has zero fixed ips."
msgstr ""

#: nova/exception.py:802
#, python-format
msgid "Network host %(host)s has zero fixed ips in network %(network_id)s."
msgstr ""

#: nova/exception.py:807
#, python-format
msgid "Instance %(instance_uuid)s doesn't have fixed ip '%(ip)s'."
msgstr ""

#: nova/exception.py:811
#, python-format
msgid ""
"Fixed IP address (%(address)s) does not exist in network "
"(%(network_uuid)s)."
msgstr ""

#: nova/exception.py:816
#, python-format
msgid "Fixed IP associate failed for network: %(net)s."
msgstr ""

#: nova/exception.py:820
#, python-format
msgid ""
"Fixed IP address %(address)s is already in use on instance "
"%(instance_uuid)s."
msgstr ""

#: nova/exception.py:825
#, python-format
msgid "More than one instance is associated with fixed ip address '%(address)s'."
msgstr ""

#: nova/exception.py:830
#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr ""

#: nova/exception.py:835
#, python-format
msgid "No fixed IP addresses available for network: %(net)s"
msgstr ""

#: nova/exception.py:839
msgid "Zero fixed ips could be found."
msgstr ""

#: nova/exception.py:843
#, python-format
msgid "Floating ip %(address)s already exists."
msgstr ""

#: nova/exception.py:848
#, python-format
msgid "Floating ip not found for id %(id)s."
msgstr ""

#: nova/exception.py:852
#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr ""

#: nova/exception.py:856
#, python-format
msgid "Floating ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:860
#, python-format
msgid "Floating ip not found for host %(host)s."
msgstr ""

#: nova/exception.py:864
#, python-format
msgid "Multiple floating ips are found for address %(address)s."
msgstr ""

#: nova/exception.py:868
msgid "Floating ip pool not found."
msgstr ""

#: nova/exception.py:873
msgid "Zero floating ips available."
msgstr ""

#: nova/exception.py:879
#, python-format
msgid "Floating ip %(address)s is associated."
msgstr ""

#: nova/exception.py:883
#, python-format
msgid "Floating ip %(address)s is not associated."
msgstr ""

#: nova/exception.py:887
msgid "Zero floating ips exist."
msgstr ""

#: nova/exception.py:892
#, python-format
msgid "Interface %(interface)s not found."
msgstr ""

#: nova/exception.py:896
msgid "Floating IP allocate failed."
msgstr ""

#: nova/exception.py:900
#, python-format
msgid "Floating IP %(address)s association has failed."
msgstr ""

#: nova/exception.py:905 nova/api/openstack/compute/contrib/floating_ips.py:73
#: nova/api/openstack/compute/contrib/floating_ips.py:154
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:83
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:174
msgid "Cannot disassociate auto assigned floating ip"
msgstr ""

#: nova/exception.py:910
#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr ""

#: nova/exception.py:914
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: nova/exception.py:918
#, python-format
msgid "Service with host %(host)s binary %(binary)s exists."
msgstr ""

#: nova/exception.py:922
#, python-format
msgid "Service with host %(host)s topic %(topic)s exists."
msgstr ""

#: nova/exception.py:926
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: nova/exception.py:930
#, python-format
msgid "Compute host %(host)s could not be found."
msgstr ""

#: nova/exception.py:934
#, python-format
msgid "Compute host %(name)s needs to be created first before updating."
msgstr ""

#: nova/exception.py:939
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: nova/exception.py:943
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: nova/exception.py:947
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"
msgstr ""

#: nova/exception.py:952
#, python-format
msgid "Wrong quota method %(method)s used on resource %(res)s"
msgstr ""

#: nova/exception.py:956
msgid "Quota could not be found"
msgstr ""

#: nova/exception.py:960
#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s"
msgstr ""

#: nova/exception.py:965
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: nova/exception.py:969
#, python-format
msgid "Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:974
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:978
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: nova/exception.py:982
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:986
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: nova/exception.py:990
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr ""

#: nova/exception.py:994
#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr ""

#: nova/exception.py:998
#, python-format
msgid "Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""

#: nova/exception.py:1003
#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr ""

#: nova/exception.py:1008
#, python-format
msgid ""
"Security group %(security_group_name)s already exists for project "
"%(project_id)s."
msgstr ""

#: nova/exception.py:1013
#, python-format
msgid ""
"Security group %(security_group_id)s is already associated with the "
"instance %(instance_id)s"
msgstr ""

#: nova/exception.py:1018
#, python-format
msgid ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"
msgstr ""

#: nova/exception.py:1023
#, python-format
msgid "Security group default rule (%rule_id)s not found."
msgstr ""

#: nova/exception.py:1027
msgid ""
"Network requires port_security_enabled and subnet associated in order to "
"apply security groups."
msgstr ""

#: nova/exception.py:1033
#, python-format
msgid "Rule already exists in group: %(rule)s"
msgstr ""

#: nova/exception.py:1037
msgid "No Unique Match Found."
msgstr ""

#: nova/exception.py:1042
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: nova/exception.py:1046
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: nova/exception.py:1051
#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr ""

#: nova/exception.py:1055
#, python-format
msgid ""
"Console pool with host %(host)s, console_type %(console_type)s and "
"compute_host %(compute_host)s already exists."
msgstr ""

#: nova/exception.py:1061
#, python-format
msgid ""
"Console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s not found."
msgstr ""

#: nova/exception.py:1067
#, python-format
msgid "Console %(console_id)s could not be found."
msgstr ""

#: nova/exception.py:1071
#, python-format
msgid "Console for instance %(instance_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1075
#, python-format
msgid ""
"Console for instance %(instance_uuid)s in pool %(pool_id)s could not be "
"found."
msgstr ""

#: nova/exception.py:1080
#, python-format
msgid "Invalid console type %(console_type)s"
msgstr ""

#: nova/exception.py:1084
#, python-format
msgid "Unavailable console type %(console_type)s."
msgstr ""

#: nova/exception.py:1088
#, python-format
msgid "The console port range %(min_port)d-%(max_port)d is exhausted."
msgstr ""

#: nova/exception.py:1093
#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr ""

#: nova/exception.py:1097
#, python-format
msgid "Flavor with name %(flavor_name)s could not be found."
msgstr ""

#: nova/exception.py:1101
#, python-format
msgid "Flavor access not found for %(flavor_id)s / %(project_id)s combination."
msgstr ""

#: nova/exception.py:1106
#, python-format
msgid ""
"Flavor %(id)d extra spec cannot be updated or created after %(retries)d "
"retries."
msgstr ""

#: nova/exception.py:1111
#, python-format
msgid "Cell %(cell_name)s doesn't exist."
msgstr ""

#: nova/exception.py:1115
#, python-format
msgid "Cell with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1119
#, python-format
msgid "Inconsistency in cell routing: %(reason)s"
msgstr ""

#: nova/exception.py:1123
#, python-format
msgid "Service API method not found: %(detail)s"
msgstr ""

#: nova/exception.py:1127
msgid "Timeout waiting for response from cell"
msgstr ""

#: nova/exception.py:1131
#, python-format
msgid "Cell message has reached maximum hop count: %(hop_count)s"
msgstr ""

#: nova/exception.py:1135
msgid "No cells available matching scheduling criteria."
msgstr ""

#: nova/exception.py:1139
msgid "Cannot update cells configuration file."
msgstr ""

#: nova/exception.py:1143
#, python-format
msgid "Cell is not known for instance %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1147
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: nova/exception.py:1151
#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(extra_specs_key)s."
msgstr ""

#: nova/exception.py:1156
#, python-format
msgid ""
"Metric %(name)s could not be found on the compute host node "
"%(host)s.%(node)s."
msgstr ""

#: nova/exception.py:1161
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: nova/exception.py:1165
#, python-format
msgid "Virtual switch associated with the network adapter %(adapter)s not found."
msgstr ""

#: nova/exception.py:1170
#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr ""

#: nova/exception.py:1174
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr ""

#: nova/exception.py:1178
#, python-format
msgid "Instance %(instance_id)s has no tag '%(tag)s'"
msgstr ""

#: nova/exception.py:1182
msgid "Rotation param is required for backup image_type"
msgstr ""

#: nova/exception.py:1187
#, python-format
msgid "Key pair '%(key_name)s' already exists."
msgstr ""

#: nova/exception.py:1191
#, python-format
msgid "Instance %(name)s already exists."
msgstr ""

#: nova/exception.py:1195
#, python-format
msgid "Flavor with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1199
#, python-format
msgid "Flavor with ID %(flavor_id)s already exists."
msgstr ""

#: nova/exception.py:1203
#, python-format
msgid ""
"Flavor access already exists for flavor %(flavor_id)s and project "
"%(project_id)s combination."
msgstr ""

#: nova/exception.py:1208
#, python-format
msgid "%(path)s is not on shared storage: %(reason)s"
msgstr ""

#: nova/exception.py:1212
#, python-format
msgid "%(path)s is not on local storage: %(reason)s"
msgstr ""

#: nova/exception.py:1216
#, python-format
msgid "Storage error: %(reason)s"
msgstr ""

#: nova/exception.py:1220
#, python-format
msgid "Migration error: %(reason)s"
msgstr ""

#: nova/exception.py:1224
#, python-format
msgid "Migration pre-check error: %(reason)s"
msgstr ""

#: nova/exception.py:1228
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr ""

#: nova/exception.py:1234
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: nova/exception.py:1238
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""

#: nova/exception.py:1242
msgid "When resizing, instances must change flavor!"
msgstr ""

#: nova/exception.py:1246
#, python-format
msgid "Resize error: %(reason)s"
msgstr ""

#: nova/exception.py:1250
#, python-format
msgid "Server disk was unable to be resized because: %(reason)s"
msgstr ""

#: nova/exception.py:1254
msgid "Flavor's memory is too small for requested image."
msgstr ""

#: nova/exception.py:1258
msgid "Flavor's disk is too small for requested image."
msgstr ""

#: nova/exception.py:1262
#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr ""

#: nova/exception.py:1266
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr ""

#: nova/exception.py:1270
#, python-format
msgid "Exceeded maximum number of retries. %(reason)s"
msgstr ""

#: nova/exception.py:1275
#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr ""

#: nova/exception.py:1285
#, python-format
msgid ""
"Quota exceeded for %(overs)s: Requested %(req)s, but already used "
"%(used)d of %(allowed)d %(resource)s"
msgstr ""

#: nova/exception.py:1290
msgid "Maximum number of floating ips exceeded"
msgstr ""

#: nova/exception.py:1294
msgid "Maximum number of fixed ips exceeded"
msgstr ""

#: nova/exception.py:1298
#, python-format
msgid "Maximum number of metadata items exceeds %(allowed)d"
msgstr ""

#: nova/exception.py:1302
msgid "Personality file limit exceeded"
msgstr ""

#: nova/exception.py:1306
msgid "Personality file path too long"
msgstr ""

#: nova/exception.py:1310
msgid "Personality file content too long"
msgstr ""

#: nova/exception.py:1314
msgid "Maximum number of key pairs exceeded"
msgstr ""

#: nova/exception.py:1319
msgid "Maximum number of security groups or rules exceeded"
msgstr ""

#: nova/exception.py:1323
msgid "Maximum number of ports exceeded"
msgstr ""

#: nova/exception.py:1327
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: "
"%(reason)s."
msgstr ""

#: nova/exception.py:1332
#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr ""

#: nova/exception.py:1336
#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr ""

#: nova/exception.py:1340
#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr ""

#: nova/exception.py:1344
#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:1349
#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr ""

#: nova/exception.py:1353
msgid "Unable to create flavor"
msgstr ""

#: nova/exception.py:1357
#, python-format
msgid "Failed to set admin password on %(instance)s because %(reason)s"
msgstr ""

#: nova/exception.py:1364
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: nova/exception.py:1368
#, python-format
msgid "Info cache for instance %(instance_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1374
msgid "Invalid association."
msgstr ""

#: nova/exception.py:1378
#, python-format
msgid "Marker %(marker)s could not be found."
msgstr ""

#: nova/exception.py:1382
#, python-format
msgid "Invalid id: %(instance_id)s (expecting \"i-...\")"
msgstr ""

#: nova/exception.py:1387
#, python-format
msgid "Invalid id: %(volume_id)s (expecting \"i-...\")"
msgstr ""

#: nova/exception.py:1392
#, python-format
msgid "Could not fetch image %(image_id)s"
msgstr ""

#: nova/exception.py:1396
#, python-format
msgid "Could not upload image %(image_id)s"
msgstr ""

#: nova/exception.py:1400
#, python-format
msgid "Task %(task_name)s is already running on host %(host)s"
msgstr ""

#: nova/exception.py:1404
#, python-format
msgid "Task %(task_name)s is not running on host %(host)s"
msgstr ""

#: nova/exception.py:1408
#, python-format
msgid "Instance %(instance_uuid)s is locked"
msgstr ""

#: nova/exception.py:1412
#, python-format
msgid "Invalid value for Config Drive option: %(option)s"
msgstr ""

#: nova/exception.py:1416
#, python-format
msgid "Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"
msgstr ""

#: nova/exception.py:1421
#, python-format
msgid "Unknown config drive format %(format)s. Select one of iso9660 or vfat."
msgstr ""

#: nova/exception.py:1426
#, python-format
msgid "Failed to attach network adapter device to %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1431
#, python-format
msgid "Failed to detach network adapter device from %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1436
#, python-format
msgid ""
"User data too large. User data must be no larger than %(maxsize)s bytes "
"once base64 encoded. Your data is %(length)d bytes"
msgstr ""

#: nova/exception.py:1442
msgid "User data needs to be valid base 64."
msgstr ""

#: nova/exception.py:1446
#, python-format
msgid ""
"Conflict updating instance %(instance_uuid)s. Expected: %(expected)s. "
"Actual: %(actual)s"
msgstr ""

#: nova/exception.py:1451
#, python-format
msgid ""
"Conflict updating instance %(instance_uuid)s, but we were unable to "
"determine the cause"
msgstr ""

#: nova/exception.py:1464
#, python-format
msgid ""
"Action for request_id %(request_id)s on instance %(instance_uuid)s not "
"found"
msgstr ""

#: nova/exception.py:1469
#, python-format
msgid "Event %(event)s not found for action id %(action_id)s"
msgstr ""

#: nova/exception.py:1473
#, python-format
msgid "The CA file for %(project)s could not be found"
msgstr ""

#: nova/exception.py:1477
#, python-format
msgid "The CRL file for %(project)s could not be found"
msgstr ""

#: nova/exception.py:1481
msgid "Instance recreate is not supported."
msgstr ""

#: nova/exception.py:1485
#, python-format
msgid ""
"The service from servicegroup driver %(driver)s is temporarily "
"unavailable."
msgstr ""

#: nova/exception.py:1490
#, python-format
msgid "%(binary)s attempted direct database access which is not allowed by policy"
msgstr ""

#: nova/exception.py:1495
#, python-format
msgid "Virtualization type '%(virt)s' is not supported by this compute driver"
msgstr ""

#: nova/exception.py:1500
#, python-format
msgid ""
"Requested hardware '%(model)s' is not supported by the '%(virt)s' virt "
"driver"
msgstr ""

#: nova/exception.py:1505
#, python-format
msgid "Invalid Base 64 data for file %(path)s"
msgstr ""

#: nova/exception.py:1509
#, python-format
msgid "Build of instance %(instance_uuid)s aborted: %(reason)s"
msgstr ""

#: nova/exception.py:1513
#, python-format
msgid "Build of instance %(instance_uuid)s was re-scheduled: %(reason)s"
msgstr ""

#: nova/exception.py:1518
#, python-format
msgid "Shadow table with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1523
#, python-format
msgid "Instance rollback performed due to: %s"
msgstr ""

#: nova/exception.py:1529
#, python-format
msgid "Conflict updating instance %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1533
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""

#: nova/exception.py:1537
#, python-format
msgid "Object action %(action)s failed because: %(reason)s"
msgstr ""

#: nova/exception.py:1541
#, python-format
msgid "Core API extensions are missing: %(missing_apis)s"
msgstr ""

#: nova/exception.py:1545
#, python-format
msgid "Error during following call to agent: %(method)s"
msgstr ""

#: nova/exception.py:1549
#, python-format
msgid "Unable to contact guest agent. The following call timed out: %(method)s"
msgstr ""

#: nova/exception.py:1554
#, python-format
msgid "Agent does not support the call: %(method)s"
msgstr ""

#: nova/exception.py:1558
#, python-format
msgid "Instance group %(group_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1562
#, python-format
msgid "Instance group %(group_uuid)s already exists."
msgstr ""

#: nova/exception.py:1566
#, python-format
msgid "Instance group %(group_uuid)s has no member with id %(instance_id)s."
msgstr ""

#: nova/exception.py:1571
#, python-format
msgid "Instance group %(group_uuid)s has no policy %(policy)s."
msgstr ""

#: nova/exception.py:1575
#, python-format
msgid "Number of retries to plugin (%(num_retries)d) exceeded."
msgstr ""

#: nova/exception.py:1579
#, python-format
msgid "There was an error with the download module %(module)s. %(reason)s"
msgstr ""

#: nova/exception.py:1584
#, python-format
msgid ""
"The metadata for this location will not work with this module %(module)s."
"  %(reason)s."
msgstr ""

#: nova/exception.py:1589
#, python-format
msgid "The method %(method_name)s is not implemented."
msgstr ""

#: nova/exception.py:1593
#, python-format
msgid "The module %(module)s is misconfigured: %(reason)s."
msgstr ""

#: nova/exception.py:1597
#, python-format
msgid "Error when creating resource monitor: %(monitor)s"
msgstr ""

#: nova/exception.py:1601
#, python-format
msgid "The PCI address %(address)s has an incorrect format."
msgstr ""

#: nova/exception.py:1605
#, python-format
msgid ""
"Invalid PCI Whitelist: The PCI address %(address)s has an invalid "
"%(field)s."
msgstr ""

#: nova/exception.py:1610
msgid ""
"Invalid PCI Whitelist: The PCI whitelist can specify devname or address, "
"but not both"
msgstr ""

#: nova/exception.py:1616
#, python-format
msgid "PCI device %(id)s not found"
msgstr ""

#: nova/exception.py:1620
#, python-format
msgid "PCI Device %(node_id)s:%(address)s not found."
msgstr ""

#: nova/exception.py:1624
#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is %(status)s instead of "
"%(hopestatus)s"
msgstr ""

#: nova/exception.py:1630
#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is owned by %(owner)s instead "
"of %(hopeowner)s"
msgstr ""

#: nova/exception.py:1636
#, python-format
msgid "PCI device request (%requests)s failed"
msgstr ""

#: nova/exception.py:1641
#, python-format
msgid ""
"Attempt to consume PCI device %(compute_node_id)s:%(address)s from empty "
"pool"
msgstr ""

#: nova/exception.py:1647
#, python-format
msgid "Invalid PCI alias definition: %(reason)s"
msgstr ""

#: nova/exception.py:1651
#, python-format
msgid "PCI alias %(alias)s is not defined"
msgstr ""

#: nova/exception.py:1656
#, python-format
msgid "Not enough parameters: %(reason)s"
msgstr ""

#: nova/exception.py:1661
#, python-format
msgid "Invalid PCI devices Whitelist config %(reason)s"
msgstr ""

#: nova/exception.py:1671
#, python-format
msgid ""
"Failed to prepare PCI device %(id)s for instance %(instance_uuid)s: "
"%(reason)s"
msgstr ""

#: nova/exception.py:1676
#, python-format
msgid "Failed to detach PCI device %(dev)s: %(reason)s"
msgstr ""

#: nova/exception.py:1680
#, python-format
msgid "%(type)s hypervisor does not support PCI devices"
msgstr ""

#: nova/exception.py:1684
#, python-format
msgid "Key manager error: %(reason)s"
msgstr ""

#: nova/exception.py:1688
#, python-format
msgid "Failed to remove volume(s): (%(reason)s)"
msgstr ""

#: nova/exception.py:1692
#, python-format
msgid "Provided video model (%(model)s) is not supported."
msgstr ""

#: nova/exception.py:1696
#, python-format
msgid "The provided RNG device path: (%(path)s) is not present on the host."
msgstr ""

#: nova/exception.py:1701
#, python-format
msgid ""
"The requested amount of video memory %(req_vram)d is higher than the "
"maximum allowed by flavor %(max_vram)d."
msgstr ""

#: nova/exception.py:1706
#, python-format
msgid "Provided watchdog action (%(action)s) is not supported."
msgstr ""

#: nova/exception.py:1710
msgid ""
"Live migration of instances with config drives is not supported in "
"libvirt unless libvirt instance path and drive data is shared across "
"compute nodes."
msgstr ""

#: nova/exception.py:1716
#, python-format
msgid ""
"Host %(server)s is running an old version of Nova, live migrations "
"involving that version may cause data loss. Upgrade Nova on %(server)s "
"and try again."
msgstr ""

#: nova/exception.py:1722
#, python-format
msgid "Error during unshelve instance %(instance_id)s: %(reason)s"
msgstr ""

#: nova/exception.py:1726
#, python-format
msgid ""
"Image vCPU limits %(sockets)d:%(cores)d:%(threads)d exceeds permitted "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""

#: nova/exception.py:1731
#, python-format
msgid ""
"Image vCPU topology %(sockets)d:%(cores)d:%(threads)d exceeds permitted "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""

#: nova/exception.py:1736
#, python-format
msgid ""
"Requested vCPU limits %(sockets)d:%(cores)d:%(threads)d are impossible to"
" satisfy for vcpus count %(vcpus)d"
msgstr ""

#: nova/exception.py:1741
#, python-format
msgid "Architecture name '%(arch)s' is not recognised"
msgstr ""

#: nova/exception.py:1745
msgid "CPU and memory allocation must be provided for all NUMA nodes"
msgstr ""

#: nova/exception.py:1750
#, python-format
msgid ""
"Image property '%(name)s' is not permitted to override NUMA configuration"
" set against the flavor"
msgstr ""

#: nova/exception.py:1755
msgid ""
"Asymmetric NUMA topologies require explicit assignment of CPUs and memory"
" to nodes in image or flavor"
msgstr ""

#: nova/exception.py:1760
#, python-format
msgid "CPU number %(cpunum)d is larger than max %(cpumax)d"
msgstr ""

#: nova/exception.py:1764
#, python-format
msgid "CPU number %(cpunum)d is assigned to two nodes"
msgstr ""

#: nova/exception.py:1768
#, python-format
msgid "CPU number %(cpuset)s is not assigned to any node"
msgstr ""

#: nova/exception.py:1772
#, python-format
msgid "%(memsize)d MB of memory assigned, but expected %(memtotal)d MB"
msgstr ""

#: nova/exception.py:1777
#, python-format
msgid "Invalid characters in hostname '%(hostname)s'"
msgstr ""

#: nova/exception.py:1781
#, python-format
msgid "Instance %(instance_uuid)s does not specify a NUMA topology"
msgstr ""

#: nova/exception.py:1785
#, python-format
msgid "Not able to acquire a free port for %(host)s"
msgstr ""

#: nova/exception.py:1789
#, python-format
msgid "Not able to bind %(host)s:%(port)d, %(error)s"
msgstr ""

#: nova/exception.py:1793
#, python-format
msgid ""
"Number of serial ports '%(num_ports)s' specified in '%(property)s' isn't "
"valid."
msgstr ""

#: nova/exception.py:1798
msgid ""
"Forbidden to exceed flavor value of number of serial ports passed in "
"image meta."
msgstr ""

#: nova/exception.py:1803
#, python-format
msgid "Image's config drive option '%(config_drive)s' is invalid"
msgstr ""

#: nova/exception.py:1807
#, python-format
msgid "Hypervisor virtualization type '%(hv_type)s' is not recognised"
msgstr ""

#: nova/exception.py:1812
#, python-format
msgid "Virtual machine mode '%(vmmode)s' is not recognised"
msgstr ""

#: nova/exception.py:1816
#, python-format
msgid "The token '%(token)s' is invalid or has expired"
msgstr ""

#: nova/exception.py:1820
msgid "Invalid Connection Info"
msgstr ""

#: nova/exception.py:1824
#, python-format
msgid "Quiescing is not supported in instance %(instance_id)s"
msgstr ""

#: nova/exception.py:1828
msgid "QEMU guest agent is not enabled"
msgstr ""

#: nova/exception.py:1832
msgid "Set admin password is not supported"
msgstr ""

#: nova/exception.py:1836
#, python-format
msgid "Invalid memory page size '%(pagesize)s'"
msgstr ""

#: nova/exception.py:1840
#, python-format
msgid "Page size %(pagesize)s forbidden against '%(against)s'"
msgstr ""

#: nova/exception.py:1844
#, python-format
msgid "Page size %(pagesize)s is not supported by the host."
msgstr ""

#: nova/exception.py:1848
#, python-format
msgid "CPU pinning is not supported by the host: %(reason)s"
msgstr ""

#: nova/exception.py:1853
#, python-format
msgid ""
"Cannot pin/unpin cpus %(requested)s from the following pinned set "
"%(pinned)s"
msgstr ""

#: nova/exception.py:1858
#, python-format
msgid ""
"CPU set to pin/unpin %(requested)s must be a subset of known CPU set "
"%(cpuset)s"
msgstr ""

#: nova/exception.py:1863
msgid ""
"Image property 'hw_cpu_policy' is not permitted to override CPU pinning "
"policy set against the flavor"
msgstr ""

#: nova/exception.py:1868
#, python-format
msgid "ServerGroup policy is not supported: %(reason)s"
msgstr ""

#: nova/exception.py:1872
#, python-format
msgid "Cell %(uuid)s has no mapping."
msgstr ""

#: nova/exception.py:1876
msgid "Host does not support guests with NUMA topology set"
msgstr ""

#: nova/exception.py:1880
msgid "Host does not support guests with custom memory page sizes"
msgstr ""

#: nova/exception.py:1884
#, python-format
msgid "%(typename)s in %(fieldname)s is not an instance of Enum"
msgstr ""

#: nova/exception.py:1888
#, python-format
msgid "%(fieldname)s missing field type"
msgstr ""

#: nova/exception.py:1892
#, python-format
msgid "Invalid image format '%(format)s'"
msgstr ""

#: nova/exception.py:1896
#, python-format
msgid "Image model '%(image)s' is not supported"
msgstr ""

#: nova/exception.py:1900
#, python-format
msgid "Database migration failed: %(reason)s"
msgstr ""

#: nova/exception.py:1904
#, python-format
msgid "Host '%(name)s' is not mapped to any cell"
msgstr ""

#: nova/hooks.py:77
msgid "Wrong type of hook method. Only 'pre' and 'post' type allowed"
msgstr ""

#: nova/service.py:334
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: nova/service.py:427
msgid "serve() can only be called once"
msgstr ""

#: nova/utils.py:432
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: nova/utils.py:435
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: nova/utils.py:464
#, python-format
msgid "Expected object of type: %s"
msgstr ""

#: nova/utils.py:951
msgid "The input is not a string or unicode"
msgstr ""

#: nova/utils.py:953
#, python-format
msgid "%s is not a string or unicode"
msgstr ""

#: nova/utils.py:960
#, python-format
msgid "%(name)s has a minimum character requirement of %(min_length)s."
msgstr ""

#: nova/utils.py:965
#, python-format
msgid "%(name)s has more than %(max_length)s characters."
msgstr ""

#: nova/utils.py:975
#, python-format
msgid "%(value_name)s must be an integer"
msgstr ""

#: nova/utils.py:981
#, python-format
msgid "%(value_name)s must be >= %(min_value)d"
msgstr ""

#: nova/utils.py:987
#, python-format
msgid "%(value_name)s must be <= %(max_value)d"
msgstr ""

#: nova/utils.py:1058
#, python-format
msgid "Hypervisor version %s is invalid."
msgstr ""

#: nova/wsgi.py:188
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: nova/wsgi.py:192
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: nova/wsgi.py:196
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: nova/wsgi.py:200
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: nova/wsgi.py:352
msgid "You must implement __call__"
msgstr ""

#: nova/api/auth.py:138
msgid "Invalid service catalog json."
msgstr ""

#: nova/api/ec2/__init__.py:167
msgid "Too many failed authentications."
msgstr ""

#: nova/api/ec2/__init__.py:237
msgid "Signature not provided"
msgstr ""

#: nova/api/ec2/__init__.py:242
msgid "Access key not provided"
msgstr ""

#: nova/api/ec2/__init__.py:301
#, python-format
msgid "Failure parsing response from keystone: %s"
msgstr ""

#: nova/api/ec2/__init__.py:364
msgid "Timestamp failed validation."
msgstr ""

#: nova/api/ec2/__init__.py:585
msgid "Unknown error occurred."
msgstr ""

#: nova/api/ec2/cloud.py:444
#, python-format
msgid "Could not find key pair(s): %s"
msgstr ""

#: nova/api/ec2/cloud.py:627 nova/api/ec2/cloud.py:757
msgid "need group_name or group_id"
msgstr ""

#: nova/api/ec2/cloud.py:632
msgid "can't build a valid rule"
msgstr ""

#: nova/api/ec2/cloud.py:640
#, python-format
msgid "Invalid IP protocol %(protocol)s"
msgstr ""

#: nova/api/ec2/cloud.py:674 nova/api/ec2/cloud.py:710
msgid "No rule for the specified parameters."
msgstr ""

#: nova/api/ec2/cloud.py:1323
msgid "Unable to associate IP Address, no fixed_ips."
msgstr ""

#: nova/api/ec2/cloud.py:1350
msgid "Floating ip is not associated."
msgstr ""

#: nova/api/ec2/cloud.py:1366 nova/api/openstack/compute/servers.py:589
#: nova/api/openstack/compute/plugins/v3/multiple_create.py:56
msgid "min_count must be <= max_count"
msgstr ""

#: nova/api/ec2/cloud.py:1398
msgid "Image must be available"
msgstr ""

#: nova/api/ec2/cloud.py:1629
msgid "imageLocation is required"
msgstr ""

#: nova/api/ec2/cloud.py:1710
msgid "user or group not specified"
msgstr ""

#: nova/api/ec2/cloud.py:1713
msgid "only group \"all\" is supported"
msgstr ""

#: nova/api/ec2/cloud.py:1716
msgid "operation_type must be add or remove"
msgstr ""

#: nova/api/ec2/cloud.py:1731
#, python-format
msgid "Not allowed to modify attributes for image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1761
#, python-format
msgid ""
"Invalid value '%(ec2_instance_id)s' for instanceId. Instance does not "
"have a volume attached at root (%(root)s)"
msgstr ""

#: nova/api/ec2/cloud.py:1794
#, python-format
msgid ""
"Couldn't stop instance %(instance)s within 1 hour. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s"
msgstr ""

#: nova/api/ec2/cloud.py:1818
#, python-format
msgid "image of %(instance)s at %(now)s"
msgstr ""

#: nova/api/ec2/cloud.py:1843 nova/api/ec2/cloud.py:1893
msgid "resource_id and tag are required"
msgstr ""

#: nova/api/ec2/cloud.py:1847 nova/api/ec2/cloud.py:1897
msgid "Expecting a list of resources"
msgstr ""

#: nova/api/ec2/cloud.py:1852 nova/api/ec2/cloud.py:1902
#: nova/api/ec2/cloud.py:1960
msgid "Only instances implemented"
msgstr ""

#: nova/api/ec2/cloud.py:1856 nova/api/ec2/cloud.py:1906
msgid "Expecting a list of tagSets"
msgstr ""

#: nova/api/ec2/cloud.py:1862 nova/api/ec2/cloud.py:1915
msgid "Expecting tagSet to be key/value pairs"
msgstr ""

#: nova/api/ec2/cloud.py:1869
msgid "Expecting both key and value to be set"
msgstr ""

#: nova/api/ec2/cloud.py:1920
msgid "Expecting key to be set"
msgstr ""

#: nova/api/ec2/cloud.py:1994
msgid "Invalid CIDR"
msgstr ""

#: nova/api/ec2/ec2utils.py:252
#, python-format
msgid "Unacceptable attach status:%s for ec2 API."
msgstr ""

#: nova/api/ec2/ec2utils.py:274
msgid "Request must include either Timestamp or Expires, but cannot contain both"
msgstr ""

#: nova/api/metadata/handler.py:165 nova/api/metadata/handler.py:250
#: nova/api/metadata/handler.py:314
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: nova/api/metadata/handler.py:185
msgid "X-Instance-ID header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:187
msgid "X-Instance-ID-Signature header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:189
msgid "X-Tenant-ID header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:191
msgid "Multiple X-Instance-ID headers found within request."
msgstr ""

#: nova/api/metadata/handler.py:193
msgid "Multiple X-Tenant-ID headers found within request."
msgstr ""

#: nova/api/metadata/handler.py:266
msgid "X-Forwarded-For is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:270
msgid "X-Metadata-Provider is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:304
msgid "Invalid proxy request signature."
msgstr ""

#: nova/api/metadata/password.py:63
msgid "Request is too large."
msgstr ""

#: nova/api/openstack/__init__.py:234
msgid "Must specify an ExtensionManager class"
msgstr ""

#: nova/api/openstack/common.py:307
#, python-format
msgid "href %s does not contain version"
msgstr ""

#: nova/api/openstack/common.py:320
msgid "Image metadata limit exceeded"
msgstr ""

#: nova/api/openstack/common.py:327
msgid "Image metadata key cannot be blank"
msgstr ""

#: nova/api/openstack/common.py:330
msgid "Image metadata key too long"
msgstr ""

#: nova/api/openstack/common.py:333
msgid "Invalid image metadata"
msgstr ""

#: nova/api/openstack/common.py:383
#, python-format
msgid ""
"Cannot '%(action)s' instance %(server_id)s while it is in %(attr)s "
"%(state)s"
msgstr ""

#: nova/api/openstack/common.py:389
#, python-format
msgid "Instance %(server_id)s is in an invalid state for '%(action)s'"
msgstr ""

#: nova/api/openstack/common.py:400
msgid "Instance snapshots are not permitted at this time."
msgstr ""

#: nova/api/openstack/common.py:519
msgid "The requested functionality is not supported."
msgstr ""

#: nova/api/openstack/extensions.py:494
#, python-format
msgid ""
"Unexpected API Error. Please report this at "
"http://bugs.launchpad.net/nova/ and attach the Nova API log if possible."
"\n"
"%s"
msgstr ""

#: nova/api/openstack/wsgi.py:279 nova/api/openstack/wsgi.py:489
msgid "cannot understand JSON"
msgstr ""

#: nova/api/openstack/wsgi.py:494
msgid "too many body keys"
msgstr ""

#: nova/api/openstack/wsgi.py:778
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:781 nova/api/openstack/wsgi.py:807
#: nova/api/openstack/compute/server_metadata.py:55
#: nova/api/openstack/compute/server_metadata.py:74
#: nova/api/openstack/compute/server_metadata.py:101
#: nova/api/openstack/compute/server_metadata.py:130
#: nova/api/openstack/compute/contrib/evacuate.py:54
msgid "Malformed request body"
msgstr ""

#: nova/api/openstack/wsgi.py:785
#, python-format
msgid "Action: '%(action)s', calling method: %(meth)s, body: %(body)s"
msgstr ""

#: nova/api/openstack/wsgi.py:804
msgid "Unsupported Content-Type"
msgstr ""

#: nova/api/openstack/wsgi.py:816
#, python-format
msgid ""
"Malformed request URL: URL's project_id '%(project_id)s' doesn't match "
"Context's project_id '%(context_project_id)s'"
msgstr ""

#: nova/api/openstack/compute/flavors.py:67
#: nova/api/openstack/compute/plugins/v3/flavors.py:73
#, python-format
msgid "Invalid is_public filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:90
#, python-format
msgid "Invalid minRam filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:97
#: nova/api/openstack/compute/plugins/v3/flavors.py:103
#, python-format
msgid "Invalid minDisk filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:105
#: nova/api/openstack/compute/servers.py:233
#: nova/api/openstack/compute/plugins/v3/flavors.py:112
#: nova/api/openstack/compute/plugins/v3/servers.py:380
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:38
#: nova/api/openstack/compute/images.py:85
#: nova/api/openstack/compute/images.py:101
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:43
#: nova/api/openstack/compute/plugins/v3/images.py:89
#: nova/api/openstack/compute/plugins/v3/images.py:107
msgid "Image not found."
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:76
msgid "Incorrect request body format"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:80
#: nova/api/openstack/compute/server_metadata.py:82
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:99
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:91
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:86
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:83
msgid "Request body and URI mismatch"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:83
#: nova/api/openstack/compute/server_metadata.py:86
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:102
msgid "Request body contains too many items"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:115
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:121
msgid "Invalid metadata key"
msgstr ""

#: nova/api/openstack/compute/images.py:106
#: nova/api/openstack/compute/plugins/v3/images.py:112
msgid "You are not allowed to delete the image."
msgstr ""

#: nova/api/openstack/compute/ips.py:45
#: nova/api/openstack/compute/plugins/v3/ips.py:56
msgid "Instance is not a member of specified network"
msgstr ""

#: nova/api/openstack/compute/limits.py:128
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: nova/api/openstack/compute/limits.py:256
msgid "This request was rate-limited."
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:38
#: nova/api/openstack/compute/server_metadata.py:126
#: nova/api/openstack/compute/server_metadata.py:177
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:47
msgid "Server does not exist"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:58
#: nova/api/openstack/compute/server_metadata.py:105
msgid "Malformed request body. metadata must be object"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:78
msgid "Malformed request body. meta item must be object"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:158
#: nova/api/openstack/compute/server_metadata.py:169
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:135
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:147
msgid "Metadata item was not found"
msgstr ""

#: nova/api/openstack/compute/servers.py:91
#: nova/api/openstack/compute/plugins/v3/servers.py:593
msgid "Can not find requested image"
msgstr ""

#: nova/api/openstack/compute/servers.py:92
#: nova/api/openstack/compute/servers.py:898
#: nova/api/openstack/compute/plugins/v3/servers.py:570
#: nova/api/openstack/compute/plugins/v3/servers.py:596
msgid "Invalid flavorRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:93
#: nova/api/openstack/compute/plugins/v3/servers.py:599
msgid "Invalid key_name provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:94
#: nova/api/openstack/compute/plugins/v3/servers.py:602
msgid "Invalid config_drive provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:167
#: nova/api/openstack/compute/contrib/cells.py:340
#: nova/api/openstack/compute/plugins/v3/servers.py:298
msgid "Invalid changes-since value"
msgstr ""

#: nova/api/openstack/compute/servers.py:192
#: nova/api/openstack/compute/plugins/v3/servers.py:323
msgid "Only administrators may list deleted instances"
msgstr ""

#: nova/api/openstack/compute/servers.py:281
#, python-format
msgid "Bad personality format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:284
msgid "Bad personality format"
msgstr ""

#: nova/api/openstack/compute/servers.py:287
#, python-format
msgid "Personality content for %s cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:302
#, python-format
msgid "Bad port format: port uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:310
msgid "Unknown argument : port"
msgstr ""

#: nova/api/openstack/compute/servers.py:319
#: nova/api/openstack/compute/plugins/v3/servers.py:446
#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:330
#, python-format
msgid "Invalid fixed IP address (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:337
#: nova/api/openstack/compute/plugins/v3/servers.py:454
#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr ""

#: nova/api/openstack/compute/servers.py:344
#: nova/api/openstack/compute/plugins/v3/servers.py:461
#, python-format
msgid "Bad network format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:347
#: nova/api/openstack/compute/servers.py:490
#: nova/api/openstack/compute/plugins/v3/servers.py:464
msgid "Bad networks format"
msgstr ""

#: nova/api/openstack/compute/servers.py:370
msgid "accessIPv4 is not proper IPv4 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:375
msgid "accessIPv6 is not proper IPv6 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:391
msgid "Userdata content cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:402
msgid "block_device_mapping must be a list"
msgstr ""

#: nova/api/openstack/compute/servers.py:422
#: nova/api/openstack/compute/plugins/v3/block_device_mapping.py:59
#: nova/api/openstack/compute/plugins/v3/block_device_mapping_v1.py:53
msgid ""
"Using different block_device_mapping syntaxes is not allowed in the same "
"request."
msgstr ""

#: nova/api/openstack/compute/servers.py:427
msgid "block_device_mapping_v2 must be a list"
msgstr ""

#: nova/api/openstack/compute/servers.py:507
msgid "Server name is not defined"
msgstr ""

#: nova/api/openstack/compute/servers.py:533
#: nova/api/validation/validators.py:114
#, python-format
msgid "Invalid input for field/attribute %(path)s. Value: %(value)s. %(message)s"
msgstr ""

#: nova/api/openstack/compute/servers.py:706
msgid "HostId cannot be updated."
msgstr ""

#: nova/api/openstack/compute/servers.py:710
msgid "Personality cannot be updated."
msgstr ""

#: nova/api/openstack/compute/servers.py:720
#: nova/api/openstack/compute/servers.py:838
#: nova/api/openstack/compute/servers.py:1025
#: nova/api/openstack/compute/plugins/v3/servers.py:771
#: nova/api/openstack/compute/plugins/v3/servers.py:883
#: nova/api/openstack/compute/plugins/v3/servers.py:987
msgid "Instance could not be found"
msgstr ""

#: nova/api/openstack/compute/servers.py:733
#: nova/api/openstack/compute/servers.py:749
#: nova/api/openstack/compute/plugins/v3/servers.py:787
#: nova/api/openstack/compute/plugins/v3/servers.py:805
msgid "Instance has not been resized."
msgstr ""

#: nova/api/openstack/compute/servers.py:752
#: nova/api/openstack/compute/plugins/v3/servers.py:808
msgid "Flavor used by the instance could not be found."
msgstr ""

#: nova/api/openstack/compute/servers.py:766
msgid "Argument 'type' for reboot must be a string"
msgstr ""

#: nova/api/openstack/compute/servers.py:772
msgid "Argument 'type' for reboot is not HARD or SOFT"
msgstr ""

#: nova/api/openstack/compute/servers.py:776
msgid "Missing argument 'type' for reboot"
msgstr ""

#: nova/api/openstack/compute/servers.py:803
#: nova/api/openstack/compute/plugins/v3/servers.py:848
msgid "Unable to locate requested flavor."
msgstr ""

#: nova/api/openstack/compute/servers.py:806
#: nova/api/openstack/compute/plugins/v3/servers.py:851
msgid "Resize requires a flavor change."
msgstr ""

#: nova/api/openstack/compute/servers.py:816
#: nova/api/openstack/compute/plugins/v3/servers.py:862
msgid "You are not authorized to access the image the instance was started with."
msgstr ""

#: nova/api/openstack/compute/servers.py:820
#: nova/api/openstack/compute/plugins/v3/servers.py:866
msgid "Image that the instance was started with could not be found."
msgstr ""

#: nova/api/openstack/compute/servers.py:827
#: nova/api/openstack/compute/plugins/v3/servers.py:873
msgid "Invalid instance image."
msgstr ""

#: nova/api/openstack/compute/servers.py:850
#: nova/api/openstack/compute/plugins/v3/servers.py:916
msgid "Missing imageRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:855
#: nova/api/openstack/compute/servers.py:863
#: nova/api/openstack/compute/plugins/v3/servers.py:897
msgid "Invalid imageRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:893
msgid "Missing flavorRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:907
msgid "No adminPass was specified"
msgstr ""

#: nova/api/openstack/compute/servers.py:920
#: nova/api/openstack/compute/plugins/v3/admin_password.py:58
msgid "Unable to set password on instance"
msgstr ""

#: nova/api/openstack/compute/servers.py:929
msgid "Unable to parse metadata key/value pairs."
msgstr ""

#: nova/api/openstack/compute/servers.py:940
msgid "Resize request has invalid 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:943
msgid "Resize requests require 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:961
msgid "Could not parse imageRef from request."
msgstr ""

#: nova/api/openstack/compute/servers.py:1031
#: nova/api/openstack/compute/plugins/v3/servers.py:990
msgid "Cannot find image for rebuild"
msgstr ""

#: nova/api/openstack/compute/servers.py:1065
msgid "createImage entity requires name attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1074
#: nova/api/openstack/compute/contrib/admin_actions.py:277
msgid "Invalid metadata"
msgstr ""

#: nova/api/openstack/compute/servers.py:1136
msgid "Invalid adminPass"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:64
#: nova/api/openstack/compute/contrib/admin_actions.py:86
#: nova/api/openstack/compute/contrib/admin_actions.py:108
#: nova/api/openstack/compute/contrib/admin_actions.py:130
#: nova/api/openstack/compute/contrib/admin_actions.py:171
#: nova/api/openstack/compute/contrib/admin_actions.py:190
#: nova/api/openstack/compute/contrib/admin_actions.py:209
#: nova/api/openstack/compute/contrib/admin_actions.py:228
#: nova/api/openstack/compute/contrib/admin_actions.py:379
msgid "Server not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:258
#, python-format
msgid "createBackup entity requires %s attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:262
msgid "Malformed createBackup entity"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:311
msgid ""
"host, block_migration and disk_over_commit must be specified for live "
"migration."
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:348
#, python-format
msgid "Live migration of instance %s to another host failed"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:351
#, python-format
msgid "Live migration of instance %(id)s to host %(host)s failed"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:369
#, python-format
msgid "Desired state must be specified.  Valid states are: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/agents.py:88
#: nova/api/openstack/compute/contrib/agents.py:106
#: nova/api/openstack/compute/contrib/agents.py:148
#: nova/api/openstack/compute/contrib/cloudpipe_update.py:56
#, python-format
msgid "Invalid request body: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:41
msgid "Only host parameter can be specified"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:44
msgid "Host parameter must be specified"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:178
#, python-format
msgid "Aggregates does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:182
#: nova/api/openstack/compute/contrib/flavormanage.py:52
#: nova/api/openstack/compute/contrib/keypairs.py:69
msgid "Invalid request body"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:199
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s: not found"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:204
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s: host exists"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:225
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s: not found"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:229
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s: invalid"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:248
msgid "The value of metadata must be a dict"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:261
#, python-format
msgid "Cannot set metadata %(metadata)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:80
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:81
#, python-format
msgid "Instance %(instance)s does not have a port with id %(port)s"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:105
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:108
msgid "Must not input both network_id and port_id"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:108
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:111
msgid "Must input network_id when request IP address"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:136
#: nova/api/openstack/compute/contrib/attach_interfaces.py:163
#: nova/api/openstack/compute/contrib/attach_interfaces.py:183
#: nova/network/security_group/neutron_driver.py:541
#: nova/network/security_group/neutron_driver.py:545
#: nova/network/security_group/neutron_driver.py:549
#: nova/network/security_group/neutron_driver.py:553
#: nova/network/security_group/neutron_driver.py:557
msgid "Network driver does not support this function."
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:139
msgid "Failed to attach interface"
msgstr ""

#: nova/api/openstack/compute/contrib/baremetal_nodes.py:64
msgid "Ironic client unavailable, cannot access Ironic."
msgstr ""

#: nova/api/openstack/compute/contrib/baremetal_nodes.py:85
#: nova/api/openstack/compute/plugins/v3/baremetal_nodes.py:83
#, python-format
msgid ""
"Command Not supported. Please use Ironic command %(cmd)s to perform this "
"action."
msgstr ""

#: nova/api/openstack/compute/contrib/baremetal_nodes.py:139
#: nova/api/openstack/compute/plugins/v3/baremetal_nodes.py:129
#, python-format
msgid "Node %s could not be found."
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:154
#, python-format
msgid "Cell %(id)s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:192
msgid "Cell name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:195
msgid "Cell name cannot contain '!' or '.'"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:201
msgid "Cell type must be 'parent' or 'child'"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:237
msgid "rpc_port must be integer"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:265
#: nova/api/openstack/compute/contrib/cells.py:291
msgid "No cell information in request"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:269
msgid "No cell name in request"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:328
msgid "Only 'updated_since', 'project_id' and 'deleted' are understood."
msgstr ""

#: nova/api/openstack/compute/contrib/certificates.py:44
#: nova/api/openstack/compute/plugins/v3/certificates.py:50
msgid "Only root certificate can be retrieved."
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe.py:127
#: nova/api/openstack/compute/plugins/v3/cloudpipe.py:134
msgid ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try "
"again in a few minutes"
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe_update.py:41
#: nova/api/openstack/compute/plugins/v3/cloudpipe.py:158
#, python-format
msgid "Unknown action %s"
msgstr ""

#: nova/api/openstack/compute/contrib/console_auth_tokens.py:40
#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:45
msgid "Token not found"
msgstr ""

#: nova/api/openstack/compute/contrib/console_auth_tokens.py:46
#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:51
msgid "The requested console type details are not accessible"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:47
msgid "os-getConsoleOutput malformed or missing from request body"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:58
msgid "Length in request body must be an integer value"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:66
msgid "Unable to get console"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:71
msgid "Unable to get console log, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:49
msgid "Instance not yet ready"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:56
msgid "Unable to get vnc console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:83
msgid "Unable to get spice console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:111
msgid "Unable to get rdp console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:140
msgid "Unable to get serial console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/disk_config.py:41
#: nova/api/openstack/compute/plugins/v3/disk_config.py:41
#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:61
msgid "host must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:68
msgid "onSharedStorage must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:76
#: nova/api/openstack/compute/plugins/v3/evacuate.py:67
msgid "admin password can't be changed on existing disk"
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:87
#: nova/api/openstack/compute/plugins/v3/evacuate.py:78
#, python-format
msgid "Compute host %s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:93
#: nova/api/openstack/compute/plugins/v3/evacuate.py:83
msgid "The target host can't be the same one."
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:43
#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:59
#, python-format
msgid "Fixed IP %s has been deleted"
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:76
#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:101
#, python-format
msgid "Fixed IP %s not found"
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:60
#: nova/api/openstack/compute/plugins/v3/flavor_access.py:59
msgid "Access list not available for public flavors."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:72
msgid "No request body"
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:115
#: nova/api/openstack/compute/contrib/flavor_access.py:140
msgid "Missing tenant parameter"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:40
msgid "No Request Body"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:45
msgid "Bad extra_specs provided"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:51
msgid "Fail to validate provided extra specs keys. Expected string"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:123
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:141
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:112
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:133
#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(key)s."
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:57
msgid "A valid name parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:63
msgid "A valid ram parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:68
msgid "A valid vcpus parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:73
msgid "A valid disk parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:94
msgid "Unable to get dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:134
msgid "Unable to create dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:156
msgid "Unable to delete dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:188
msgid "Unable to get dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:192
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:193
msgid "DNS entries not found."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:229
msgid "Unable to create dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:249
msgid "Unable to delete dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:93
#: nova/api/openstack/compute/contrib/floating_ips.py:142
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:104
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:159
#, python-format
msgid "Floating ip not found for id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:119
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:134
#, python-format
msgid "No more floating ips in pool %s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:121
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:136
msgid "No more floating ips available."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:125
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:140
#, python-format
msgid "IP allocation over quota in pool %s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:127
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:142
msgid "IP allocation over quota."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:175
#: nova/api/openstack/compute/contrib/floating_ips.py:256
#: nova/api/openstack/compute/contrib/security_groups.py:353
#: nova/api/openstack/compute/plugins/v3/security_groups.py:370
msgid "Missing parameter dict"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:178
#: nova/api/openstack/compute/contrib/floating_ips.py:259
msgid "Address not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:187
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:200
msgid "No nw_info cache associated with instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:192
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:205
msgid "No fixed ips associated to instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:203
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:215
msgid "Specified fixed address not assigned to instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:211
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:223
#, python-format
msgid ""
"Unable to associate floating ip %(address)s to any fixed IPs for instance"
" %(id)s. Instance has no fixed IPv4 addresses to associate."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:226
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:238
msgid "floating ip is already associated"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:229
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:241
msgid "l3driver call to add floating ip failed"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:232
#: nova/api/openstack/compute/contrib/floating_ips.py:267
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:244
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:274
msgid "floating ip not found"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:237
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:249
#, python-format
msgid ""
"Unable to associate floating ip %(address)s to fixed ip %(fixed_address)s"
" for instance %(id)s. Error: %(error)s"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:282
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:289
msgid "Floating ip is not associated"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:286
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:293
#, python-format
msgid "Floating ip %(address)s is not associated with instance %(id)s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:122
#: nova/api/openstack/compute/contrib/services.py:135
#: nova/api/openstack/compute/plugins/v3/floating_ips_bulk.py:123
#: nova/api/openstack/compute/plugins/v3/services.py:155
msgid "Unknown action"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:150
#: nova/api/openstack/compute/plugins/v3/floating_ips_bulk.py:146
#: nova/cmd/manage.py:424
#, python-format
msgid "/%s should be specified as single address(es) not in cidr format"
msgstr ""

#: nova/api/openstack/compute/contrib/fping.py:52
#: nova/api/openstack/compute/plugins/v3/fping.py:48
msgid "fping utility is not found."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:137
#, python-format
msgid "Invalid update setting: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:140
#, python-format
msgid "Invalid status: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:142
#, python-format
msgid "Invalid mode: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:144
msgid "'status' or 'maintenance_mode' needed for host update"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:166
msgid "Virt driver does not implement host maintenance mode."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:190
msgid "Virt driver does not implement host disabled status."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:213
msgid "Virt driver does not implement host power management."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:129
#: nova/api/openstack/compute/contrib/hypervisors.py:142
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:111
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:125
#, python-format
msgid "Hypervisor with ID '%s' could not be found."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:150
msgid "Virt driver does not implement uptime function."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:177
#: nova/api/openstack/compute/contrib/hypervisors.py:193
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:153
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:163
#, python-format
msgid "No hypervisor matching '%s' could be found."
msgstr ""

#: nova/api/openstack/compute/contrib/instance_usage_audit_log.py:57
#: nova/api/openstack/compute/plugins/v3/instance_usage_audit_log.py:59
#, python-format
msgid "Invalid timestamp for date %s"
msgstr ""

#: nova/api/openstack/compute/contrib/keypairs.py:87
#: nova/api/openstack/compute/plugins/v3/keypairs.py:138
msgid "Quota exceeded, too many key pairs."
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:48
msgid "Missing 'networkId' argument for addFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:68
msgid "Missing 'address' argument for removeFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:43
#: nova/api/openstack/compute/contrib/networks_associate.py:62
#: nova/api/openstack/compute/contrib/networks_associate.py:83
#: nova/api/openstack/compute/contrib/os_networks.py:110
#: nova/api/openstack/compute/contrib/os_networks.py:125
#: nova/api/openstack/compute/contrib/os_networks.py:137
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:105
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:136
#: nova/api/openstack/compute/plugins/v3/networks.py:103
#: nova/api/openstack/compute/plugins/v3/networks.py:116
#: nova/api/openstack/compute/plugins/v3/networks.py:131
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:44
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:58
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:75
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:102
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:135
msgid "Network not found"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:46
msgid "Disassociate host is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:65
msgid "Disassociate project is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:86
msgid "Associate host is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:113
msgid "Disassociate network is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:152
msgid "Missing network in body"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:156
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:158
msgid "Network label is required"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:160
msgid "Network cidr or cidr_v6 is required"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:169
#, python-format
msgid "%s is not a valid ip network"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:205
msgid "VLAN support must be enabled"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:163
msgid "No CIDR requested"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:169
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:158
msgid "Requested network does not contain enough (2+) usable hosts"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:173
msgid "CIDR is malformed."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:176
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:162
msgid "Address could not be converted."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:184
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:170
msgid "Quota exceeded, too many networks."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:199
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:185
msgid "Create networks failed"
msgstr ""

#: nova/api/openstack/compute/contrib/quota_classes.py:79
msgid "quota_class_set not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/quota_classes.py:94
#: nova/api/openstack/compute/contrib/quotas.py:188
#, python-format
msgid "Bad key(s) %s in quota_set"
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:76
#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be in the range of -1 and "
"%(max)s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:85
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:62
#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be greater than or equal to "
"already used and reserved %(minimum)s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:91
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:68
#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be less than or equal to "
"%(maximum)s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:164
msgid "quota_set not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/scheduler_hints.py:37
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:55
#: nova/api/openstack/compute/contrib/security_groups.py:259
#: nova/api/openstack/compute/plugins/v3/security_group_default_rules.py:55
#: nova/api/openstack/compute/plugins/v3/security_groups.py:258
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:59
#: nova/api/openstack/compute/plugins/v3/security_group_default_rules.py:59
msgid "This default rule already exists."
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:82
msgid "security group default rule not found"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:134
#: nova/api/openstack/compute/plugins/v3/security_groups.py:110
msgid "The request body can't be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:138
#: nova/api/openstack/compute/plugins/v3/security_groups.py:114
#, python-format
msgid "Missing parameter %s"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:267
#: nova/api/openstack/compute/plugins/v3/security_groups.py:266
#, python-format
msgid "Bad prefix for network in cidr %s"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:356
#: nova/api/openstack/compute/plugins/v3/security_groups.py:373
msgid "Security group not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:360
#: nova/api/openstack/compute/plugins/v3/security_groups.py:377
msgid "Security group name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/server_diagnostics.py:44
msgid "Unable to get diagnostics, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:61
#, python-format
msgid "Invalid event status `%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:69
#, python-format
msgid "event entity requires key %(key)s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:73
#, python-format
msgid "event entity contains unsupported items: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:120
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:108
msgid "No instances found for any event"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:83
msgid "Conflicting policies configured!"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:88
#, python-format
msgid "Invalid policies: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:93
msgid "Duplicate policies configured!"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:98
msgid "the body is invalid."
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:107
#, python-format
msgid "'%s' is either missing or empty."
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:113
#, python-format
msgid "Invalid format for name: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:121
#, python-format
msgid "'%s' is not a list"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:125
#, python-format
msgid "unsupported fields: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:202
#: nova/api/openstack/compute/plugins/v3/server_groups.py:139
msgid "Quota exceeded, too many server groups."
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:37
msgid "Instance not found"
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:109
#: nova/api/openstack/compute/plugins/v3/services.py:170
#, python-format
msgid "Service %s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:154
msgid ""
"The string containing the reason for disabling the service contains "
"invalid characters or is too long."
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:162
msgid "Invalid attribute in the request"
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:164
#: nova/api/openstack/compute/plugins/v3/services.py:100
msgid "Missing disabled reason field"
msgstr ""

#: nova/api/openstack/compute/contrib/simple_tenant_usage.py:196
#: nova/api/openstack/compute/plugins/v3/simple_tenant_usage.py:195
msgid "Datetime is in invalid format"
msgstr ""

#: nova/api/openstack/compute/contrib/simple_tenant_usage.py:215
#: nova/api/openstack/compute/plugins/v3/simple_tenant_usage.py:214
msgid "Invalid start time. The start time cannot occur after the end time."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:143
msgid "volume not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:255
#: nova/api/openstack/compute/contrib/volumes.py:404
#: nova/api/openstack/compute/plugins/v3/volumes.py:248
#: nova/api/openstack/compute/plugins/v3/volumes.py:379
#, python-format
msgid "Instance %s is not attached."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:266
#: nova/api/openstack/compute/contrib/volumes.py:383
#: nova/api/openstack/compute/contrib/volumes.py:430
#: nova/api/openstack/compute/plugins/v3/volumes.py:259
#: nova/api/openstack/compute/plugins/v3/volumes.py:408
#, python-format
msgid "volume_id not found: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:276
#, python-format
msgid "Bad volumeId format: volumeId is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:287
#: nova/api/openstack/compute/contrib/volumes.py:344
msgid "volumeAttachment not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:292
#: nova/api/openstack/compute/contrib/volumes.py:353
msgid "volumeId must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:413
#: nova/api/openstack/compute/plugins/v3/volumes.py:388
msgid "Can't detach root device volume"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:536
msgid "snapshot not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:549
#, python-format
msgid "Invalid value '%s' for force."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/aggregates.py:165
#: nova/api/openstack/compute/plugins/v3/aggregates.py:169
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/cells.py:188
#, python-format
msgid "Cell %s doesn't exist."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:40
msgid "token not provided"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:104
#, python-format
msgid "Fixed IP %s not valid"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/flavor_access.py:113
msgid "Can not add access to a public flavor."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/flavors.py:96
#, python-format
msgid "Invalid min_ram filter [%s]"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:122
msgid "you can not pass project if the scope is private"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:125
msgid "you can not pass av_zone if the scope is public"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/instance_actions.py:71
#, python-format
msgid "Action %s not found"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/quota_sets.py:53
#, python-format
msgid "Quota limit %(limit)s for %(resource)s must be -1 or greater."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:430
msgid "Unknown argument: port"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:433
#, python-format
msgid ""
"Specified Fixed IP '%(addr)s' cannot be used with port '%(port)s': port "
"already has a Fixed IP allocated."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/services.py:128
msgid "Missing forced_down field"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/volumes.py:355
msgid "The volume was either invalid or not attached to the instance."
msgstr ""

#: nova/cells/messaging.py:351
msgid "No cell given in routing path."
msgstr ""

#: nova/cells/messaging.py:370 nova/cells/messaging.py:378
#, python-format
msgid "destination is %(target_cell)s but routing_path is %(routing_path)s"
msgstr ""

#: nova/cells/messaging.py:390
#, python-format
msgid "Unknown %(cell_type)s when routing to %(target_cell)s"
msgstr ""

#: nova/cells/messaging.py:664
#, python-format
msgid "Unknown method '%(method)s' in compute API"
msgstr ""

#: nova/cloudpipe/pipelib.py:47
msgid "Flavor for vpn instances"
msgstr ""

#: nova/cloudpipe/pipelib.py:50
msgid "Template for cloudpipe instance boot script"
msgstr ""

#: nova/cloudpipe/pipelib.py:53
msgid "Network to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:56
msgid "Netmask to push into openvpn config"
msgstr ""

#: nova/cmd/manage.py:221
msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using 'nova-manage db sync' before running this "
"command."
msgstr ""

#: nova/cmd/manage.py:262
msgid "Quota limit must be -1 or greater."
msgstr ""

#: nova/cmd/manage.py:266
#, python-format
msgid "Quota limit must be greater than %s."
msgstr ""

#: nova/cmd/manage.py:269
#, python-format
msgid "Quota limit must be less than %s."
msgstr ""

#: nova/cmd/manage.py:278
#, python-format
msgid "%(key)s is not a valid quota key. Valid options are: %(options)s."
msgstr ""

#: nova/cmd/manage.py:284
msgid "Quota"
msgstr ""

#: nova/cmd/manage.py:285
msgid "Limit"
msgstr ""

#: nova/cmd/manage.py:286
msgid "In Use"
msgstr ""

#: nova/cmd/manage.py:287
msgid "Reserved"
msgstr ""

#: nova/cmd/manage.py:330 nova/cmd/manage.py:405 nova/cmd/manage.py:745
#: nova/cmd/manage.py:759 nova/cmd/manage.py:829
#, python-format
msgid "error: %s"
msgstr ""

#: nova/cmd/manage.py:338
msgid "network"
msgstr ""

#: nova/cmd/manage.py:339
msgid "IP address"
msgstr ""

#: nova/cmd/manage.py:340
msgid "hostname"
msgstr ""

#: nova/cmd/manage.py:341 nova/cmd/manage.py:885
msgid "host"
msgstr ""

#: nova/cmd/manage.py:353 nova/cmd/manage.py:377
msgid "No fixed IP found."
msgstr ""

#: nova/cmd/manage.py:369
#, python-format
msgid "WARNING: fixed ip %s allocated to missing instance"
msgstr ""

#: nova/cmd/manage.py:431
#, python-format
msgid ""
"Too many IP addresses will be generated.  Please increase /%s to reduce "
"the number generated."
msgstr ""

#: nova/cmd/manage.py:482
msgid "No floating IP addresses have been defined."
msgstr ""

#: nova/cmd/manage.py:501
msgid ""
"ERROR: Network commands are not supported when using the Neutron API.  "
"Use python-neutronclient instead."
msgstr ""

#: nova/cmd/manage.py:558
msgid "id"
msgstr ""

#: nova/cmd/manage.py:559
msgid "IPv4"
msgstr ""

#: nova/cmd/manage.py:560
msgid "IPv6"
msgstr ""

#: nova/cmd/manage.py:561
msgid "start address"
msgstr ""

#: nova/cmd/manage.py:562
msgid "DNS1"
msgstr ""

#: nova/cmd/manage.py:563
msgid "DNS2"
msgstr ""

#: nova/cmd/manage.py:564
msgid "VlanID"
msgstr ""

#: nova/cmd/manage.py:565 nova/cmd/manage.py:672
msgid "project"
msgstr ""

#: nova/cmd/manage.py:566
msgid "uuid"
msgstr ""

#: nova/cmd/manage.py:573
msgid "No networks found"
msgstr ""

#: nova/cmd/manage.py:592
msgid "Please specify either fixed_range or uuid"
msgstr ""

#: nova/cmd/manage.py:597
msgid "UUID is required to delete Neutron Networks"
msgstr ""

#: nova/cmd/manage.py:600
msgid "Deleting by fixed_range is not supported with the NeutronManager"
msgstr ""

#: nova/cmd/manage.py:664
msgid "instance"
msgstr ""

#: nova/cmd/manage.py:665
msgid "node"
msgstr ""

#: nova/cmd/manage.py:666
msgid "type"
msgstr ""

#: nova/cmd/manage.py:667
msgid "state"
msgstr ""

#: nova/cmd/manage.py:668
msgid "launched"
msgstr ""

#: nova/cmd/manage.py:669
msgid "image"
msgstr ""

#: nova/cmd/manage.py:670
msgid "kernel"
msgstr ""

#: nova/cmd/manage.py:671
msgid "ramdisk"
msgstr ""

#: nova/cmd/manage.py:673
msgid "user"
msgstr ""

#: nova/cmd/manage.py:674 nova/cmd/manage.py:886
msgid "zone"
msgstr ""

#: nova/cmd/manage.py:675
msgid "index"
msgstr ""

#: nova/cmd/manage.py:720
msgid "Binary"
msgstr ""

#: nova/cmd/manage.py:721
msgid "Host"
msgstr ""

#: nova/cmd/manage.py:722
msgid "Zone"
msgstr ""

#: nova/cmd/manage.py:723
msgid "Status"
msgstr ""

#: nova/cmd/manage.py:724
msgid "State"
msgstr ""

#: nova/cmd/manage.py:725
msgid "Updated_At"
msgstr ""

#: nova/cmd/manage.py:747
#, python-format
msgid "Service %(service)s on host %(host)s enabled."
msgstr ""

#: nova/cmd/manage.py:761
#, python-format
msgid "Service %(service)s on host %(host)s disabled."
msgstr ""

#: nova/cmd/manage.py:833
msgid "An unexpected error has occurred."
msgstr ""

#: nova/cmd/manage.py:834
msgid "[Result]"
msgstr ""

#: nova/cmd/manage.py:838
msgid "HOST"
msgstr ""

#: nova/cmd/manage.py:839
msgid "PROJECT"
msgstr ""

#: nova/cmd/manage.py:840
msgid "cpu"
msgstr ""

#: nova/cmd/manage.py:841
msgid "mem(mb)"
msgstr ""

#: nova/cmd/manage.py:842
msgid "hdd"
msgstr ""

#: nova/cmd/manage.py:950
msgid "Must supply a positive value for max_rows"
msgstr ""

#: nova/cmd/manage.py:969
#, python-format
msgid "Deleted %(records)d records from table '%(table_name)s'."
msgstr ""

#: nova/cmd/manage.py:973
#, python-format
msgid ""
"There are %(records)d records in the '%(table_name)s' table where the "
"uuid or instance_uuid column is NULL. Run this command again with the "
"--delete option after you have backed up any necessary data."
msgstr ""

#: nova/cmd/manage.py:981
msgid "There were no records found where instance_uuid was NULL."
msgstr ""

#: nova/cmd/manage.py:1056
#, python-format
msgid "Hypervisor: %s"
msgstr ""

#: nova/cmd/manage.py:1105
#, python-format
msgid "Line %(linenum)d : %(line)s"
msgstr ""

#: nova/cmd/manage.py:1108
msgid "No errors in logfiles!"
msgstr ""

#: nova/cmd/manage.py:1122
msgid "Unable to find system log file!"
msgstr ""

#: nova/cmd/manage.py:1126
#, python-format
msgid "Last %s nova syslog entries:-"
msgstr ""

#: nova/cmd/manage.py:1135
msgid "No nova entries in syslog!"
msgstr ""

#: nova/cmd/manage.py:1152
#, python-format
msgid "Invalid broker_hosts value: %s. It should be in hostname:port format"
msgstr ""

#: nova/cmd/manage.py:1158
#, python-format
msgid "Invalid port value: %s. It should be an integer"
msgstr ""

#: nova/cmd/manage.py:1171
#, python-format
msgid "Invalid port value: %s. Should be an integer"
msgstr ""

#: nova/cmd/manage.py:1274
msgid "cell_uuid must be set"
msgstr ""

#: nova/cmd/manage.py:1394
#, python-format
msgid "Could not read %s. Re-running with sudo"
msgstr ""

#: nova/cmd/manage.py:1398
msgid "sudo failed, continuing as if nothing happened"
msgstr ""

#: nova/cmd/manage.py:1400
msgid "Please re-run nova-manage as root."
msgstr ""

#: nova/cmd/manage.py:1447
msgid "Command failed, please check log for more info"
msgstr ""

#: nova/compute/api.py:422
msgid "Cannot run any more instances of this type."
msgstr ""

#: nova/compute/api.py:428
#, python-format
msgid "Can only run %s more instances of this type."
msgstr ""

#: nova/compute/api.py:465
msgid "Metadata type should be dict."
msgstr ""

#: nova/compute/api.py:487
msgid "Metadata property key greater than 255 characters"
msgstr ""

#: nova/compute/api.py:490
msgid "Metadata property value greater than 255 characters"
msgstr ""

#: nova/compute/api.py:739
#, python-format
msgid "The volume cannot be assigned the same device name as the root device %s"
msgstr ""

#: nova/compute/api.py:775
msgid "Cannot attach one or more volumes to multiple instances"
msgstr ""

#: nova/compute/api.py:818
msgid "The requested availability zone is not available"
msgstr ""

#: nova/compute/api.py:961
msgid "Quota exceeded, too many servers in group"
msgstr ""

#: nova/compute/api.py:1049
msgid "Server group scheduler hint must be a UUID."
msgstr ""

#: nova/compute/api.py:1251
msgid ""
"Images with destination_type 'volume' need to have a non-zero size "
"specified"
msgstr ""

#: nova/compute/api.py:1277
msgid "Blank volumes (source: 'blank', dest: 'volume') need to have non-zero size"
msgstr ""

#: nova/compute/api.py:1291
msgid "More than one swap drive requested."
msgstr ""

#: nova/compute/api.py:1441
msgid ""
"Unable to launch multiple instances with a single configured port ID. "
"Please launch your instance one by one with different ports."
msgstr ""

#: nova/compute/api.py:1451
msgid "max_count cannot be greater than 1 if an fixed_ip is specified."
msgstr ""

#: nova/compute/api.py:2279
#, python-format
msgid "snapshot for %s"
msgstr ""

#: nova/compute/api.py:2630
msgid "Resize to zero disk flavor is not allowed."
msgstr ""

#: nova/compute/api.py:2846
msgid "Cannot rescue a volume-backed instance"
msgstr ""

#: nova/compute/api.py:3115
msgid "Volume must be attached in order to detach."
msgstr ""

#: nova/compute/api.py:3135
msgid "Old volume is attached to a different instance."
msgstr ""

#: nova/compute/api.py:3138
msgid "New volume must be detached in order to swap."
msgstr ""

#: nova/compute/api.py:3141
msgid "New volume must be the same size or larger."
msgstr ""

#: nova/compute/api.py:3638
msgid "Host aggregate is not empty"
msgstr ""

#: nova/compute/api.py:3669
#, python-format
msgid "One or more hosts already in availability zone(s) %s"
msgstr ""

#: nova/compute/api.py:3689
#, python-format
msgid "Unexpected aggregate action %s"
msgstr ""

#: nova/compute/api.py:3769
msgid "Keypair name contains unsafe characters"
msgstr ""

#: nova/compute/api.py:3775
msgid "Keypair name must be string and between 1 and 255 characters long"
msgstr ""

#: nova/compute/api.py:3882
#, python-format
msgid "Security group %s is not a string or unicode"
msgstr ""

#: nova/compute/api.py:3892
#, python-format
msgid ""
"Value (%(value)s) for parameter Group%(property)s is invalid. Content "
"limited to '%(allowed)s'."
msgstr ""

#: nova/compute/api.py:3913
msgid "Quota exceeded, too many security groups."
msgstr ""

#: nova/compute/api.py:3928
#, python-format
msgid "Security group %s already exists"
msgstr ""

#: nova/compute/api.py:3941
#, python-format
msgid "Unable to update system group '%s'"
msgstr ""

#: nova/compute/api.py:4003
#, python-format
msgid "Unable to delete system group '%s'"
msgstr ""

#: nova/compute/api.py:4008
msgid "Security group is still in use"
msgstr ""

#: nova/compute/api.py:4097
#, python-format
msgid "Rule (%s) not found"
msgstr ""

#: nova/compute/api.py:4113
msgid "Quota exceeded, too many security group rules."
msgstr ""

#: nova/compute/api.py:4116
#, python-format
msgid ""
"Security group %(name)s added %(protocol)s ingress "
"(%(from_port)s:%(to_port)s)"
msgstr ""

#: nova/compute/api.py:4131
#, python-format
msgid ""
"Security group %(name)s removed %(protocol)s ingress "
"(%(from_port)s:%(to_port)s)"
msgstr ""

#: nova/compute/api.py:4183
msgid "Security group id should be integer"
msgstr ""

#: nova/compute/claims.py:152
#, python-format
msgid "Attempting claim: memory %(memory_mb)d MB, disk %(disk_gb)d GB"
msgstr ""

#: nova/compute/claims.py:170
msgid "memory"
msgstr ""

#: nova/compute/claims.py:179
msgid "disk"
msgstr ""

#: nova/compute/claims.py:195 nova/compute/claims.py:300
msgid "Claim pci failed."
msgstr ""

#: nova/compute/claims.py:223
msgid ""
"Requested instance NUMA topology together with requested PCI devices "
"cannot fit the given host NUMA topology"
msgstr ""

#: nova/compute/claims.py:227
msgid "Requested instance NUMA topology cannot fit the given host NUMA topology"
msgstr ""

#: nova/compute/claims.py:256
#, python-format
msgid "Free %(type)s %(free).02f %(unit)s < requested %(requested)d %(unit)s"
msgstr ""

#: nova/compute/flavors.py:116
msgid "Flavor names can only contain printable characters and horizontal spaces."
msgstr ""

#: nova/compute/flavors.py:126
msgid "id cannot contain leading and/or trailing whitespace(s)"
msgstr ""

#: nova/compute/flavors.py:136
msgid ""
"Flavor id can only contain letters from A-Z (both cases), periods, "
"dashes, underscores and spaces."
msgstr ""

#: nova/compute/flavors.py:162
#, python-format
msgid "'rxtx_factor' argument must be a float between 0 and %g"
msgstr ""

#: nova/compute/flavors.py:173
msgid "is_public must be a boolean"
msgstr ""

#: nova/compute/flavors.py:366
msgid ""
"Key Names can only contain alphanumeric characters, periods, dashes, "
"underscores, colons and spaces."
msgstr ""

#: nova/compute/manager.py:584
msgid "Instance event failed"
msgstr ""

#: nova/compute/manager.py:704
#, python-format
msgid "%s is not a valid node managed by this compute host."
msgstr ""

#: nova/compute/manager.py:1430
msgid "Anti-affinity instance group policy was violated."
msgstr ""

#: nova/compute/manager.py:1438
msgid "Affinity instance group policy was violated."
msgstr ""

#: nova/compute/manager.py:2009
#, python-format
msgid "Failed to allocate the network(s) with error %s, not rescheduling."
msgstr ""

#: nova/compute/manager.py:2019 nova/compute/manager.py:2074
msgid "Failed to allocate the network(s), not rescheduling."
msgstr ""

#: nova/compute/manager.py:2051
msgid "Success"
msgstr ""

#: nova/compute/manager.py:2109
msgid "Failure prepping block device."
msgstr ""

#: nova/compute/manager.py:2135
msgid "Could not clean up failed build, not rescheduling"
msgstr ""

#: nova/compute/manager.py:2616
msgid "Invalid state of instance files on shared storage"
msgstr ""

#: nova/compute/manager.py:3042
#, python-format
msgid "instance %s is not running"
msgstr ""

#: nova/compute/manager.py:3059
msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr ""

#: nova/compute/manager.py:3074
msgid "error setting admin password"
msgstr ""

#: nova/compute/manager.py:3158
#, python-format
msgid "Driver Error: %s"
msgstr ""

#: nova/compute/manager.py:3493
msgid "Instance has no source host"
msgstr ""

#: nova/compute/manager.py:3505
msgid "destination same as source!"
msgstr ""

#: nova/compute/manager.py:4779
#, python-format
msgid "Port %s is not attached"
msgstr ""

#: nova/compute/manager.py:5464
#, python-format
msgid "Instance %s not found"
msgstr ""

#: nova/compute/manager.py:5469
msgid "In ERROR state"
msgstr ""

#: nova/compute/manager.py:5497
#, python-format
msgid "In states %(vm_state)s/%(task_state)s, not RESIZED/None"
msgstr ""

#: nova/compute/manager.py:6134
#, python-format
msgid "Unrecognized value '%s' for CONF.running_deleted_instance_action"
msgstr ""

#: nova/compute/resource_tracker.py:834
#, python-format
msgid "Missing keys: %s"
msgstr ""

#: nova/compute/rpcapi.py:63
msgid "No compute host specified"
msgstr ""

#: nova/compute/rpcapi.py:65
#, python-format
msgid "Unable to find host for Instance %s"
msgstr ""

#: nova/compute/stats.py:50
msgid "Unexpected type adding stats"
msgstr ""

#: nova/conductor/manager.py:567
msgid "No valid host found for cold migrate"
msgstr ""

#: nova/conductor/manager.py:569
msgid "No valid host found for resize"
msgstr ""

#: nova/conductor/manager.py:780
#, python-format
msgid "Unshelve attempted but the image %s cannot be found."
msgstr ""

#: nova/conductor/tasks/live_migrate.py:118
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of "
"memory(host:%(avail)s <= instance:%(mem_inst)s)"
msgstr ""

#: nova/conductor/tasks/live_migrate.py:180
#, python-format
msgid ""
"Exceeded max scheduling retries %(max_retries)d for instance "
"%(instance_uuid)s during live migration"
msgstr ""

#: nova/console/websocketproxy.py:57
msgid "No access_url in connection_info. Cannot validate protocol"
msgstr ""

#: nova/console/websocketproxy.py:86
#, python-format
msgid ""
"We do not support scheme '%s' under Python < 2.7.4, please use http or "
"https"
msgstr ""

#: nova/console/websocketproxy.py:126
msgid "Origin header not valid."
msgstr ""

#: nova/console/websocketproxy.py:129
msgid "Origin header does not match this host."
msgstr ""

#: nova/console/websocketproxy.py:132
msgid "Origin header protocol does not match this host."
msgstr ""

#: nova/console/websocketproxy.py:135
#, python-format
msgid "connect info: %s"
msgstr ""

#: nova/console/websocketproxy.py:140
#, python-format
msgid "connecting to: %(host)s:%(port)s"
msgstr ""

#: nova/console/websocketproxy.py:163
#, python-format
msgid "%(host)s:%(port)s: Target closed"
msgstr ""

#: nova/console/xvp.py:203
msgid "Failed to run xvp."
msgstr ""

#: nova/db/sqlalchemy/api.py:302
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: nova/db/sqlalchemy/api.py:999
#, python-format
msgid "Invalid floating IP %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1313
#, python-format
msgid "Invalid fixed IP Address %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1469
#, python-format
msgid "Invalid virtual interface address %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1563
#, python-format
msgid ""
"Unknown osapi_compute_unique_server_name_scope value: %s Flag must be "
"empty, \"global\" or \"project\""
msgstr ""

#: nova/db/sqlalchemy/api.py:1754
#, python-format
msgid "Invalid instance id %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:2123
#, python-format
msgid "Invalid field name: %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:2280
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: nova/db/sqlalchemy/api.py:2291
msgid "Sort direction size exceeds sort key size"
msgstr ""

#: nova/db/sqlalchemy/api.py:5626
#, python-format
msgid "Add metadata failed for aggregate %(id)s after %(retries)s retries"
msgstr ""

#: nova/db/sqlalchemy/api.py:6023
#, python-format
msgid "IntegrityError detected when archiving table %s"
msgstr ""

#: nova/db/sqlalchemy/migration.py:95
msgid "version should be an integer"
msgstr ""

#: nova/db/sqlalchemy/migration.py:101
msgid "Cannot run 'db sync' until 'db contract' is run"
msgstr ""

#: nova/db/sqlalchemy/migration.py:129
msgid "Upgrade DB using Essex release first."
msgstr ""

#: nova/db/sqlalchemy/migration.py:743 nova/db/sqlalchemy/migration.py:761
#, python-format
msgid "Unknown alembic cmd %s"
msgstr ""

#: nova/db/sqlalchemy/migration.py:876
msgid "Dependency loop exists in database migrations"
msgstr ""

#: nova/db/sqlalchemy/migration.py:1041 nova/db/sqlalchemy/migration.py:1055
msgid "expand phase still has operations that need to be executed"
msgstr ""

#: nova/db/sqlalchemy/migration.py:1058
msgid "migrate phase still has operations that need to be executed"
msgstr ""

#: nova/db/sqlalchemy/utils.py:69
#, python-format
msgid "Missing column %(table)s.%(column)s in shadow table"
msgstr ""

#: nova/db/sqlalchemy/utils.py:75
#, python-format
msgid ""
"Different types in %(table)s.%(column)s and shadow table: %(c_type)s "
"%(shadow_c_type)s"
msgstr ""

#: nova/db/sqlalchemy/utils.py:84
#, python-format
msgid "Extra column %(table)s.%(column)s in shadow table"
msgstr ""

#: nova/db/sqlalchemy/utils.py:103
msgid "Specify `table_name` or `table` param"
msgstr ""

#: nova/db/sqlalchemy/utils.py:106
msgid "Specify only one param `table_name` `table`"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/267_instance_uuid_non_nullable.py:54
#, python-format
msgid ""
"There are %(records)d records in the '%(table_name)s' table where the "
"uuid or instance_uuid column is NULL. These must be manually cleaned up "
"before the migration will pass. Consider running the 'nova-manage db "
"null_instance_uuid_scan' command."
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/291_enforce_flavors_migrated.py:30
#, python-format
msgid ""
"There are still %(count)i unmigrated flavor records. Migration cannot "
"continue until all instance flavor records have been migrated to the new "
"format. Please run `nova-manage db migrate_flavor_data' first."
msgstr ""

#: nova/image/s3.py:400
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: nova/image/s3.py:407
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: nova/image/s3.py:418
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: nova/image/s3.py:430
msgid "Unsafe filenames in image"
msgstr ""

#: nova/image/download/file.py:29
msgid ""
"List of file systems that are configured in this file in the "
"image_file_url:<list entry name> sections"
msgstr ""

#: nova/image/download/file.py:77
msgid ""
"A unique ID given to each file system.  This is value is set in Glance "
"and agreed upon here so that the operator knowns they are dealing with "
"the same file system."
msgstr ""

#: nova/image/download/file.py:82
msgid "The path at which the file system is mounted."
msgstr ""

#: nova/image/download/file.py:91
#, python-format
msgid "The group %(group_name)s must be configured with an id."
msgstr ""

#: nova/image/download/file.py:109
#, python-format
msgid "The key %s is required in all file system descriptions."
msgstr ""

#: nova/image/download/file.py:119
#, python-format
msgid ""
"The key %(r)s is required in the location metadata to access the url "
"%(url)s."
msgstr ""

#: nova/image/download/file.py:126
#, python-format
msgid "The ID %(id)s is unknown."
msgstr ""

#: nova/image/download/file.py:134
#, python-format
msgid ""
"The mount point advertised by glance: %(glance_mount)s, does not match "
"the URL path: %(path)s"
msgstr ""

#: nova/image/download/file.py:152
#, python-format
msgid "No matching ID for the URL %s was found."
msgstr ""

#: nova/ipv6/account_identifier.py:39 nova/ipv6/rfc2462.py:34
#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:41 nova/ipv6/rfc2462.py:36
#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:43
#, python-format
msgid "Bad project_id for to_global_ipv6: %s"
msgstr ""

#: nova/keymgr/barbican.py:78
msgid "User is not authorized to use key manager."
msgstr ""

#: nova/keymgr/conf_key_mgr.py:58
msgid "keymgr.fixed_key not defined"
msgstr ""

#: nova/keymgr/single_key_mgr.py:60
msgid "cannot store arbitrary keys"
msgstr ""

#: nova/keymgr/single_key_mgr.py:70
msgid "cannot delete non-existent key"
msgstr ""

#: nova/network/base_api.py:71
msgid "instance is a required argument to use @refresh_cache"
msgstr ""

#: nova/network/ldapdns.py:322
msgid "ldap not installed"
msgstr ""

#: nova/network/ldapdns.py:333
msgid "This driver only supports type 'a' entries."
msgstr ""

#: nova/network/linux_net.py:276
#, python-format
msgid "Unknown chain: %r"
msgstr ""

#: nova/network/linux_net.py:1608
#, python-format
msgid "Failed to add bridge: %s"
msgstr ""

#: nova/network/linux_net.py:1627
#, python-format
msgid "Failed to add interface: %s"
msgstr ""

#: nova/network/manager.py:2095
msgid ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"
msgstr ""

#: nova/network/manager.py:2105
msgid "vlan must be an integer"
msgstr ""

#: nova/network/manager.py:2107
msgid "The vlan number cannot be greater than 4094"
msgstr ""

#: nova/network/manager.py:2110
msgid "The vlan number cannot be less than 1"
msgstr ""

#: nova/network/manager.py:2115
#, python-format
msgid ""
"The network range is not big enough to fit %(num_networks)s networks. "
"Network size is %(network_size)s"
msgstr ""

#: nova/network/minidns.py:75 nova/network/minidns.py:106
msgid "Invalid name"
msgstr ""

#: nova/network/minidns.py:78
msgid "This driver only supports type 'a'"
msgstr ""

#: nova/network/model.py:156
#, python-format
msgid "Invalid IP format %s"
msgstr ""

#: nova/network/neutronv2/api.py:149
msgid ""
"For \"noauth\" authentication strategy, the endpoint must be specified "
"conf.neutron.url"
msgstr ""

#: nova/network/neutronv2/api.py:166
#, python-format
msgid "Unknown auth strategy: %s"
msgstr ""

#: nova/network/neutronv2/api.py:303
#, python-format
msgid "Fixed IP %(ip)s is not a valid ip address for network %(network_id)s."
msgstr ""

#: nova/network/neutronv2/api.py:310
#, python-format
msgid "Fixed IP %s is already in use."
msgstr ""

#: nova/network/neutronv2/api.py:508
#, python-format
msgid ""
"Multiple security groups found matching '%s'. Use an ID to be more "
"specific."
msgstr ""

#: nova/network/neutronv2/api.py:568
#, python-format
msgid "empty project id for instance %s"
msgstr ""

#: nova/network/neutronv2/api.py:600 nova/network/neutronv2/api.py:1031
msgid "Multiple possible networks found, use a Network ID to be more specific."
msgstr ""

#: nova/network/neutronv2/api.py:855
#, python-format
msgid "Failed to access port %(port_id)s: %(reason)s"
msgstr ""

#: nova/network/neutronv2/api.py:1129
#, python-format
msgid "The number of defined ports: %(ports)dis over the limit: %(quota)d"
msgstr ""

#: nova/network/neutronv2/api.py:1380
#, python-format
msgid "Multiple floating IP pools matches found for name '%s'"
msgstr ""

#: nova/network/security_group/neutron_driver.py:148
#, python-format
msgid "Invalid security group name: %(name)s."
msgstr ""

#: nova/network/security_group/neutron_driver.py:189
msgid "Security group id should be uuid"
msgstr ""

#: nova/network/security_group/neutron_driver.py:430
#: nova/network/security_group/neutron_driver.py:485
#, python-format
msgid "Security group %(name)s is not found for project %(project)s"
msgstr ""

#: nova/network/security_group/neutron_driver.py:446
#: nova/network/security_group/neutron_driver.py:501
#, python-format
msgid "instance_id %s could not be found as device id on any ports"
msgstr ""

#: nova/network/security_group/neutron_driver.py:529
#, python-format
msgid ""
"Security group %(security_group_name)s not associated with the instance "
"%(instance)s"
msgstr ""

#: nova/network/security_group/security_group_base.py:92
msgid "Type and Code must be integers for ICMP protocol type"
msgstr ""

#: nova/network/security_group/security_group_base.py:95
msgid "To and From ports must be integers"
msgstr ""

#: nova/network/security_group/security_group_base.py:137
#, python-format
msgid "This rule already exists in group %s"
msgstr ""

#: nova/objects/block_device.py:209
msgid "Volume does not belong to the requested instance."
msgstr ""

#: nova/objects/fields.py:83
#, python-format
msgid "Architecture name '%s' is not valid"
msgstr ""

#: nova/objects/fields.py:196
#, python-format
msgid "Hypervisor virt type '%s' is not valid"
msgstr ""

#: nova/objects/fields.py:316
#, python-format
msgid "Virtual machine mode '%s' is not valid"
msgstr ""

#: nova/objects/fields.py:377
#, python-format
msgid "Version %(val)s is not a valid predicate in field %(attr)s"
msgstr ""

#: nova/objects/fields.py:441 nova/objects/fields.py:452
#: nova/objects/fields.py:463
#, python-format
msgid "Network \"%(val)s\" is not valid in field %(attr)s"
msgstr ""

#: nova/objects/fields.py:509
#, python-format
msgid "An object of type %(type)s is required in field %(attr)s"
msgstr ""

#: nova/objects/fields.py:553
#, python-format
msgid "A NetworkModel is required in field %s"
msgstr ""

#: nova/objects/network.py:101
#, python-format
msgid "IPv6 netmask \"%s\" must be a netmask or integral prefix"
msgstr ""

#: nova/openstack/common/cliutils.py:40
#, python-format
msgid "Missing arguments: %s"
msgstr ""

#: nova/openstack/common/cliutils.py:158
#, python-format
msgid ""
"Field labels list %(labels)s has different number of elements than fields"
" list %(fields)s"
msgstr ""

#: nova/openstack/common/imageutils.py:76
#, python-format
msgid "Invalid input value \"%s\"."
msgstr ""

#: nova/openstack/common/imageutils.py:105
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: nova/openstack/common/policy.py:110
msgid "The JSON file that defines policies."
msgstr ""

#: nova/openstack/common/policy.py:113
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: nova/openstack/common/policy.py:117
msgid ""
"Directories where policy configuration files are stored. They can be "
"relative to any directory in the search path defined by the config_dir "
"option, or absolute paths. The file defined by policy_file must exist for"
" these directories to be searched.  Missing or empty directories are "
"ignored."
msgstr ""

#: nova/openstack/common/policy.py:142
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: nova/openstack/common/policy.py:239
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: nova/pci/whitelist.py:56
#, python-format
msgid "Invalid entry: '%s'"
msgstr ""

#: nova/pci/whitelist.py:61
#, python-format
msgid "Invalid entry: '%s'; Expecting list or dict"
msgstr ""

#: nova/pci/whitelist.py:67
#, python-format
msgid "Invalid entry: '%s'; Expecting dict"
msgstr ""

#: nova/scheduler/chance.py:50
msgid "Is the appropriate service running?"
msgstr ""

#: nova/scheduler/chance.py:55
msgid "Could not find another compute"
msgstr ""

#: nova/scheduler/chance.py:73 nova/scheduler/filter_scheduler.py:88
msgid "There are not enough hosts available."
msgstr ""

#: nova/scheduler/driver.py:65
msgid "Driver must implement select_destinations"
msgstr ""

#: nova/scheduler/host_manager.py:461
#, python-format
msgid "Host filter ignoring hosts: %s"
msgstr ""

#: nova/scheduler/host_manager.py:473
#, python-format
msgid "Host filter forcing available hosts to %s"
msgstr ""

#: nova/scheduler/host_manager.py:476
#, python-format
msgid "No hosts matched due to not matching 'force_hosts' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:489
#, python-format
msgid "Host filter forcing available nodes to %s"
msgstr ""

#: nova/scheduler/host_manager.py:492
#, python-format
msgid "No nodes matched due to not matching 'force_nodes' value of '%s'"
msgstr ""

#: nova/scheduler/utils.py:171
#, python-format
msgid ""
"Exceeded max scheduling attempts %(max_attempts)d for instance "
"%(instance_uuid)s. Last exception: %(exc)s"
msgstr ""

#: nova/scheduler/utils.py:204
msgid "Invalid value for 'scheduler_max_attempts', must be >= 1"
msgstr ""

#: nova/scheduler/utils.py:295
msgid "ServerGroupAffinityFilter not configured"
msgstr ""

#: nova/scheduler/utils.py:299
msgid "ServerGroupAntiAffinityFilter not configured"
msgstr ""

#: nova/servicegroup/api.py:73
#, python-format
msgid "unknown ServiceGroup driver name: %s"
msgstr ""

#: nova/servicegroup/drivers/db.py:49
msgid "service is a mandatory argument for DB based ServiceGroup driver"
msgstr ""

#: nova/servicegroup/drivers/mc.py:41
msgid "memcached_servers not defined"
msgstr ""

#: nova/servicegroup/drivers/mc.py:54
msgid "service is a mandatory argument for Memcached based ServiceGroup driver"
msgstr ""

#: nova/virt/diagnostics.py:143
#, python-format
msgid "Invalid type for %s"
msgstr ""

#: nova/virt/diagnostics.py:147
#, python-format
msgid "Invalid type for %s entry"
msgstr ""

#: nova/virt/driver.py:781
msgid "Hypervisor driver does not support post_live_migration_at_source method"
msgstr ""

#: nova/virt/driver.py:1300
msgid "Event must be an instance of nova.virt.event.Event"
msgstr ""

#: nova/virt/event.py:34
msgid "Started"
msgstr ""

#: nova/virt/event.py:35
msgid "Stopped"
msgstr ""

#: nova/virt/event.py:36
msgid "Paused"
msgstr ""

#: nova/virt/event.py:37
msgid "Resumed"
msgstr ""

#: nova/virt/event.py:38
msgid "Suspended"
msgstr ""

#: nova/virt/event.py:110
msgid "Unknown"
msgstr ""

#: nova/virt/hardware.py:56
#, python-format
msgid "No CPUs available after parsing %r"
msgstr ""

#: nova/virt/hardware.py:88 nova/virt/hardware.py:92
#, python-format
msgid "Invalid range expression %r"
msgstr ""

#: nova/virt/hardware.py:101
#, python-format
msgid "Invalid exclusion expression %r"
msgstr ""

#: nova/virt/hardware.py:108
#, python-format
msgid "Invalid inclusion expression %r"
msgstr ""

#: nova/virt/images.py:56
#, python-format
msgid "Path does not exist %(path)s"
msgstr ""

#: nova/virt/images.py:62
#, python-format
msgid "Failed to run qemu-img info on %(path)s : %(error)s"
msgstr ""

#: nova/virt/images.py:95
msgid "'qemu-img info' parsing failed."
msgstr ""

#: nova/virt/images.py:101
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: nova/virt/images.py:131
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: nova/virt/disk/api.py:347
msgid "image already mounted"
msgstr ""

#: nova/virt/disk/api.py:676
msgid "Not implemented on Windows"
msgstr ""

#: nova/virt/disk/api.py:703
#, python-format
msgid "User %(username)s not found in password file."
msgstr ""

#: nova/virt/disk/api.py:719
#, python-format
msgid "User %(username)s not found in shadow file."
msgstr ""

#: nova/virt/disk/mount/api.py:184
#, python-format
msgid "partition search unsupported with %s"
msgstr ""

#: nova/virt/disk/mount/api.py:200
#, python-format
msgid "partition %s not found"
msgstr ""

#: nova/virt/disk/mount/api.py:201
#, python-format
msgid "Failed to map partitions: %s"
msgstr ""

#: nova/virt/disk/mount/api.py:236
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: nova/virt/disk/mount/loop.py:34
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:65
msgid "nbd unavailable: module not loaded"
msgstr ""

#: nova/virt/disk/mount/nbd.py:73
msgid "No free nbd devices"
msgstr ""

#: nova/virt/disk/mount/nbd.py:91
#, python-format
msgid "qemu-nbd error: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:104
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:76
#, python-format
msgid "libguestfs is not installed (%s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:89
#, python-format
msgid "libguestfs installed but not usable (%s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:134
#, python-format
msgid "No operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:140
#, python-format
msgid "Multi-boot operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:151
#, python-format
msgid "No mount points found in %(root)s of %(image)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:165
#, python-format
msgid ""
"Error mounting %(device)s to %(dir)s in image %(image)s with libguestfs "
"(%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:232
#, python-format
msgid "Error mounting %(image)s with libguestfs (%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:45
#, python-format
msgid "File path %s not valid"
msgstr ""

#: nova/virt/hyperv/driver.py:200
msgid "VIF plugging is not supported by the Hyper-V driver."
msgstr ""

#: nova/virt/hyperv/driver.py:205
msgid "VIF unplugging is not supported by the Hyper-V driver."
msgstr ""

#: nova/virt/hyperv/hostops.py:158
msgid "Host PowerOn is not supported by the Hyper-V driver"
msgstr ""

#: nova/virt/hyperv/hostutils.py:103
#, python-format
msgid "Host %(action)s is not supported by the Hyper-V driver"
msgstr ""

#: nova/virt/hyperv/imagecache.py:61
#, python-format
msgid ""
"Cannot resize the image to a size smaller than the VHD max. internal "
"size: %(vhd_size)s. Requested disk size: %(root_vhd_size)s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:41
msgid "Live migration is supported starting with Hyper-V Server 2012"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:44
#, python-format
msgid "Live migration is not supported on target host \"%s\""
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:47
#, python-format
msgid "Target live migration host \"%s\" is unreachable"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:50
#, python-format
msgid "Live migration failed: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:62
msgid "Live migration is not enabled on this host"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:65
msgid "Live migration networks are not configured on this host"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:71 nova/virt/hyperv/vmutils.py:183
#, python-format
msgid "VM not found: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:73 nova/virt/hyperv/vmutils.py:192
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: nova/virt/hyperv/migrationops.py:109
#, python-format
msgid ""
"Cannot resize the root disk to a smaller size. Current size: "
"%(curr_root_gb)s GB. Requested size: %(new_root_gb)s GB"
msgstr ""

#: nova/virt/hyperv/migrationops.py:159
#, python-format
msgid "Config drive is required by instance: %s, but it does not exist."
msgstr ""

#: nova/virt/hyperv/migrationops.py:220
msgid "Cannot resize a VHD to a smaller size"
msgstr ""

#: nova/virt/hyperv/migrationops.py:265
#, python-format
msgid "Cannot find boot VHD file for instance: %s"
msgstr ""

#: nova/virt/hyperv/networkutils.py:45 nova/virt/hyperv/networkutilsv2.py:42
#, python-format
msgid "vswitch \"%s\" not found"
msgstr ""

#: nova/virt/hyperv/networkutils.py:58
#, python-format
msgid "Failed to create vswitch port %(port_name)s on switch %(vswitch_path)s"
msgstr ""

#: nova/virt/hyperv/networkutilsv2.py:55
msgid "No external vswitch found"
msgstr ""

#: nova/virt/hyperv/pathutils.py:60
msgid "The SMB WMI namespace is not available on this OS version."
msgstr ""

#: nova/virt/hyperv/pathutils.py:103
#, python-format
msgid "The file copy from %(src)s to %(dest)s failed"
msgstr ""

#: nova/virt/hyperv/pathutils.py:169
#, python-format
msgid ""
"Cannot access \"%(instances_path)s\", make sure the path exists and that "
"you have the proper permissions. In particular Nova-Compute must not be "
"executed with the builtin SYSTEM account or other accounts unable to "
"authenticate on a remote host."
msgstr ""

#: nova/virt/hyperv/pathutils.py:262
#, python-format
msgid "Unable to mount SMBFS share: %(smbfs_share)s WMI exception: %(wmi_exc)s"
msgstr ""

#: nova/virt/hyperv/pathutils.py:288
#, python-format
msgid "Could not unmount share: %s"
msgstr ""

#: nova/virt/hyperv/utilsfactory.py:71
msgid ""
"The \"force_hyperv_utils_v1\" option cannot be set to \"True\" on Windows"
" Server / Hyper-V Server 2012 R2 or above as the WMI "
"\"root/virtualization\" namespace is no longer supported."
msgstr ""

#: nova/virt/hyperv/vhdutils.py:66 nova/virt/hyperv/vhdutilsv2.py:65
#, python-format
msgid "Unsupported disk format: %s"
msgstr ""

#: nova/virt/hyperv/vhdutils.py:162
#, python-format
msgid "Unable to obtain block size from VHD %(vhd_path)s"
msgstr ""

#: nova/virt/hyperv/vhdutils.py:209
msgid "Unsupported virtual disk format"
msgstr ""

#: nova/virt/hyperv/vhdutilsv2.py:107
#, python-format
msgid ""
"Failed to reconnect image %(child_vhd_path)s to parent "
"%(parent_vhd_path)s. The child image has no parent path property."
msgstr ""

#: nova/virt/hyperv/vhdutilsv2.py:173
#, python-format
msgid "Unable to obtain internal size from VHDX: %(vhd_path)s. Exception: %(ex)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:145
#, python-format
msgid "VIF driver not found for network_api_class: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:230
#, python-format
msgid ""
"Cannot resize a VHD to a smaller size, the original size is %(old_size)s,"
" the newer size is %(new_size)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:357
#, python-format
msgid "Requested VM Generation %s is not supported on this OS."
msgstr ""

#: nova/virt/hyperv/vmops.py:368
#, python-format
msgid "Requested VM Generation %s, but provided VHD instead of VHDX."
msgstr ""

#: nova/virt/hyperv/vmops.py:377 nova/virt/vmwareapi/vmops.py:759
#, python-format
msgid "Invalid config_drive_format \"%s\""
msgstr ""

#: nova/virt/hyperv/vmops.py:666
#, python-format
msgid "Could not get instance console log. Error: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:154
#, python-format
msgid "Cannot get VM summary data for: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:252
msgid ""
"The Windows account running nova-compute on this Hyper-V host doesn't "
"have the required permissions to create or operate the virtual machine."
msgstr ""

#: nova/virt/hyperv/vmutils.py:583
#, python-format
msgid "Operation failed with return value: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:599
#, python-format
msgid ""
"WMI job failed with status %(job_state)d. Error details: %(err_sum_desc)s"
" - %(err_desc)s - Error code: %(err_code)d"
msgstr ""

#: nova/virt/hyperv/vmutils.py:610
#, python-format
msgid "WMI job failed with status %(job_state)d. Error details: %(error)s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:616
#, python-format
msgid "WMI job failed with status %d. No error description available"
msgstr ""

#: nova/virt/hyperv/vmutils.py:742
msgid "Exceeded the maximum number of slots"
msgstr ""

#: nova/virt/hyperv/vmutils.py:745
msgid "Metrics collection is not supported on this version of Hyper-V"
msgstr ""

#: nova/virt/hyperv/volumeops.py:177
#, python-format
msgid ""
"Cannot log in target %(target_iqn)s. Unsupported iSCSI authentication "
"method: %(auth_method)s."
msgstr ""

#: nova/virt/hyperv/volumeops.py:302
#, python-format
msgid "Unable to find a mounted disk for target_iqn: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:316
#, python-format
msgid ""
"Unable to find a mounted disk for target_iqn: %s. Please ensure that the "
"host's SAN policy is set to \"OfflineAll\" or \"OfflineShared\""
msgstr ""

#: nova/virt/hyperv/volumeops.py:386
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:51
#, python-format
msgid "An error has occurred when calling the iscsi initiator: %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:108 nova/virt/hyperv/volumeutilsv2.py:110
#, python-format
msgid "Failed to login target %s"
msgstr ""

#: nova/virt/ironic/client_wrapper.py:88
msgid "Unable to authenticate Ironic client."
msgstr ""

#: nova/virt/ironic/client_wrapper.py:141
#, python-format
msgid ""
"Error contacting Ironic server for '%(method)s'. Attempt %(attempt)d of "
"%(total)d"
msgstr ""

#: nova/virt/ironic/driver.py:360
#, python-format
msgid ""
"Failed to add deploy parameters on node %(node)s when provisioning the "
"instance %(instance)s"
msgstr ""

#: nova/virt/ironic/driver.py:388
#, python-format
msgid "Fail to clean up node %s parameters"
msgstr ""

#: nova/virt/ironic/driver.py:400
#, python-format
msgid "Instance %s provisioning was aborted"
msgstr ""

#: nova/virt/ironic/driver.py:421
#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr ""

#: nova/virt/ironic/driver.py:712
#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr ""

#: nova/virt/ironic/driver.py:733
#, python-format
msgid ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"
msgstr ""

#: nova/virt/ironic/driver.py:837
#, python-format
msgid ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."
msgstr ""

#: nova/virt/ironic/driver.py:1040
#, python-format
msgid ""
"Ironic node: %(id)s virtual to physical interface count  missmatch (Vif "
"count: %(vif_count)d, Pif count: %(pif_count)d)"
msgstr ""

#: nova/virt/ironic/driver.py:1160
#, python-format
msgid "Failed to request Ironic to rebuild instance %(inst)s: %(reason)s"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:146
#, python-format
msgid "Unable to determine disk prefix for %s"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:194
#, python-format
msgid "No free disk device names for prefix '%s'"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:309
#, python-format
msgid "Unable to determine disk bus for '%s'"
msgstr ""

#: nova/virt/libvirt/config.py:75
#, python-format
msgid "Root element name should be '%(name)s' not '%(tag)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:520
#, python-format
msgid ""
"Unexpected sysinfo_serial setting '%(actual)s'. Permitted values are "
"%(expect)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:607
#, python-format
msgid "Nova requires libvirt version %s or greater."
msgstr ""

#: nova/virt/libvirt/driver.py:613
#, python-format
msgid "Running Nova with parallels virt_type requires libvirt version %s"
msgstr ""

#: nova/virt/libvirt/driver.py:633
#, python-format
msgid ""
"Running Nova with qemu/kvm virt_type on s390/s390x requires libvirt "
"version %(libvirt_ver)s and qemu version %(qemu_ver)s, or greater"
msgstr ""

#: nova/virt/libvirt/driver.py:756
msgid "operation time out"
msgstr ""

#: nova/virt/libvirt/driver.py:1111
#, python-format
msgid ""
"Volume sets block size, but the current libvirt hypervisor '%s' does not "
"support custom block size"
msgstr ""

#: nova/virt/libvirt/driver.py:1118
#, python-format
msgid "Volume sets block size, but libvirt '%s' or later is required."
msgstr ""

#: nova/virt/libvirt/driver.py:1208
msgid "Swap only supports host devices"
msgstr ""

#: nova/virt/libvirt/driver.py:1507
#, python-format
msgid ""
"Error from libvirt while set password for username \"%(user)s\": [Error "
"Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1538
#, python-format
msgid ""
"Error from libvirt while quiescing %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1693
msgid "Found no disk to snapshot."
msgstr ""

#: nova/virt/libvirt/driver.py:1794
#, python-format
msgid "Unknown type: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1799
msgid "snapshot_id required in create_info"
msgstr ""

#: nova/virt/libvirt/driver.py:1857
#, python-format
msgid "Libvirt '%s' or later is required for online deletion of volume snapshots."
msgstr ""

#: nova/virt/libvirt/driver.py:1865
#, python-format
msgid "Unknown delete_info type %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1901
#, python-format
msgid "Disk with id: %s not found attached to instance."
msgstr ""

#: nova/virt/libvirt/driver.py:1910
msgid "filename cannot be None"
msgstr ""

#: nova/virt/libvirt/driver.py:1939
#, python-format
msgid "no match found for %s"
msgstr ""

#: nova/virt/libvirt/driver.py:2010
#, python-format
msgid ""
"Relative blockcommit support was not detected. Libvirt '%s' or later is "
"required for online deletion of file/network storage-backed volume "
"snapshots."
msgstr ""

#: nova/virt/libvirt/driver.py:2325
#, python-format
msgid ""
"Error from libvirt while injecting an NMI to %(instance_uuid)s: [Error "
"Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:2564 nova/virt/xenapi/vmops.py:1770
msgid "Guest does not have a console available"
msgstr ""

#: nova/virt/libvirt/driver.py:2923
#, python-format
msgid "%s format is not supported"
msgstr ""

#: nova/virt/libvirt/driver.py:3044
#, python-format
msgid "Detaching PCI devices with libvirt < %(ver)s is not permitted"
msgstr ""

#: nova/virt/libvirt/driver.py:3126
#, python-format
msgid "Detaching SR-IOV ports with libvirt < %(ver)s is not permitted"
msgstr ""

#: nova/virt/libvirt/driver.py:3207
#, python-format
msgid ""
"Config requested an explicit CPU model, but the current libvirt "
"hypervisor '%s' does not support selecting CPU models"
msgstr ""

#: nova/virt/libvirt/driver.py:3213
msgid "Config requested a custom CPU model, but no model name was provided"
msgstr ""

#: nova/virt/libvirt/driver.py:3217
msgid "A CPU model name should not be set when a host CPU model is requested"
msgstr ""

#: nova/virt/libvirt/driver.py:3257
#, python-format
msgid ""
"Volume sets discard option, but libvirt %(libvirt)s or later is required,"
" qemu %(qemu)s or later is required."
msgstr ""

#: nova/virt/libvirt/driver.py:3567
#, python-format
msgid "Invalid libvirt version %(version)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4358
#, python-format
msgid ""
"Error from libvirt while getting domain info for %(instance_name)s: "
"[Error Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4643
#, python-format
msgid ""
"Invalid vcpu_pin_set config, one or more of the specified cpuset is not "
"online. Online cpuset(s): %(online)s, requested cpuset(s): %(req)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4650
msgid "Invalid vcpu_pin_set config, out of hypervisor cpu range."
msgstr ""

#: nova/virt/libvirt/driver.py:5190
msgid "Block migration can not be used with shared storage."
msgstr ""

#: nova/virt/libvirt/driver.py:5201
msgid ""
"Live migration can not be used without shared storage except a booted "
"from volume VM which does not have a local disk."
msgstr ""

#: nova/virt/libvirt/driver.py:5286
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s: Disk of instance is too "
"large(available on destination host:%(available)s < need:%(necessary)s)"
msgstr ""

#: nova/virt/libvirt/driver.py:5332
#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5402
#, python-format
msgid "The firewall filter for %s does not exist"
msgstr ""

#: nova/virt/libvirt/driver.py:5521
msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag "
"or your destination node does not support retrieving listen addresses.  "
"In order for live migration to work properly, you must configure the "
"graphics (VNC and/or SPICE) listen addresses to be either the catch-all "
"address (0.0.0.0 or ::) or the local address (127.0.0.1 or ::1)."
msgstr ""

#: nova/virt/libvirt/driver.py:6163
#, python-format
msgid "Cannot block migrate instance %s with mapped volumes"
msgstr ""

#: nova/virt/libvirt/driver.py:6583
msgid "Unable to resize disk down."
msgstr ""

#: nova/virt/libvirt/driver.py:6591
msgid "Migration is not supported for LVM backed instances"
msgstr ""

#: nova/virt/libvirt/driver.py:6609
#, python-format
msgid "not able to execute ssh command: %s"
msgstr ""

#: nova/virt/libvirt/guest.py:347
msgid "libvirt error while requesting blockjob info."
msgstr ""

#: nova/virt/libvirt/host.py:300
#, python-format
msgid "Can not handle authentication request for %d credentials"
msgstr ""

#: nova/virt/libvirt/host.py:380
#, python-format
msgid "Connection to libvirt lost: %s"
msgstr ""

#: nova/virt/libvirt/host.py:634
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_id)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:656
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/host.py:836 nova/virt/libvirt/host.py:865
#, python-format
msgid "Invalid usage_type: %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:105
msgid ""
"Incompatible settings: ephemeral storage encryption is supported only for"
" LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:315
#, python-format
msgid "Could not load line %(line)s, got error %(error)s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:330
msgid "Attempted overwrite of an existing value."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:378
msgid "clone() is not implemented"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:590
msgid "You should specify images_volume_group flag to use LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:652
msgid "Instance disk to be encrypted but no context provided"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:702
msgid "You should specify images_rbd_pool flag to use rbd images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:802
msgid "Image is not raw format"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:810
msgid "No image locations are accessible"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:872
#, python-format
msgid ""
"PCS doesn't support images in %s format. You should either set "
"force_raw_images=True in config or upload an image in ploop or raw "
"format."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:911
#, python-format
msgid "Unknown image_type=%s"
msgstr ""

#: nova/virt/libvirt/utils.py:347
msgid "Can't retrieve root device path from instance libvirt configuration"
msgstr ""

#: nova/virt/libvirt/vif.py:453 nova/virt/libvirt/vif.py:722
#: nova/virt/libvirt/vif.py:924
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr ""

#: nova/virt/libvirt/vif.py:459 nova/virt/libvirt/vif.py:930
#, python-format
msgid "Unexpected vif_type=%s"
msgstr ""

#: nova/virt/libvirt/vif.py:728
#, python-format
msgid "Plug vif failed because of unexpected vif_type=%s"
msgstr ""

#: nova/virt/libvirt/storage/lvm.py:65
#, python-format
msgid ""
"Insufficient Space on Volume Group %(vg)s. Only %(free_space)db "
"available, but %(size)db required by volume %(lv)s."
msgstr ""

#: nova/virt/libvirt/storage/lvm.py:113
#, python-format
msgid "vg %s must be LVM volume group"
msgstr ""

#: nova/virt/libvirt/storage/lvm.py:156
#, python-format
msgid "Path %s must be LVM logical volume"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:113
msgid "rbd python libraries not found"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:165
msgid "Not stored in rbd"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:169
msgid "Blank components"
msgstr ""

#: nova/virt/libvirt/storage/rbd_utils.py:172
msgid "Not an rbd snapshot"
msgstr ""

#: nova/virt/libvirt/volume/net.py:86
msgid "Invalid volume source data"
msgstr ""

#: nova/virt/libvirt/volume/net.py:90
msgid "Invalid target_lun"
msgstr ""

#: nova/virt/libvirt/volume/quobyte.py:88
#, python-format
msgid "The mount %(mount_path)s is not a valid Quobyte volume. Error: %(exc)s"
msgstr ""

#: nova/virt/libvirt/volume/scality.py:100
msgid "Value required for 'scality_sofs_config'"
msgstr ""

#: nova/virt/libvirt/volume/scality.py:111
#, python-format
msgid "Cannot access 'scality_sofs_config': %s"
msgstr ""

#: nova/virt/libvirt/volume/scality.py:117
msgid "Cannot execute /sbin/mount.sofs"
msgstr ""

#: nova/virt/libvirt/volume/scality.py:132
msgid "Cannot mount Scality SOFS, check syslog for errors"
msgstr ""

#: nova/virt/vmwareapi/driver.py:151
msgid ""
"Must specify host_ip, host_username and host_password to use "
"vmwareapi.VMwareVCDriver"
msgstr ""

#: nova/virt/vmwareapi/driver.py:160
#, python-format
msgid "Invalid Regular Expression %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:186
#, python-format
msgid "All clusters specified %s were not found in the vCenter"
msgstr ""

#: nova/virt/vmwareapi/driver.py:455
#, python-format
msgid "The resource %s does not exist"
msgstr ""

#: nova/virt/vmwareapi/driver.py:694
msgid ""
"Multiple hosts may be managed by the VMWare vCenter driver; therefore we "
"do not return uptime for just one host."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:141
#, python-format
msgid "Storage policy %s did not match any datastores"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:145
#, python-format
msgid "Datastore regex %s did not match any datastores"
msgstr ""

#: nova/virt/vmwareapi/error_util.py:25
msgid "No root disk defined."
msgstr ""

#: nova/virt/vmwareapi/error_util.py:29
msgid "Default PBM policy is required if PBM is enabled."
msgstr ""

#: nova/virt/vmwareapi/error_util.py:33
msgid "The default PBM policy doesn't exist on the backend."
msgstr ""

#: nova/virt/vmwareapi/images.py:459
msgid "Extracting vmdk from OVA failed."
msgstr ""

#: nova/virt/vmwareapi/io_util.py:123
#, python-format
msgid "Glance image %s is in killed state"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:131
#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr ""

#: nova/virt/vmwareapi/network_util.py:159
msgid ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:87
#, python-format
msgid "Share level '%s' cannot have share configured"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:94
#, python-format
msgid "Share '%s' is not supported"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:402
#, python-format
msgid "%s is not supported."
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:679 nova/virt/vmwareapi/volumeops.py:352
#: nova/virt/vmwareapi/volumeops.py:528
msgid "Unable to find iSCSI Target"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1174
msgid "No host available on cluster"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1550
#, python-format
msgid "Rescue device does not exist for instance %s"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:497
msgid "Image disk size greater than requested disk size"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:539
#, python-format
msgid "disk type '%s' not supported"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:954
msgid "instance is not powered on"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1050
msgid "pause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1054
msgid "unpause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1072
msgid "instance is powered off and cannot be suspended."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1092
msgid "instance is not in a suspended state"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1264
msgid "Unable to shrink disk."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1703
#, python-format
msgid "No device with interface-id %s exists on VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1713
#, python-format
msgid "No device with MAC address %s exists on the VM"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:325 nova/virt/vmwareapi/volumeops.py:506
#, python-format
msgid "%s does not support disk hotplug."
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:485 nova/virt/vmwareapi/volumeops.py:536
msgid "Unable to find volume"
msgstr ""

#: nova/virt/xenapi/agent.py:463
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: nova/virt/xenapi/driver.py:115
msgid ""
"Must specify connection_url, connection_username (optionally), and "
"connection_password to use compute_driver=xenapi.XenAPIDriver"
msgstr ""

#: nova/virt/xenapi/driver.py:639
msgid "Host startup on XenServer is not supported."
msgstr ""

#: nova/virt/xenapi/fake.py:850
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: nova/virt/xenapi/fake.py:958
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""

#: nova/virt/xenapi/host.py:89
#, python-format
msgid "Aggregate for host %(host)s count not be found."
msgstr ""

#: nova/virt/xenapi/host.py:187
msgid "Failed to parse information about a pci device for passthrough"
msgstr ""

#: nova/virt/xenapi/network_utils.py:31
#, python-format
msgid "Found non-unique network for name_label %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:49
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:52
#, python-format
msgid "Found no network for bridge %s"
msgstr ""

#: nova/virt/xenapi/pool.py:74 nova/virt/xenapi/pool.py:122
msgid "setup in progress"
msgstr ""

#: nova/virt/xenapi/pool.py:75 nova/virt/xenapi/pool.py:123
msgid "aggregate deleted"
msgstr ""

#: nova/virt/xenapi/pool.py:76
msgid "aggregate in error"
msgstr ""

#: nova/virt/xenapi/pool.py:121
msgid "no hosts to remove"
msgstr ""

#: nova/virt/xenapi/pool.py:145
#, python-format
msgid "Unable to eject %s from the pool; pool not empty"
msgstr ""

#: nova/virt/xenapi/pool.py:160
#, python-format
msgid "Unable to eject %s from the pool; No master found"
msgstr ""

#: nova/virt/xenapi/pool.py:180
#, python-format
msgid "Unable to join %s in the pool"
msgstr ""

#: nova/virt/xenapi/vif.py:100
#, python-format
msgid "Found no PIF for device %s"
msgstr ""

#: nova/virt/xenapi/vif.py:119
#, python-format
msgid ""
"PIF %(pif_uuid)s for network %(bridge)s has VLAN id %(pif_vlan)d. "
"Expected %(vlan_num)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:211
#, python-format
msgid ""
"Device id %(id)s specified is not supported by hypervisor version "
"%(version)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:407
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:410
#, python-format
msgid "Reached maximum number of retries trying to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:422
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:475
#, python-format
msgid "Unable to destroy VDI %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:637
#, python-format
msgid "No primary VDI found for %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:770
#, python-format
msgid ""
"Only file-based SRs (ext/NFS) are supported by this feature.  SR %(uuid)s"
" is of type %(type)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:904
#, python-format
msgid ""
"VDI %(vdi_ref)s is %(virtual_size)d bytes which is larger than flavor "
"size of %(new_disk_size)d bytes."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:915 nova/virt/xenapi/vmops.py:1208
msgid "Can't resize a disk to 0 GB."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:967
msgid "Disk must have only one partition."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:972
#, python-format
msgid "Disk contains a filesystem we are unable to resize: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:977
msgid "The only partition should be partition 1."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1546
#, python-format
msgid ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d "
"bytes"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1917
msgid "Cannot find SR of content-type ISO"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2123
#, python-format
msgid "VHD coalesce attempts exceeded (%d), giving up..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2158
#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2333
msgid ""
"Shrinking the filesystem down with resize2fs has failed, please check if "
"you have enough free space on your disk."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2498
msgid "This domU must be running on the host specified by connection_url"
msgstr ""

#: nova/virt/xenapi/vmops.py:180
msgid "Error: Agent is disabled"
msgstr ""

#: nova/virt/xenapi/vmops.py:605
msgid "Failed to spawn, rolling back"
msgstr ""

#: nova/virt/xenapi/vmops.py:616
msgid "Unable to find root VBD/VDI for VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:932
msgid "Unable to terminate instance."
msgstr ""

#: nova/virt/xenapi/vmops.py:1184
msgid "Can't resize down ephemeral disks."
msgstr ""

#: nova/virt/xenapi/vmops.py:1462
msgid "instance has a kernel or ramdisk but not both"
msgstr ""

#: nova/virt/xenapi/vmops.py:1618
#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:2061
#, python-format
msgid "Destination host:%s must be in the same aggregate as the source server"
msgstr ""

#: nova/virt/xenapi/vmops.py:2082
msgid "No suitable network for migrate"
msgstr ""

#: nova/virt/xenapi/vmops.py:2088
#, python-format
msgid "PIF %s does not contain IP address"
msgstr ""

#: nova/virt/xenapi/vmops.py:2101
msgid "Migrate Receive failed"
msgstr ""

#: nova/virt/xenapi/vmops.py:2175
msgid "XAPI supporting relax-xsm-sr-check=true required"
msgstr ""

#: nova/virt/xenapi/vmops.py:2186
#, python-format
msgid "assert_can_migrate failed because: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:2247
msgid "Migrate Send failed"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:86 nova/virt/xenapi/volume_utils.py:262
#, python-format
msgid "Unable to obtain target information %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:165
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:169
#, python-format
msgid ""
"VDI not found on SR %(sr)s (vdi_uuid %(vdi_uuid)s, target_lun "
"%(target_lun)s)"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:180
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:202
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:300
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:311
#, python-format
msgid "Unable to find SR from VDI %s"
msgstr ""

#: nova/virt/xenapi/client/session.py:89
#, python-format
msgid "%(vendor)s %(product)s %(version)s"
msgstr ""

#: nova/virt/xenapi/client/session.py:97
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: nova/virt/xenapi/client/session.py:117
#, python-format
msgid "Plugin version mismatch (Expected %(exp)s, got %(got)s)"
msgstr ""

#: nova/virt/xenapi/image/bittorrent.py:81
msgid ""
"Cannot create default bittorrent URL without xenserver.torrent_base_url "
"configuration option set."
msgstr ""

#: nova/volume/cinder.py:302
#, python-format
msgid "volume '%(vol)s' status must be 'in-use'. Currently in '%(status)s' status"
msgstr ""

#: nova/volume/cinder.py:310
#, python-format
msgid "volume '%(vol)s' status must be 'available'. Currently in '%(status)s'"
msgstr ""

#: nova/volume/cinder.py:315
#, python-format
msgid "volume %s already attached"
msgstr ""

#: nova/volume/cinder.py:326
#, python-format
msgid ""
"Instance %(instance)s and volume %(vol)s are not in the same "
"availability_zone. Instance is in %(ins_zone)s. Volume is in %(vol_zone)s"
msgstr ""

#: nova/volume/cinder.py:338
#, python-format
msgid "volume %s already detached"
msgstr ""

