# Translations template for nova.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the nova project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: nova 2015.1.dev1451\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-12-17 06:15+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: nova/block_device.py:102
msgid "Some fields are invalid."
msgstr ""

#: nova/block_device.py:112
msgid "Some required fields are missing"
msgstr ""

#: nova/block_device.py:128
msgid "Boot index is invalid."
msgstr ""

#: nova/block_device.py:171
msgid "Unrecognized legacy format."
msgstr ""

#: nova/block_device.py:188
msgid "Invalid source_type field."
msgstr ""

#: nova/block_device.py:191
msgid "Invalid device UUID."
msgstr ""

#: nova/block_device.py:195
msgid "Missing device UUID."
msgstr ""

#: nova/block_device.py:374
msgid "Device name empty or too long."
msgstr ""

#: nova/block_device.py:378
msgid "Device name contains spaces."
msgstr ""

#: nova/block_device.py:388
msgid "Invalid volume_size."
msgstr ""

#: nova/context.py:143
#, python-format
msgid "read_deleted can only be one of 'no', 'yes' or 'only', not %r"
msgstr ""

#: nova/crypto.py:53
msgid "Filename of root CA"
msgstr ""

#: nova/crypto.py:56
msgid "Filename of private key"
msgstr ""

#: nova/crypto.py:59
msgid "Filename of root Certificate Revocation List"
msgstr ""

#: nova/crypto.py:62
msgid "Where we keep our keys"
msgstr ""

#: nova/crypto.py:65
msgid "Where we keep our root CA"
msgstr ""

#: nova/crypto.py:68
msgid "Should we use a CA for each project?"
msgstr ""

#: nova/crypto.py:72
#, python-format
msgid "Subject for certificate for users, %s for project, user, timestamp"
msgstr ""

#: nova/crypto.py:77
#, python-format
msgid "Subject for certificate for projects, %s for project, timestamp"
msgstr ""

#: nova/crypto.py:142
msgid "failed to generate fingerprint"
msgstr ""

#: nova/crypto.py:211
msgid "Unable to find the key"
msgstr ""

#: nova/exception.py:102
msgid "An unknown exception occurred."
msgstr ""

#: nova/exception.py:143
#, python-format
msgid "Failed to encrypt text: %(reason)s"
msgstr ""

#: nova/exception.py:147
#, python-format
msgid "Failed to decrypt text: %(reason)s"
msgstr ""

#: nova/exception.py:151
#, python-format
msgid "Failed to revoke certificate for %(project_id)s"
msgstr ""

#: nova/exception.py:155
msgid "Virtual Interface creation failed"
msgstr ""

#: nova/exception.py:159
msgid "Creation of virtual interface with unique mac address failed"
msgstr ""

#: nova/exception.py:164
msgid "Virtual interface plugin failed"
msgstr ""

#: nova/exception.py:168
#, python-format
msgid "Connection to glance host %(host)s:%(port)s failed: %(reason)s"
msgstr ""

#: nova/exception.py:173
#, python-format
msgid "Connection to cinder host failed: %(reason)s"
msgstr ""

#: nova/exception.py:178
msgid "Not authorized."
msgstr ""

#: nova/exception.py:183
msgid "User does not have admin privileges"
msgstr ""

#: nova/exception.py:187
#, python-format
msgid "Policy doesn't allow %(action)s to be performed."
msgstr ""

#: nova/exception.py:194
#, python-format
msgid "Image %(image_id)s is not active."
msgstr ""

#: nova/exception.py:198
#, python-format
msgid "Not authorized for image %(image_id)s."
msgstr ""

#: nova/exception.py:202 nova/exception.py:350
msgid "Unacceptable parameters."
msgstr ""

#: nova/exception.py:207
msgid "Block Device Mapping is Invalid."
msgstr ""

#: nova/exception.py:211
#, python-format
msgid "Block Device Mapping is Invalid: failed to get snapshot %(id)s."
msgstr ""

#: nova/exception.py:216
#, python-format
msgid "Block Device Mapping is Invalid: failed to get volume %(id)s."
msgstr ""

#: nova/exception.py:221
#, python-format
msgid "Block Device Mapping is Invalid: failed to get image %(id)s."
msgstr ""

#: nova/exception.py:226
msgid ""
"Block Device Mapping is Invalid: Boot sequence for the instance and "
"image/block device mapping combination is not valid."
msgstr ""

#: nova/exception.py:233
msgid ""
"Block Device Mapping is Invalid: You specified more local devices than "
"the limit allows"
msgstr ""

#: nova/exception.py:239
msgid "Ephemeral disks requested are larger than the instance type allows."
msgstr ""

#: nova/exception.py:244
msgid "Swap drive requested is larger than instance type allows."
msgstr ""

#: nova/exception.py:248
#, python-format
msgid "Block Device Mapping is Invalid: %(details)s"
msgstr ""

#: nova/exception.py:253
msgid "Block Device Mapping cannot be converted to legacy format. "
msgstr ""

#: nova/exception.py:258
#, python-format
msgid "Block Device %(id)s is not bootable."
msgstr ""

#: nova/exception.py:262
#, python-format
msgid "Attribute not supported: %(attr)s"
msgstr ""

#: nova/exception.py:271
#, python-format
msgid "Volume %(volume_id)s is not attached to anything"
msgstr ""

#: nova/exception.py:275
#, python-format
msgid ""
"Volume %(volume_id)s did not finish being created even after we waited "
"%(seconds)s seconds or %(attempts)s attempts."
msgstr ""

#: nova/exception.py:282
#, python-format
msgid "Keypair data is invalid: %(reason)s"
msgstr ""

#: nova/exception.py:286
msgid "The request is invalid."
msgstr ""

#: nova/exception.py:290
#, python-format
msgid "Invalid input received: %(reason)s"
msgstr ""

#: nova/exception.py:295
#, python-format
msgid "Invalid volume: %(reason)s"
msgstr ""

#: nova/exception.py:299
#, python-format
msgid "Invalid volume access mode: %(access_mode)s"
msgstr ""

#: nova/exception.py:303
#, python-format
msgid "Invalid metadata: %(reason)s"
msgstr ""

#: nova/exception.py:307
#, python-format
msgid "Invalid metadata size: %(reason)s"
msgstr ""

#: nova/exception.py:312
#, python-format
msgid "Invalid port range %(from_port)s:%(to_port)s. %(msg)s"
msgstr ""

#: nova/exception.py:316
#, python-format
msgid "Invalid IP protocol %(protocol)s."
msgstr ""

#: nova/exception.py:320
#, python-format
msgid "Invalid content type %(content_type)s."
msgstr ""

#: nova/exception.py:324
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: nova/exception.py:329
#, python-format
msgid ""
"API Version String %(version)s is of invalid format. Must be of format "
"MajorNum.MinorNum."
msgstr ""

#: nova/exception.py:334
#, python-format
msgid "API version %(version)s is not supported on this method."
msgstr ""

#: nova/exception.py:338
#, python-format
msgid ""
"Version %(req_ver)s is not supported by the API. Minimum is %(min_ver)s "
"and maximum is %(max_ver)s."
msgstr ""

#: nova/exception.py:346
#, python-format
msgid "%(err)s"
msgstr ""

#: nova/exception.py:355
#, python-format
msgid "Cannot add host to aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:360
#, python-format
msgid "Cannot remove host from aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:365
#, python-format
msgid "Cannot update aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:370
#, python-format
msgid "Cannot update metadata of aggregate %(aggregate_id)s. Reason: %(reason)s."
msgstr ""

#: nova/exception.py:375
#, python-format
msgid "Group not valid. Reason: %(reason)s"
msgstr ""

#: nova/exception.py:379
msgid "Sort key supplied was not valid."
msgstr ""

#: nova/exception.py:383
#, python-format
msgid "Invalid datetime string: %(reason)s"
msgstr ""

#: nova/exception.py:387
#, python-format
msgid ""
"Instance %(instance_uuid)s in %(attr)s %(state)s. Cannot %(method)s while"
" the instance is in this state."
msgstr ""

#: nova/exception.py:392
#, python-format
msgid "Instance %(instance_id)s is not running."
msgstr ""

#: nova/exception.py:396
#, python-format
msgid "Instance %(instance_id)s is not in rescue mode"
msgstr ""

#: nova/exception.py:400
#, python-format
msgid "Instance %(instance_id)s cannot be rescued: %(reason)s"
msgstr ""

#: nova/exception.py:404
#, python-format
msgid "Instance %(instance_id)s is not ready"
msgstr ""

#: nova/exception.py:408
#, python-format
msgid "Failed to suspend instance: %(reason)s"
msgstr ""

#: nova/exception.py:412
#, python-format
msgid "Failed to resume instance: %(reason)s"
msgstr ""

#: nova/exception.py:416
#, python-format
msgid "Failed to power on instance: %(reason)s"
msgstr ""

#: nova/exception.py:420
#, python-format
msgid "Failed to power off instance: %(reason)s"
msgstr ""

#: nova/exception.py:424
#, python-format
msgid "Failed to reboot instance: %(reason)s"
msgstr ""

#: nova/exception.py:428
#, python-format
msgid "Failed to terminate instance: %(reason)s"
msgstr ""

#: nova/exception.py:432
#, python-format
msgid "Failed to deploy instance: %(reason)s"
msgstr ""

#: nova/exception.py:436 nova/exception.py:440
#, python-format
msgid "Failed to launch instances: %(reason)s"
msgstr ""

#: nova/exception.py:444
msgid "Service is unavailable at this time."
msgstr ""

#: nova/exception.py:448
#, python-format
msgid "Insufficient compute resources: %(reason)s."
msgstr ""

#: nova/exception.py:452
#, python-format
msgid "Connection to the hypervisor is broken on host: %(host)s"
msgstr ""

#: nova/exception.py:456
#, python-format
msgid "Compute service of %(host)s is unavailable at this time."
msgstr ""

#: nova/exception.py:460
#, python-format
msgid "Compute service of %(host)s is still in use."
msgstr ""

#: nova/exception.py:464
#, python-format
msgid "Unable to migrate instance (%(instance_id)s) to current host (%(host)s)."
msgstr ""

#: nova/exception.py:469
msgid "The supplied hypervisor type of is invalid."
msgstr ""

#: nova/exception.py:473
msgid "The instance requires a newer hypervisor version than has been provided."
msgstr ""

#: nova/exception.py:478
#, python-format
msgid ""
"The supplied disk path (%(path)s) already exists, it is expected not to "
"exist."
msgstr ""

#: nova/exception.py:483
#, python-format
msgid "The supplied device path (%(path)s) is invalid."
msgstr ""

#: nova/exception.py:487
#, python-format
msgid "The supplied device path (%(path)s) is in use."
msgstr ""

#: nova/exception.py:492
#, python-format
msgid "The supplied device (%(device)s) is busy."
msgstr ""

#: nova/exception.py:496
#, python-format
msgid "Unacceptable CPU info: %(reason)s"
msgstr ""

#: nova/exception.py:500
#, python-format
msgid "%(address)s is not a valid IP v4/6 address."
msgstr ""

#: nova/exception.py:504
#, python-format
msgid ""
"VLAN tag is not appropriate for the port group %(bridge)s. Expected VLAN "
"tag is %(tag)s, but the one associated with the port group is %(pgroup)s."
msgstr ""

#: nova/exception.py:510
#, python-format
msgid ""
"vSwitch which contains the port group %(bridge)s is not associated with "
"the desired physical adapter. Expected vSwitch is %(expected)s, but the "
"one associated is %(actual)s."
msgstr ""

#: nova/exception.py:517
#, python-format
msgid "Disk format %(disk_format)s is not acceptable"
msgstr ""

#: nova/exception.py:521
#, python-format
msgid "Disk info file is invalid: %(reason)s"
msgstr ""

#: nova/exception.py:525
#, python-format
msgid "Failed to read or write disk info file: %(reason)s"
msgstr ""

#: nova/exception.py:529
#, python-format
msgid "Image %(image_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:533
#, python-format
msgid "Instance %(instance_id)s is unacceptable: %(reason)s"
msgstr ""

#: nova/exception.py:537
#, python-format
msgid "Ec2 id %(ec2_id)s is unacceptable."
msgstr ""

#: nova/exception.py:541
#, python-format
msgid "Expected a uuid but received %(uuid)s."
msgstr ""

#: nova/exception.py:545
#, python-format
msgid "Invalid ID received %(id)s."
msgstr ""

#: nova/exception.py:549
msgid "Constraint not met."
msgstr ""

#: nova/exception.py:554
msgid "Resource could not be found."
msgstr ""

#: nova/exception.py:559
#, python-format
msgid "No agent-build associated with id %(id)s."
msgstr ""

#: nova/exception.py:563
#, python-format
msgid ""
"Agent-build with hypervisor %(hypervisor)s os %(os)s architecture "
"%(architecture)s exists."
msgstr ""

#: nova/exception.py:569
#, python-format
msgid "Volume %(volume_id)s could not be found."
msgstr ""

#: nova/exception.py:573
#, python-format
msgid "No volume Block Device Mapping with id %(volume_id)s."
msgstr ""

#: nova/exception.py:577
#, python-format
msgid "No volume Block Device Mapping at path: %(path)s"
msgstr ""

#: nova/exception.py:582
#, python-format
msgid "Snapshot %(snapshot_id)s could not be found."
msgstr ""

#: nova/exception.py:586
#, python-format
msgid "No disk at %(location)s"
msgstr ""

#: nova/exception.py:590
#, python-format
msgid "Could not find a handler for %(driver_type)s volume."
msgstr ""

#: nova/exception.py:594
#, python-format
msgid "Invalid image href %(image_href)s."
msgstr ""

#: nova/exception.py:598
#, python-format
msgid "Requested image %(image)s has automatic disk resize disabled."
msgstr ""

#: nova/exception.py:603
#, python-format
msgid "Image %(image_id)s could not be found."
msgstr ""

#: nova/exception.py:607
msgid "The current driver does not support preserving ephemeral partitions."
msgstr ""

#: nova/exception.py:613
#, python-format
msgid ""
"Image %(image_id)s could not be found. The nova EC2 API assigns image ids"
" dynamically when they are listed for the first time. Have you listed "
"image ids since adding this image?"
msgstr ""

#: nova/exception.py:620
#, python-format
msgid "Project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:624
msgid "Cannot find SR to read/write VDI."
msgstr ""

#: nova/exception.py:628
#, python-format
msgid "Network %(network_id)s is duplicated."
msgstr ""

#: nova/exception.py:632
#, python-format
msgid "Failed to release IP %(address)s with MAC %(mac_address)s"
msgstr ""

#: nova/exception.py:636
#, python-format
msgid "Network %(network_id)s is still in use."
msgstr ""

#: nova/exception.py:640
#, python-format
msgid "%(req)s is required to create a network."
msgstr ""

#: nova/exception.py:644
msgid "Maximum allowed length for 'label' is 255."
msgstr ""

#: nova/exception.py:648
#, python-format
msgid "%(key)s must be an integer."
msgstr ""

#: nova/exception.py:652
#, python-format
msgid "%(cidr)s is not a valid ip network."
msgstr ""

#: nova/exception.py:656
#, python-format
msgid "%(address)s is not a valid ip address."
msgstr ""

#: nova/exception.py:660
#, python-format
msgid "%(address)s is not within %(cidr)s."
msgstr ""

#: nova/exception.py:664
#, python-format
msgid "Detected existing vlan with id %(vlan)d"
msgstr ""

#: nova/exception.py:669
#, python-format
msgid "Requested cidr (%(cidr)s) conflicts with existing cidr (%(other)s)"
msgstr ""

#: nova/exception.py:675
#, python-format
msgid ""
"Network must be disassociated from project %(project_id)s before it can "
"be deleted."
msgstr ""

#: nova/exception.py:680
#, python-format
msgid "Network %(network_id)s could not be found."
msgstr ""

#: nova/exception.py:684
#, python-format
msgid "Port id %(port_id)s could not be found."
msgstr ""

#: nova/exception.py:688
#, python-format
msgid "Network could not be found for bridge %(bridge)s"
msgstr ""

#: nova/exception.py:692
#, python-format
msgid "Network could not be found for uuid %(uuid)s"
msgstr ""

#: nova/exception.py:696
#, python-format
msgid "Network could not be found with cidr %(cidr)s."
msgstr ""

#: nova/exception.py:700
#, python-format
msgid "Network could not be found for instance %(instance_id)s."
msgstr ""

#: nova/exception.py:704
msgid "No networks defined."
msgstr ""

#: nova/exception.py:708
msgid "No more available networks."
msgstr ""

#: nova/exception.py:712
#, python-format
msgid ""
"Either network uuid %(network_uuid)s is not present or is not assigned to"
" the project %(project_id)s."
msgstr ""

#: nova/exception.py:717
msgid ""
"More than one possible network found. Specify network ID(s) to select "
"which one(s) to connect to."
msgstr ""

#: nova/exception.py:722
#, python-format
msgid "Network %(network_uuid)s requires a subnet in order to boot instances on."
msgstr ""

#: nova/exception.py:727
#, python-format
msgid ""
"It is not allowed to create an interface on external network "
"%(network_uuid)s"
msgstr ""

#: nova/exception.py:732
#, python-format
msgid "Physical network is missing for network %(network_uuid)s"
msgstr ""

#: nova/exception.py:736
msgid "Could not find the datastore reference(s) which the VM uses."
msgstr ""

#: nova/exception.py:740
#, python-format
msgid "Port %(port_id)s is still in use."
msgstr ""

#: nova/exception.py:744
#, python-format
msgid "Port %(port_id)s requires a FixedIP in order to be used."
msgstr ""

#: nova/exception.py:748
#, python-format
msgid "Port %(port_id)s not usable for instance %(instance)s."
msgstr ""

#: nova/exception.py:752
#, python-format
msgid "No free port available for instance %(instance)s."
msgstr ""

#: nova/exception.py:756
#, python-format
msgid "Fixed ip %(address)s already exists."
msgstr ""

#: nova/exception.py:760
#, python-format
msgid "No fixed IP associated with id %(id)s."
msgstr ""

#: nova/exception.py:764
#, python-format
msgid "Fixed ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:768
#, python-format
msgid "Instance %(instance_uuid)s has zero fixed ips."
msgstr ""

#: nova/exception.py:772
#, python-format
msgid "Network host %(host)s has zero fixed ips in network %(network_id)s."
msgstr ""

#: nova/exception.py:777
#, python-format
msgid "Instance %(instance_uuid)s doesn't have fixed ip '%(ip)s'."
msgstr ""

#: nova/exception.py:781
#, python-format
msgid ""
"Fixed IP address (%(address)s) does not exist in network "
"(%(network_uuid)s)."
msgstr ""

#: nova/exception.py:786
#, python-format
msgid ""
"Fixed IP address %(address)s is already in use on instance "
"%(instance_uuid)s."
msgstr ""

#: nova/exception.py:791
#, python-format
msgid "More than one instance is associated with fixed ip address '%(address)s'."
msgstr ""

#: nova/exception.py:796
#, python-format
msgid "Fixed IP address %(address)s is invalid."
msgstr ""

#: nova/exception.py:801
#, python-format
msgid "No fixed IP addresses available for network: %(net)s"
msgstr ""

#: nova/exception.py:805
msgid "Zero fixed ips could be found."
msgstr ""

#: nova/exception.py:809
#, python-format
msgid "Floating ip %(address)s already exists."
msgstr ""

#: nova/exception.py:814
#, python-format
msgid "Floating ip not found for id %(id)s."
msgstr ""

#: nova/exception.py:818
#, python-format
msgid "The DNS entry %(name)s already exists in domain %(domain)s."
msgstr ""

#: nova/exception.py:822
#, python-format
msgid "Floating ip not found for address %(address)s."
msgstr ""

#: nova/exception.py:826
#, python-format
msgid "Floating ip not found for host %(host)s."
msgstr ""

#: nova/exception.py:830
#, python-format
msgid "Multiple floating ips are found for address %(address)s."
msgstr ""

#: nova/exception.py:834
msgid "Floating ip pool not found."
msgstr ""

#: nova/exception.py:839
msgid "Zero floating ips available."
msgstr ""

#: nova/exception.py:845
#, python-format
msgid "Floating ip %(address)s is associated."
msgstr ""

#: nova/exception.py:849
#, python-format
msgid "Floating ip %(address)s is not associated."
msgstr ""

#: nova/exception.py:853
msgid "Zero floating ips exist."
msgstr ""

#: nova/exception.py:858
#, python-format
msgid "Interface %(interface)s not found."
msgstr ""

#: nova/exception.py:863 nova/api/openstack/compute/contrib/floating_ips.py:99
#: nova/api/openstack/compute/contrib/floating_ips.py:183
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:81
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:172
msgid "Cannot disassociate auto assigned floating ip"
msgstr ""

#: nova/exception.py:868
#, python-format
msgid "Keypair %(name)s not found for user %(user_id)s"
msgstr ""

#: nova/exception.py:872
#, python-format
msgid "Service %(service_id)s could not be found."
msgstr ""

#: nova/exception.py:876
#, python-format
msgid "Service with host %(host)s binary %(binary)s exists."
msgstr ""

#: nova/exception.py:880
#, python-format
msgid "Service with host %(host)s topic %(topic)s exists."
msgstr ""

#: nova/exception.py:884
#, python-format
msgid "Host %(host)s could not be found."
msgstr ""

#: nova/exception.py:888
#, python-format
msgid "Compute host %(host)s could not be found."
msgstr ""

#: nova/exception.py:892
#, python-format
msgid "Compute host %(name)s needs to be created first before updating."
msgstr ""

#: nova/exception.py:897
#, python-format
msgid "Could not find binary %(binary)s on host %(host)s."
msgstr ""

#: nova/exception.py:901
#, python-format
msgid "Invalid reservation expiration %(expire)s."
msgstr ""

#: nova/exception.py:905
#, python-format
msgid ""
"Change would make usage less than 0 for the following resources: "
"%(unders)s"
msgstr ""

#: nova/exception.py:910
#, python-format
msgid "Wrong quota method %(method)s used on resource %(res)s"
msgstr ""

#: nova/exception.py:914
msgid "Quota could not be found"
msgstr ""

#: nova/exception.py:918
#, python-format
msgid "Quota exists for project %(project_id)s, resource %(resource)s"
msgstr ""

#: nova/exception.py:923
#, python-format
msgid "Unknown quota resources %(unknown)s."
msgstr ""

#: nova/exception.py:927
#, python-format
msgid "Quota for user %(user_id)s in project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:932
#, python-format
msgid "Quota for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:936
#, python-format
msgid "Quota class %(class_name)s could not be found."
msgstr ""

#: nova/exception.py:940
#, python-format
msgid "Quota usage for project %(project_id)s could not be found."
msgstr ""

#: nova/exception.py:944
#, python-format
msgid "Quota reservation %(uuid)s could not be found."
msgstr ""

#: nova/exception.py:948
#, python-format
msgid "Quota exceeded for resources: %(overs)s"
msgstr ""

#: nova/exception.py:952
#, python-format
msgid "Security group %(security_group_id)s not found."
msgstr ""

#: nova/exception.py:956
#, python-format
msgid "Security group %(security_group_id)s not found for project %(project_id)s."
msgstr ""

#: nova/exception.py:961
#, python-format
msgid "Security group with rule %(rule_id)s not found."
msgstr ""

#: nova/exception.py:966
#, python-format
msgid ""
"Security group %(security_group_name)s already exists for project "
"%(project_id)s."
msgstr ""

#: nova/exception.py:971
#, python-format
msgid ""
"Security group %(security_group_id)s is already associated with the "
"instance %(instance_id)s"
msgstr ""

#: nova/exception.py:976
#, python-format
msgid ""
"Security group %(security_group_id)s is not associated with the instance "
"%(instance_id)s"
msgstr ""

#: nova/exception.py:981
#, python-format
msgid "Security group default rule (%rule_id)s not found."
msgstr ""

#: nova/exception.py:985
msgid ""
"Network requires port_security_enabled and subnet associated in order to "
"apply security groups."
msgstr ""

#: nova/exception.py:991
#, python-format
msgid "Rule already exists in group: %(rule)s"
msgstr ""

#: nova/exception.py:995
msgid "No Unique Match Found."
msgstr ""

#: nova/exception.py:1000
#, python-format
msgid "Migration %(migration_id)s could not be found."
msgstr ""

#: nova/exception.py:1004
#, python-format
msgid "Migration not found for instance %(instance_id)s with status %(status)s."
msgstr ""

#: nova/exception.py:1009
#, python-format
msgid "Console pool %(pool_id)s could not be found."
msgstr ""

#: nova/exception.py:1013
#, python-format
msgid ""
"Console pool with host %(host)s, console_type %(console_type)s and "
"compute_host %(compute_host)s already exists."
msgstr ""

#: nova/exception.py:1019
#, python-format
msgid ""
"Console pool of type %(console_type)s for compute host %(compute_host)s "
"on proxy host %(host)s not found."
msgstr ""

#: nova/exception.py:1025
#, python-format
msgid "Console %(console_id)s could not be found."
msgstr ""

#: nova/exception.py:1029
#, python-format
msgid "Console for instance %(instance_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1033
#, python-format
msgid ""
"Console for instance %(instance_uuid)s in pool %(pool_id)s could not be "
"found."
msgstr ""

#: nova/exception.py:1038
#, python-format
msgid "Invalid console type %(console_type)s"
msgstr ""

#: nova/exception.py:1042
#, python-format
msgid "Unavailable console type %(console_type)s."
msgstr ""

#: nova/exception.py:1046
#, python-format
msgid "The console port range %(min_port)d-%(max_port)d is exhausted."
msgstr ""

#: nova/exception.py:1051
#, python-format
msgid "Flavor %(flavor_id)s could not be found."
msgstr ""

#: nova/exception.py:1055
#, python-format
msgid "Flavor with name %(flavor_name)s could not be found."
msgstr ""

#: nova/exception.py:1059
#, python-format
msgid "Flavor access not found for %(flavor_id)s / %(project_id)s combination."
msgstr ""

#: nova/exception.py:1064
#, python-format
msgid ""
"Flavor %(id)d extra spec cannot be updated or created after %(retries)d "
"retries."
msgstr ""

#: nova/exception.py:1069
#, python-format
msgid "Cell %(cell_name)s doesn't exist."
msgstr ""

#: nova/exception.py:1073
#, python-format
msgid "Cell with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1077
#, python-format
msgid "Inconsistency in cell routing: %(reason)s"
msgstr ""

#: nova/exception.py:1081
#, python-format
msgid "Service API method not found: %(detail)s"
msgstr ""

#: nova/exception.py:1085
msgid "Timeout waiting for response from cell"
msgstr ""

#: nova/exception.py:1089
#, python-format
msgid "Cell message has reached maximum hop count: %(hop_count)s"
msgstr ""

#: nova/exception.py:1093
msgid "No cells available matching scheduling criteria."
msgstr ""

#: nova/exception.py:1097
msgid "Cannot update cells configuration file."
msgstr ""

#: nova/exception.py:1101
#, python-format
msgid "Cell is not known for instance %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1105
#, python-format
msgid "Scheduler Host Filter %(filter_name)s could not be found."
msgstr ""

#: nova/exception.py:1109
#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(extra_specs_key)s."
msgstr ""

#: nova/exception.py:1114
#, python-format
msgid ""
"Metric %(name)s could not be found on the compute host node "
"%(host)s.%(node)s."
msgstr ""

#: nova/exception.py:1119
#, python-format
msgid "File %(file_path)s could not be found."
msgstr ""

#: nova/exception.py:1123
#, python-format
msgid "Virtual switch associated with the network adapter %(adapter)s not found."
msgstr ""

#: nova/exception.py:1128
#, python-format
msgid "Network adapter %(adapter)s could not be found."
msgstr ""

#: nova/exception.py:1132
#, python-format
msgid "Class %(class_name)s could not be found: %(exception)s"
msgstr ""

#: nova/exception.py:1136
msgid "Action not allowed."
msgstr ""

#: nova/exception.py:1140
#, python-format
msgid "Instance %(instance_id)s has no tag '%(tag)s'"
msgstr ""

#: nova/exception.py:1144
msgid "Rotation is not allowed for snapshots"
msgstr ""

#: nova/exception.py:1148
msgid "Rotation param is required for backup image_type"
msgstr ""

#: nova/exception.py:1153 nova/tests/unit/compute/test_keypairs.py:147
#, python-format
msgid "Key pair '%(key_name)s' already exists."
msgstr ""

#: nova/exception.py:1157
#, python-format
msgid "Instance %(name)s already exists."
msgstr ""

#: nova/exception.py:1161
#, python-format
msgid "Flavor with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1165
#, python-format
msgid "Flavor with ID %(flavor_id)s already exists."
msgstr ""

#: nova/exception.py:1169
#, python-format
msgid ""
"Flavor access already exists for flavor %(flavor_id)s and project "
"%(project_id)s combination."
msgstr ""

#: nova/exception.py:1174
#, python-format
msgid "%(path)s is not on shared storage: %(reason)s"
msgstr ""

#: nova/exception.py:1178
#, python-format
msgid "%(path)s is not on local storage: %(reason)s"
msgstr ""

#: nova/exception.py:1182
#, python-format
msgid "Storage error: %(reason)s"
msgstr ""

#: nova/exception.py:1186
#, python-format
msgid "Migration error: %(reason)s"
msgstr ""

#: nova/exception.py:1190
#, python-format
msgid "Migration pre-check error: %(reason)s"
msgstr ""

#: nova/exception.py:1194
#, python-format
msgid "Malformed message body: %(reason)s"
msgstr ""

#: nova/exception.py:1200
#, python-format
msgid "Could not find config at %(path)s"
msgstr ""

#: nova/exception.py:1204
#, python-format
msgid "Could not load paste app '%(name)s' from %(path)s"
msgstr ""

#: nova/exception.py:1208
msgid "When resizing, instances must change flavor!"
msgstr ""

#: nova/exception.py:1212
#, python-format
msgid "Resize error: %(reason)s"
msgstr ""

#: nova/exception.py:1216
#, python-format
msgid "Server disk was unable to be resized because: %(reason)s"
msgstr ""

#: nova/exception.py:1220
msgid "Flavor's memory is too small for requested image."
msgstr ""

#: nova/exception.py:1224
msgid "Flavor's disk is too small for requested image."
msgstr ""

#: nova/exception.py:1228
#, python-format
msgid "Insufficient free memory on compute node to start %(uuid)s."
msgstr ""

#: nova/exception.py:1232
#, python-format
msgid "No valid host was found. %(reason)s"
msgstr ""

#: nova/exception.py:1237
#, python-format
msgid "Quota exceeded: code=%(code)s"
msgstr ""

#: nova/exception.py:1247
#, python-format
msgid ""
"Quota exceeded for %(overs)s: Requested %(req)s, but already used "
"%(used)d of %(allowed)d %(resource)s"
msgstr ""

#: nova/exception.py:1252
msgid "Maximum number of floating ips exceeded"
msgstr ""

#: nova/exception.py:1256
msgid "Maximum number of fixed ips exceeded"
msgstr ""

#: nova/exception.py:1260
#, python-format
msgid "Maximum number of metadata items exceeds %(allowed)d"
msgstr ""

#: nova/exception.py:1264
msgid "Personality file limit exceeded"
msgstr ""

#: nova/exception.py:1268
msgid "Personality file path too long"
msgstr ""

#: nova/exception.py:1272
msgid "Personality file content too long"
msgstr ""

#: nova/exception.py:1276 nova/tests/unit/compute/test_keypairs.py:158
msgid "Maximum number of key pairs exceeded"
msgstr ""

#: nova/exception.py:1281
msgid "Maximum number of security groups or rules exceeded"
msgstr ""

#: nova/exception.py:1285
msgid "Maximum number of ports exceeded"
msgstr ""

#: nova/exception.py:1289
#, python-format
msgid ""
"Aggregate %(aggregate_id)s: action '%(action)s' caused an error: "
"%(reason)s."
msgstr ""

#: nova/exception.py:1294
#, python-format
msgid "Aggregate %(aggregate_id)s could not be found."
msgstr ""

#: nova/exception.py:1298
#, python-format
msgid "Aggregate %(aggregate_name)s already exists."
msgstr ""

#: nova/exception.py:1302
#, python-format
msgid "Aggregate %(aggregate_id)s has no host %(host)s."
msgstr ""

#: nova/exception.py:1306
#, python-format
msgid "Aggregate %(aggregate_id)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:1311
#, python-format
msgid "Aggregate %(aggregate_id)s already has host %(host)s."
msgstr ""

#: nova/exception.py:1315
msgid "Unable to create flavor"
msgstr ""

#: nova/exception.py:1319
#, python-format
msgid "Failed to set admin password on %(instance)s because %(reason)s"
msgstr ""

#: nova/exception.py:1326
#, python-format
msgid "Instance %(instance_id)s could not be found."
msgstr ""

#: nova/exception.py:1330
#, python-format
msgid "Info cache for instance %(instance_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1336
msgid "Invalid association."
msgstr ""

#: nova/exception.py:1340
#, python-format
msgid "Node %(node_id)s could not be found."
msgstr ""

#: nova/exception.py:1344
#, python-format
msgid "Node with UUID %(node_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1348
#, python-format
msgid "Marker %(marker)s could not be found."
msgstr ""

#: nova/exception.py:1352
#, python-format
msgid "Invalid id: %(instance_id)s (expecting \"i-...\")"
msgstr ""

#: nova/exception.py:1357
#, python-format
msgid "Invalid id: %(volume_id)s (expecting \"i-...\")"
msgstr ""

#: nova/exception.py:1362
#, python-format
msgid "Could not fetch image %(image_id)s"
msgstr ""

#: nova/exception.py:1366
#, python-format
msgid "Could not upload image %(image_id)s"
msgstr ""

#: nova/exception.py:1370
#, python-format
msgid "Task %(task_name)s is already running on host %(host)s"
msgstr ""

#: nova/exception.py:1374
#, python-format
msgid "Task %(task_name)s is not running on host %(host)s"
msgstr ""

#: nova/exception.py:1378
#, python-format
msgid "Instance %(instance_uuid)s is locked"
msgstr ""

#: nova/exception.py:1382
#, python-format
msgid "Invalid value for Config Drive option: %(option)s"
msgstr ""

#: nova/exception.py:1386
#, python-format
msgid "Could not mount vfat config drive. %(operation)s failed. Error: %(error)s"
msgstr ""

#: nova/exception.py:1391
#, python-format
msgid "Unknown config drive format %(format)s. Select one of iso9660 or vfat."
msgstr ""

#: nova/exception.py:1396
#, python-format
msgid "Failed to attach network adapter device to %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1401
#, python-format
msgid "Failed to detach network adapter device from %(instance_uuid)s"
msgstr ""

#: nova/exception.py:1406
#, python-format
msgid ""
"User data too large. User data must be no larger than %(maxsize)s bytes "
"once base64 encoded. Your data is %(length)d bytes"
msgstr ""

#: nova/exception.py:1412
msgid "User data needs to be valid base 64."
msgstr ""

#: nova/exception.py:1416
#, python-format
msgid ""
"Unexpected task state: expecting %(expected)s but the actual state is "
"%(actual)s"
msgstr ""

#: nova/exception.py:1425
#, python-format
msgid ""
"Action for request_id %(request_id)s on instance %(instance_uuid)s not "
"found"
msgstr ""

#: nova/exception.py:1430
#, python-format
msgid "Event %(event)s not found for action id %(action_id)s"
msgstr ""

#: nova/exception.py:1434
#, python-format
msgid ""
"Unexpected VM state: expecting %(expected)s but the actual state is "
"%(actual)s"
msgstr ""

#: nova/exception.py:1439
#, python-format
msgid "The CA file for %(project)s could not be found"
msgstr ""

#: nova/exception.py:1443
#, python-format
msgid "The CRL file for %(project)s could not be found"
msgstr ""

#: nova/exception.py:1447
msgid "Instance recreate is not supported."
msgstr ""

#: nova/exception.py:1451
#, python-format
msgid ""
"The service from servicegroup driver %(driver)s is temporarily "
"unavailable."
msgstr ""

#: nova/exception.py:1456
#, python-format
msgid "%(binary)s attempted direct database access which is not allowed by policy"
msgstr ""

#: nova/exception.py:1461
#, python-format
msgid "Virtualization type '%(virt)s' is not supported by this compute driver"
msgstr ""

#: nova/exception.py:1466
#, python-format
msgid ""
"Requested hardware '%(model)s' is not supported by the '%(virt)s' virt "
"driver"
msgstr ""

#: nova/exception.py:1471
#, python-format
msgid "Invalid Base 64 data for file %(path)s"
msgstr ""

#: nova/exception.py:1475
#, python-format
msgid "Build of instance %(instance_uuid)s aborted: %(reason)s"
msgstr ""

#: nova/exception.py:1479
#, python-format
msgid "Build of instance %(instance_uuid)s was re-scheduled: %(reason)s"
msgstr ""

#: nova/exception.py:1484
#, python-format
msgid "Shadow table with name %(name)s already exists."
msgstr ""

#: nova/exception.py:1489
#, python-format
msgid "Instance rollback performed due to: %s"
msgstr ""

#: nova/exception.py:1495
#, python-format
msgid "Unsupported object type %(objtype)s"
msgstr ""

#: nova/exception.py:1499
#, python-format
msgid "Cannot call %(method)s on orphaned %(objtype)s object"
msgstr ""

#: nova/exception.py:1503
#, python-format
msgid "Version %(objver)s of %(objname)s is not supported"
msgstr ""

#: nova/exception.py:1507
#, python-format
msgid "Cannot modify readonly field %(field)s"
msgstr ""

#: nova/exception.py:1511
#, python-format
msgid "Object action %(action)s failed because: %(reason)s"
msgstr ""

#: nova/exception.py:1515
#, python-format
msgid "Field %(field)s of %(objname)s is not an instance of Field"
msgstr ""

#: nova/exception.py:1519
#, python-format
msgid "Core API extensions are missing: %(missing_apis)s"
msgstr ""

#: nova/exception.py:1523
#, python-format
msgid "Error during following call to agent: %(method)s"
msgstr ""

#: nova/exception.py:1527
#, python-format
msgid "Unable to contact guest agent. The following call timed out: %(method)s"
msgstr ""

#: nova/exception.py:1532
#, python-format
msgid "Agent does not support the call: %(method)s"
msgstr ""

#: nova/exception.py:1536
#, python-format
msgid "Instance group %(group_uuid)s could not be found."
msgstr ""

#: nova/exception.py:1540
#, python-format
msgid "Instance group %(group_uuid)s already exists."
msgstr ""

#: nova/exception.py:1544
#, python-format
msgid "Instance group %(group_uuid)s has no metadata with key %(metadata_key)s."
msgstr ""

#: nova/exception.py:1549
#, python-format
msgid "Instance group %(group_uuid)s has no member with id %(instance_id)s."
msgstr ""

#: nova/exception.py:1554
#, python-format
msgid "Instance group %(group_uuid)s has no policy %(policy)s."
msgstr ""

#: nova/exception.py:1558
#, python-format
msgid "Number of retries to plugin (%(num_retries)d) exceeded."
msgstr ""

#: nova/exception.py:1562
#, python-format
msgid "There was an error with the download module %(module)s. %(reason)s"
msgstr ""

#: nova/exception.py:1567
#, python-format
msgid ""
"The metadata for this location will not work with this module %(module)s."
"  %(reason)s."
msgstr ""

#: nova/exception.py:1572
#, python-format
msgid "The method %(method_name)s is not implemented."
msgstr ""

#: nova/exception.py:1576
#, python-format
msgid "The module %(module)s is misconfigured: %(reason)s."
msgstr ""

#: nova/exception.py:1580
#, python-format
msgid "Error when creating resource monitor: %(monitor)s"
msgstr ""

#: nova/exception.py:1584
#, python-format
msgid "The PCI address %(address)s has an incorrect format."
msgstr ""

#: nova/exception.py:1588
#, python-format
msgid ""
"Invalid PCI Whitelist: The PCI address %(address)s has an invalid "
"%(field)s."
msgstr ""

#: nova/exception.py:1593
msgid ""
"Invalid PCI Whitelist: The PCI whitelist can specify devname or address, "
"but not both"
msgstr ""

#: nova/exception.py:1599
#, python-format
msgid "PCI device %(id)s not found"
msgstr ""

#: nova/exception.py:1603
#, python-format
msgid "PCI Device %(node_id)s:%(address)s not found."
msgstr ""

#: nova/exception.py:1607
#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is %(status)s instead of "
"%(hopestatus)s"
msgstr ""

#: nova/exception.py:1613
#, python-format
msgid ""
"PCI device %(compute_node_id)s:%(address)s is owned by %(owner)s instead "
"of %(hopeowner)s"
msgstr ""

#: nova/exception.py:1619
#, python-format
msgid "PCI device request (%requests)s failed"
msgstr ""

#: nova/exception.py:1624
#, python-format
msgid ""
"Attempt to consume PCI device %(compute_node_id)s:%(address)s from empty "
"pool"
msgstr ""

#: nova/exception.py:1630
#, python-format
msgid "Invalid PCI alias definition: %(reason)s"
msgstr ""

#: nova/exception.py:1634
#, python-format
msgid "PCI alias %(alias)s is not defined"
msgstr ""

#: nova/exception.py:1639
#, python-format
msgid "Not enough parameters: %(reason)s"
msgstr ""

#: nova/exception.py:1644
#, python-format
msgid "Invalid PCI devices Whitelist config %(reason)s"
msgstr ""

#: nova/exception.py:1648
#, python-format
msgid "Cannot change %(node_id)s to %(new_node_id)s"
msgstr ""

#: nova/exception.py:1658
#, python-format
msgid ""
"Failed to prepare PCI device %(id)s for instance %(instance_uuid)s: "
"%(reason)s"
msgstr ""

#: nova/exception.py:1663
#, python-format
msgid "Failed to detach PCI device %(dev)s: %(reason)s"
msgstr ""

#: nova/exception.py:1667
#, python-format
msgid "%(type)s hypervisor does not support PCI devices"
msgstr ""

#: nova/exception.py:1671
#, python-format
msgid "Key manager error: %(reason)s"
msgstr ""

#: nova/exception.py:1675
#, python-format
msgid "Failed to remove volume(s): (%(reason)s)"
msgstr ""

#: nova/exception.py:1679
#, python-format
msgid "Provided video model (%(model)s) is not supported."
msgstr ""

#: nova/exception.py:1683
#, python-format
msgid "The provided RNG device path: (%(path)s) is not present on the host."
msgstr ""

#: nova/exception.py:1688
#, python-format
msgid ""
"The requested amount of video memory %(req_vram)d is higher than the "
"maximum allowed by flavor %(max_vram)d."
msgstr ""

#: nova/exception.py:1693
#, python-format
msgid "Provided watchdog action (%(action)s) is not supported."
msgstr ""

#: nova/exception.py:1697
msgid ""
"Live migration of instances with config drives is not supported in "
"libvirt unless libvirt instance path and drive data is shared across "
"compute nodes."
msgstr ""

#: nova/exception.py:1703
#, python-format
msgid ""
"Host %(server)s is running an old version of Nova, live migrations "
"involving that version may cause data loss. Upgrade Nova on %(server)s "
"and try again."
msgstr ""

#: nova/exception.py:1709
#, python-format
msgid "Error during unshelve instance %(instance_id)s: %(reason)s"
msgstr ""

#: nova/exception.py:1713
#, python-format
msgid ""
"Image vCPU limits %(sockets)d:%(cores)d:%(threads)d exceeds permitted "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""

#: nova/exception.py:1718
#, python-format
msgid ""
"Image vCPU topology %(sockets)d:%(cores)d:%(threads)d exceeds permitted "
"%(maxsockets)d:%(maxcores)d:%(maxthreads)d"
msgstr ""

#: nova/exception.py:1723
#, python-format
msgid ""
"Requested vCPU limits %(sockets)d:%(cores)d:%(threads)d are impossible to"
" satisfy for vcpus count %(vcpus)d"
msgstr ""

#: nova/exception.py:1728
#, python-format
msgid "Architecture name '%(arch)s' is not recognised"
msgstr ""

#: nova/exception.py:1732
msgid "CPU and memory allocation must be provided for all NUMA nodes"
msgstr ""

#: nova/exception.py:1737
#, python-format
msgid ""
"Image property '%(name)s' is not permitted to override NUMA configuration"
" set against the flavor"
msgstr ""

#: nova/exception.py:1742
msgid ""
"Asymmetric NUMA topologies require explicit assignment of CPUs and memory"
" to nodes in image or flavor"
msgstr ""

#: nova/exception.py:1747
#, python-format
msgid "CPU number %(cpunum)d is larger than max %(cpumax)d"
msgstr ""

#: nova/exception.py:1751
#, python-format
msgid "CPU number %(cpunum)d is assigned to two nodes"
msgstr ""

#: nova/exception.py:1755
#, python-format
msgid "CPU number %(cpuset)s is not assigned to any node"
msgstr ""

#: nova/exception.py:1759
#, python-format
msgid "%(memsize)d MB of memory assigned, but expected %(memtotal)d MB"
msgstr ""

#: nova/exception.py:1764
#, python-format
msgid "Invalid characters in hostname '%(hostname)s'"
msgstr ""

#: nova/exception.py:1768
#, python-format
msgid "Instance %(instance_uuid)s does not specify a NUMA topology"
msgstr ""

#: nova/exception.py:1772
#, python-format
msgid "Not able to acquire a free port for %(host)s"
msgstr ""

#: nova/exception.py:1776
#, python-format
msgid "Not able to bind %(host)s:%(port)d, %(error)s"
msgstr ""

#: nova/exception.py:1780
#, python-format
msgid ""
"Number of serial ports '%(num_ports)s' specified in '%(property)s' isn't "
"valid."
msgstr ""

#: nova/exception.py:1785
msgid ""
"Forbidden to exceed flavor value of number of serial ports passed in "
"image meta."
msgstr ""

#: nova/exception.py:1790
#, python-format
msgid "Image's config drive option '%(config_drive)s' is invalid"
msgstr ""

#: nova/exception.py:1794
#, python-format
msgid "Hypervisor virtualization type '%(hv_type)s' is not recognised"
msgstr ""

#: nova/exception.py:1799
#, python-format
msgid "Virtual machine mode '%(vmmode)s' is not recognised"
msgstr ""

#: nova/exception.py:1803
#, python-format
msgid "The token '%(token)s' is invalid or has expired"
msgstr ""

#: nova/exception.py:1807
msgid "Invalid Connection Info"
msgstr ""

#: nova/exception.py:1811
#, python-format
msgid "Quiescing is not supported in instance %(instance_id)s: %(reason)s"
msgstr ""

#: nova/hooks.py:77
msgid "Wrong type of hook method. Only 'pre' and 'post' type allowed"
msgstr ""

#: nova/service.py:161
#, python-format
msgid "Starting %(topic)s node (version %(version)s)"
msgstr ""

#: nova/service.py:340
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: nova/service.py:433
msgid "serve() can only be called once"
msgstr ""

#: nova/utils.py:370
#, python-format
msgid "IPv4 address is not found.: %s"
msgstr ""

#: nova/utils.py:373
#, python-format
msgid "Couldn't get IPv4 of %(interface)s : %(ex)s"
msgstr ""

#: nova/utils.py:388
#, python-format
msgid "Link Local address is not found.:%s"
msgstr ""

#: nova/utils.py:391
#, python-format
msgid "Couldn't get Link Local IP of %(interface)s :%(ex)s"
msgstr ""

#: nova/utils.py:412
#, python-format
msgid "Invalid backend: %s"
msgstr ""

#: nova/utils.py:455
#, python-format
msgid "Expected object of type: %s"
msgstr ""

#: nova/utils.py:961
msgid "The input is not a string or unicode"
msgstr ""

#: nova/utils.py:963
#, python-format
msgid "%s is not a string or unicode"
msgstr ""

#: nova/utils.py:970
#, python-format
msgid "%(name)s has a minimum character requirement of %(min_length)s."
msgstr ""

#: nova/utils.py:975
#, python-format
msgid "%(name)s has more than %(max_length)s characters."
msgstr ""

#: nova/utils.py:985
#, python-format
msgid "%(value_name)s must be an integer"
msgstr ""

#: nova/utils.py:991
#, python-format
msgid "%(value_name)s must be >= %(min_value)d"
msgstr ""

#: nova/utils.py:997
#, python-format
msgid "%(value_name)s must be <= %(max_value)d"
msgstr ""

#: nova/utils.py:1031
#, python-format
msgid "Hypervisor version %s is invalid."
msgstr ""

#: nova/wsgi.py:170 nova/openstack/common/sslutils.py:53
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: nova/wsgi.py:174 nova/openstack/common/sslutils.py:56
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: nova/wsgi.py:178 nova/openstack/common/sslutils.py:59
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: nova/wsgi.py:182 nova/openstack/common/sslutils.py:62
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: nova/wsgi.py:342
msgid "You must implement __call__"
msgstr ""

#: nova/api/auth.py:140
msgid "Invalid service catalog json."
msgstr ""

#: nova/api/ec2/__init__.py:163
msgid "Too many failed authentications."
msgstr ""

#: nova/api/ec2/__init__.py:192
msgid "Signature not provided"
msgstr ""

#: nova/api/ec2/__init__.py:197
msgid "Access key not provided"
msgstr ""

#: nova/api/ec2/__init__.py:251
#, python-format
msgid "Failure parsing response from keystone: %s"
msgstr ""

#: nova/api/ec2/__init__.py:311
msgid "Timestamp failed validation."
msgstr ""

#: nova/api/ec2/__init__.py:409
#, python-format
msgid "Unauthorized request for controller=%(controller)s and action=%(action)s"
msgstr ""

#: nova/api/ec2/__init__.py:528
msgid "Unknown error occurred."
msgstr ""

#: nova/api/ec2/cloud.py:407
#, python-format
msgid "Create snapshot of volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:434
#, python-format
msgid "Could not find key pair(s): %s"
msgstr ""

#: nova/api/ec2/cloud.py:450
#, python-format
msgid "Create key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:462
#, python-format
msgid "Import key %s"
msgstr ""

#: nova/api/ec2/cloud.py:475
#, python-format
msgid "Delete key pair %s"
msgstr ""

#: nova/api/ec2/cloud.py:617 nova/api/ec2/cloud.py:747
msgid "need group_name or group_id"
msgstr ""

#: nova/api/ec2/cloud.py:622
msgid "can't build a valid rule"
msgstr ""

#: nova/api/ec2/cloud.py:630
#, python-format
msgid "Invalid IP protocol %(protocol)s"
msgstr ""

#: nova/api/ec2/cloud.py:664 nova/api/ec2/cloud.py:700
msgid "No rule for the specified parameters."
msgstr ""

#: nova/api/ec2/cloud.py:778
#, python-format
msgid "Get console output for instance %s"
msgstr ""

#: nova/api/ec2/cloud.py:850
#, python-format
msgid "Create volume from snapshot %s"
msgstr ""

#: nova/api/ec2/cloud.py:854 nova/api/openstack/compute/contrib/volumes.py:244
#, python-format
msgid "Create volume of %s GB"
msgstr ""

#: nova/api/ec2/cloud.py:894
#, python-format
msgid "Attach volume %(volume_id)s to instance %(instance_id)s at %(device)s"
msgstr ""

#: nova/api/ec2/cloud.py:924 nova/api/openstack/compute/contrib/volumes.py:502
#, python-format
msgid "Detach volume %s"
msgstr ""

#: nova/api/ec2/cloud.py:1284
msgid "Allocate address"
msgstr ""

#: nova/api/ec2/cloud.py:1289
#, python-format
msgid "Release address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1294
#, python-format
msgid "Associate address %(public_ip)s to instance %(instance_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1305
msgid "Unable to associate IP Address, no fixed_ips."
msgstr ""

#: nova/api/ec2/cloud.py:1327
#, python-format
msgid "Disassociate address %s"
msgstr ""

#: nova/api/ec2/cloud.py:1331
msgid "Floating ip is not associated."
msgstr ""

#: nova/api/ec2/cloud.py:1347 nova/api/openstack/compute/servers.py:919
#: nova/api/openstack/compute/plugins/v3/multiple_create.py:56
msgid "min_count must be <= max_count"
msgstr ""

#: nova/api/ec2/cloud.py:1379
msgid "Image must be available"
msgstr ""

#: nova/api/ec2/cloud.py:1479
#, python-format
msgid "Reboot instance %r"
msgstr ""

#: nova/api/ec2/cloud.py:1594
#, python-format
msgid "De-registering image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1610
msgid "imageLocation is required"
msgstr ""

#: nova/api/ec2/cloud.py:1630
#, python-format
msgid "Registered image %(image_location)s with id %(image_id)s"
msgstr ""

#: nova/api/ec2/cloud.py:1691
msgid "user or group not specified"
msgstr ""

#: nova/api/ec2/cloud.py:1694
msgid "only group \"all\" is supported"
msgstr ""

#: nova/api/ec2/cloud.py:1697
msgid "operation_type must be add or remove"
msgstr ""

#: nova/api/ec2/cloud.py:1699
#, python-format
msgid "Updating image %s publicity"
msgstr ""

#: nova/api/ec2/cloud.py:1712
#, python-format
msgid "Not allowed to modify attributes for image %s"
msgstr ""

#: nova/api/ec2/cloud.py:1742
#, python-format
msgid ""
"Invalid value '%(ec2_instance_id)s' for instanceId. Instance does not "
"have a volume attached at root (%(root)s)"
msgstr ""

#: nova/api/ec2/cloud.py:1775
#, python-format
msgid ""
"Couldn't stop instance %(instance)s within 1 hour. Current vm_state: "
"%(vm_state)s, current task_state: %(task_state)s"
msgstr ""

#: nova/api/ec2/cloud.py:1799
#, python-format
msgid "image of %(instance)s at %(now)s"
msgstr ""

#: nova/api/ec2/cloud.py:1824 nova/api/ec2/cloud.py:1874
msgid "resource_id and tag are required"
msgstr ""

#: nova/api/ec2/cloud.py:1828 nova/api/ec2/cloud.py:1878
msgid "Expecting a list of resources"
msgstr ""

#: nova/api/ec2/cloud.py:1833 nova/api/ec2/cloud.py:1883
#: nova/api/ec2/cloud.py:1941
msgid "Only instances implemented"
msgstr ""

#: nova/api/ec2/cloud.py:1837 nova/api/ec2/cloud.py:1887
msgid "Expecting a list of tagSets"
msgstr ""

#: nova/api/ec2/cloud.py:1843 nova/api/ec2/cloud.py:1896
msgid "Expecting tagSet to be key/value pairs"
msgstr ""

#: nova/api/ec2/cloud.py:1850
msgid "Expecting both key and value to be set"
msgstr ""

#: nova/api/ec2/cloud.py:1901
msgid "Expecting key to be set"
msgstr ""

#: nova/api/ec2/cloud.py:1975
msgid "Invalid CIDR"
msgstr ""

#: nova/api/ec2/ec2utils.py:256
#, python-format
msgid "Unacceptable attach status:%s for ec2 API."
msgstr ""

#: nova/api/ec2/ec2utils.py:279
msgid "Request must include either Timestamp or Expires, but cannot contain both"
msgstr ""

#: nova/api/ec2/ec2utils.py:297
msgid "Timestamp is invalid."
msgstr ""

#: nova/api/metadata/handler.py:149 nova/api/metadata/handler.py:208
msgid "An unknown error has occurred. Please try your request again."
msgstr ""

#: nova/api/metadata/handler.py:169
msgid "X-Instance-ID header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:171
msgid "X-Tenant-ID header is missing from request."
msgstr ""

#: nova/api/metadata/handler.py:173
msgid "Multiple X-Instance-ID headers found within request."
msgstr ""

#: nova/api/metadata/handler.py:175
msgid "Multiple X-Tenant-ID headers found within request."
msgstr ""

#: nova/api/metadata/handler.py:199
msgid "Invalid proxy request signature."
msgstr ""

#: nova/api/metadata/password.py:62
msgid "Request is too large."
msgstr ""

#: nova/api/openstack/__init__.py:190
msgid "Must specify an ExtensionManager class"
msgstr ""

#: nova/api/openstack/common.py:224
#, python-format
msgid "%s param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:227
#, python-format
msgid "%s param must be positive"
msgstr ""

#: nova/api/openstack/common.py:252
msgid "offset param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:258
msgid "limit param must be an integer"
msgstr ""

#: nova/api/openstack/common.py:262
msgid "limit param must be positive"
msgstr ""

#: nova/api/openstack/common.py:266
msgid "offset param must be positive"
msgstr ""

#: nova/api/openstack/common.py:319
#, python-format
msgid "href %s does not contain version"
msgstr ""

#: nova/api/openstack/common.py:332
msgid "Image metadata limit exceeded"
msgstr ""

#: nova/api/openstack/common.py:339
msgid "Image metadata key cannot be blank"
msgstr ""

#: nova/api/openstack/common.py:342
msgid "Image metadata key too long"
msgstr ""

#: nova/api/openstack/common.py:345
msgid "Invalid image metadata"
msgstr ""

#: nova/api/openstack/common.py:408
#, python-format
msgid ""
"Cannot '%(action)s' instance %(server_id)s while it is in %(attr)s "
"%(state)s"
msgstr ""

#: nova/api/openstack/common.py:413
#, python-format
msgid "Cannot '%(action)' instance %(server_id)s which has never been active"
msgstr ""

#: nova/api/openstack/common.py:417
#, python-format
msgid "Instance %(server_id)s is in an invalid state for '%(action)s'"
msgstr ""

#: nova/api/openstack/common.py:500
msgid "Instance snapshots are not permitted at this time."
msgstr ""

#: nova/api/openstack/common.py:622
msgid "Cells is not enabled."
msgstr ""

#: nova/api/openstack/extensions.py:349
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:372
#, python-format
msgid "Failed to load extension %(ext_name)s:%(exc)s"
msgstr ""

#: nova/api/openstack/extensions.py:507
#, python-format
msgid ""
"Unexpected API Error. Please report this at "
"http://bugs.launchpad.net/nova/ and attach the Nova API log if possible."
"\n"
"%s"
msgstr ""

#: nova/api/openstack/wsgi.py:286 nova/api/openstack/wsgi.py:667
msgid "cannot understand JSON"
msgstr ""

#: nova/api/openstack/wsgi.py:672
msgid "too many body keys"
msgstr ""

#: nova/api/openstack/wsgi.py:963
#, python-format
msgid "There is no such action: %s"
msgstr ""

#: nova/api/openstack/wsgi.py:966 nova/api/openstack/wsgi.py:992
#: nova/api/openstack/compute/server_metadata.py:57
#: nova/api/openstack/compute/server_metadata.py:78
#: nova/api/openstack/compute/server_metadata.py:107
#: nova/api/openstack/compute/server_metadata.py:137
#: nova/api/openstack/compute/contrib/evacuate.py:47
msgid "Malformed request body"
msgstr ""

#: nova/api/openstack/wsgi.py:970
#, python-format
msgid "Action: '%(action)s', calling method: %(meth)s, body: %(body)s"
msgstr ""

#: nova/api/openstack/wsgi.py:989
msgid "Unsupported Content-Type"
msgstr ""

#: nova/api/openstack/wsgi.py:1001
#, python-format
msgid ""
"Malformed request URL: URL's project_id '%(project_id)s' doesn't match "
"Context's project_id '%(context_project_id)s'"
msgstr ""

#: nova/api/openstack/xmlutil.py:285
msgid "element is not a child"
msgstr ""

#: nova/api/openstack/xmlutil.py:444
msgid "root element selecting a list"
msgstr ""

#: nova/api/openstack/xmlutil.py:767
#, python-format
msgid "Template tree mismatch; adding slave %(slavetag)s to master %(mastertag)s"
msgstr ""

#: nova/api/openstack/xmlutil.py:887
msgid "subclasses must implement construct()!"
msgstr ""

#: nova/api/openstack/compute/extensions.py:37
msgid "Initializing extension manager."
msgstr ""

#: nova/api/openstack/compute/flavors.py:108
#: nova/api/openstack/compute/plugins/v3/flavors.py:73
#, python-format
msgid "Invalid is_public filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:131
#, python-format
msgid "Invalid minRam filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:138
#: nova/api/openstack/compute/plugins/v3/flavors.py:103
#, python-format
msgid "Invalid minDisk filter [%s]"
msgstr ""

#: nova/api/openstack/compute/flavors.py:146
#: nova/api/openstack/compute/servers.py:612
#: nova/api/openstack/compute/plugins/v3/flavors.py:112
#: nova/api/openstack/compute/plugins/v3/servers.py:360
#, python-format
msgid "marker [%s] not found"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:37
#: nova/api/openstack/compute/images.py:135
#: nova/api/openstack/compute/images.py:151
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:42
#: nova/api/openstack/compute/plugins/v3/images.py:89
#: nova/api/openstack/compute/plugins/v3/images.py:107
msgid "Image not found."
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:81
msgid "Incorrect request body format"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:85
#: nova/api/openstack/compute/server_metadata.py:86
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:118
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:91
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:85
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:78
msgid "Request body and URI mismatch"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:88
#: nova/api/openstack/compute/server_metadata.py:90
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:121
msgid "Request body contains too many items"
msgstr ""

#: nova/api/openstack/compute/image_metadata.py:122
#: nova/api/openstack/compute/plugins/v3/image_metadata.py:120
msgid "Invalid metadata key"
msgstr ""

#: nova/api/openstack/compute/images.py:156
#: nova/api/openstack/compute/plugins/v3/images.py:112
msgid "You are not allowed to delete the image."
msgstr ""

#: nova/api/openstack/compute/ips.py:76
#: nova/api/openstack/compute/plugins/v3/ips.py:50
msgid "Instance is not a member of specified network"
msgstr ""

#: nova/api/openstack/compute/limits.py:162
#, python-format
msgid ""
"Only %(value)s %(verb)s request(s) can be made to %(uri)s every "
"%(unit_string)s."
msgstr ""

#: nova/api/openstack/compute/limits.py:290
msgid "This request was rate-limited."
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:37
#: nova/api/openstack/compute/server_metadata.py:133
#: nova/api/openstack/compute/server_metadata.py:186
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:45
msgid "Server does not exist"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:60
#: nova/api/openstack/compute/server_metadata.py:111
msgid "Malformed request body. metadata must be object"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:82
msgid "Malformed request body. meta item must be object"
msgstr ""

#: nova/api/openstack/compute/server_metadata.py:166
#: nova/api/openstack/compute/server_metadata.py:177
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:130
#: nova/api/openstack/compute/plugins/v3/server_metadata.py:142
msgid "Metadata item was not found"
msgstr ""

#: nova/api/openstack/compute/servers.py:554
#: nova/api/openstack/compute/contrib/cells.py:432
#: nova/api/openstack/compute/plugins/v3/servers.py:293
msgid "Invalid changes-since value"
msgstr ""

#: nova/api/openstack/compute/servers.py:573
#: nova/api/openstack/compute/plugins/v3/servers.py:312
msgid "Only administrators may list deleted instances"
msgstr ""

#: nova/api/openstack/compute/servers.py:659
#, python-format
msgid "Bad personality format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:662
msgid "Bad personality format"
msgstr ""

#: nova/api/openstack/compute/servers.py:665
#, python-format
msgid "Personality content for %s cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:680
#, python-format
msgid "Bad port format: port uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:688
msgid "Unknown argument : port"
msgstr ""

#: nova/api/openstack/compute/servers.py:697
#: nova/api/openstack/compute/plugins/v3/servers.py:425
#, python-format
msgid "Bad networks format: network uuid is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:708
#, python-format
msgid "Invalid fixed IP address (%s)"
msgstr ""

#: nova/api/openstack/compute/servers.py:713
#: nova/api/openstack/compute/plugins/v3/servers.py:432
#, python-format
msgid "Duplicate networks (%s) are not allowed"
msgstr ""

#: nova/api/openstack/compute/servers.py:720
#: nova/api/openstack/compute/plugins/v3/servers.py:439
#, python-format
msgid "Bad network format: missing %s"
msgstr ""

#: nova/api/openstack/compute/servers.py:723
#: nova/api/openstack/compute/servers.py:818
#: nova/api/openstack/compute/plugins/v3/servers.py:442
msgid "Bad networks format"
msgstr ""

#: nova/api/openstack/compute/servers.py:749
msgid "Userdata content cannot be decoded"
msgstr ""

#: nova/api/openstack/compute/servers.py:754
msgid "accessIPv4 is not proper IPv4 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:759
msgid "accessIPv6 is not proper IPv6 format"
msgstr ""

#: nova/api/openstack/compute/servers.py:782
msgid "Server name is not defined"
msgstr ""

#: nova/api/openstack/compute/servers.py:834
#: nova/api/openstack/compute/servers.py:973
#: nova/api/openstack/compute/plugins/v3/servers.py:522
#: nova/api/openstack/compute/plugins/v3/servers.py:548
msgid "Invalid flavorRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:857
#: nova/api/openstack/compute/plugins/v3/block_device_mapping_v1.py:58
msgid "block_device_mapping must be a list"
msgstr ""

#: nova/api/openstack/compute/servers.py:877
#: nova/api/openstack/compute/plugins/v3/block_device_mapping.py:52
#: nova/api/openstack/compute/plugins/v3/block_device_mapping_v1.py:53
msgid ""
"Using different block_device_mapping syntaxes is not allowed in the same "
"request."
msgstr ""

#: nova/api/openstack/compute/servers.py:882
#: nova/api/openstack/compute/plugins/v3/block_device_mapping.py:57
msgid "block_device_mapping_v2 must be a list"
msgstr ""

#: nova/api/openstack/compute/servers.py:970
#: nova/api/openstack/compute/plugins/v3/servers.py:545
msgid "Can not find requested image"
msgstr ""

#: nova/api/openstack/compute/servers.py:976
#: nova/api/openstack/compute/plugins/v3/servers.py:551
msgid "Invalid key_name provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:979
#: nova/api/openstack/compute/plugins/v3/servers.py:554
msgid "Invalid config_drive provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:1075
msgid "HostId cannot be updated."
msgstr ""

#: nova/api/openstack/compute/servers.py:1079
msgid "Personality cannot be updated."
msgstr ""

#: nova/api/openstack/compute/servers.py:1089
#: nova/api/openstack/compute/servers.py:1213
#: nova/api/openstack/compute/servers.py:1398
#: nova/api/openstack/compute/plugins/v3/servers.py:721
#: nova/api/openstack/compute/plugins/v3/servers.py:842
#: nova/api/openstack/compute/plugins/v3/servers.py:949
msgid "Instance could not be found"
msgstr ""

#: nova/api/openstack/compute/servers.py:1104
#: nova/api/openstack/compute/servers.py:1122
#: nova/api/openstack/compute/plugins/v3/servers.py:736
#: nova/api/openstack/compute/plugins/v3/servers.py:753
msgid "Instance has not been resized."
msgstr ""

#: nova/api/openstack/compute/servers.py:1125
#: nova/api/openstack/compute/plugins/v3/servers.py:756
msgid "Flavor used by the instance could not be found."
msgstr ""

#: nova/api/openstack/compute/servers.py:1141
#: nova/api/openstack/compute/plugins/v3/servers.py:770
msgid "Argument 'type' for reboot must be a string"
msgstr ""

#: nova/api/openstack/compute/servers.py:1147
#: nova/api/openstack/compute/plugins/v3/servers.py:776
msgid "Argument 'type' for reboot is not HARD or SOFT"
msgstr ""

#: nova/api/openstack/compute/servers.py:1151
#: nova/api/openstack/compute/plugins/v3/servers.py:780
msgid "Missing argument 'type' for reboot"
msgstr ""

#: nova/api/openstack/compute/servers.py:1178
#: nova/api/openstack/compute/plugins/v3/servers.py:807
msgid "Unable to locate requested flavor."
msgstr ""

#: nova/api/openstack/compute/servers.py:1181
#: nova/api/openstack/compute/plugins/v3/servers.py:810
msgid "Resize requires a flavor change."
msgstr ""

#: nova/api/openstack/compute/servers.py:1191
#: nova/api/openstack/compute/plugins/v3/servers.py:821
msgid "You are not authorized to access the image the instance was started with."
msgstr ""

#: nova/api/openstack/compute/servers.py:1195
#: nova/api/openstack/compute/plugins/v3/servers.py:825
msgid "Image that the instance was started with could not be found."
msgstr ""

#: nova/api/openstack/compute/servers.py:1202
#: nova/api/openstack/compute/plugins/v3/servers.py:832
msgid "Invalid instance image."
msgstr ""

#: nova/api/openstack/compute/servers.py:1225
#: nova/api/openstack/compute/plugins/v3/servers.py:875
msgid "Missing imageRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1230
#: nova/api/openstack/compute/servers.py:1238
#: nova/api/openstack/compute/plugins/v3/servers.py:856
msgid "Invalid imageRef provided."
msgstr ""

#: nova/api/openstack/compute/servers.py:1268
msgid "Missing flavorRef attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1281
msgid "No adminPass was specified"
msgstr ""

#: nova/api/openstack/compute/servers.py:1289
#: nova/api/openstack/compute/plugins/v3/admin_password.py:59
msgid "Unable to set password on instance"
msgstr ""

#: nova/api/openstack/compute/servers.py:1298
msgid "Unable to parse metadata key/value pairs."
msgstr ""

#: nova/api/openstack/compute/servers.py:1311
msgid "Resize request has invalid 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1314
msgid "Resize requests require 'flavorRef' attribute."
msgstr ""

#: nova/api/openstack/compute/servers.py:1334
msgid "Could not parse imageRef from request."
msgstr ""

#: nova/api/openstack/compute/servers.py:1404
#: nova/api/openstack/compute/plugins/v3/servers.py:952
msgid "Cannot find image for rebuild"
msgstr ""

#: nova/api/openstack/compute/servers.py:1440
#: nova/api/openstack/compute/plugins/v3/servers.py:987
msgid "createImage entity requires name attribute"
msgstr ""

#: nova/api/openstack/compute/servers.py:1449
#: nova/api/openstack/compute/contrib/admin_actions.py:291
#: nova/api/openstack/compute/plugins/v3/servers.py:996
msgid "Invalid metadata"
msgstr ""

#: nova/api/openstack/compute/servers.py:1507
msgid "Invalid adminPass"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:66
#: nova/api/openstack/compute/contrib/admin_actions.py:89
#: nova/api/openstack/compute/contrib/admin_actions.py:112
#: nova/api/openstack/compute/contrib/admin_actions.py:135
#: nova/api/openstack/compute/contrib/admin_actions.py:178
#: nova/api/openstack/compute/contrib/admin_actions.py:198
#: nova/api/openstack/compute/contrib/admin_actions.py:218
#: nova/api/openstack/compute/contrib/admin_actions.py:238
#: nova/api/openstack/compute/contrib/admin_actions.py:395
msgid "Server not found"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:268
#, python-format
msgid "createBackup entity requires %s attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:272
msgid "Malformed createBackup entity"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:278
msgid "createBackup attribute 'rotation' must be an integer"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:281
msgid "createBackup attribute 'rotation' must be greater than or equal to zero"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:324
msgid ""
"host, block_migration and disk_over_commit must be specified for live "
"migration."
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:363
#, python-format
msgid "Live migration of instance %s to another host failed"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:366
#, python-format
msgid "Live migration of instance %(id)s to host %(host)s failed"
msgstr ""

#: nova/api/openstack/compute/contrib/admin_actions.py:384
#, python-format
msgid "Desired state must be specified.  Valid states are: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/agents.py:100
#: nova/api/openstack/compute/contrib/agents.py:118
#: nova/api/openstack/compute/contrib/agents.py:156
#: nova/api/openstack/compute/contrib/cloudpipe_update.py:56
#, python-format
msgid "Invalid request body: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:39
msgid "Only host parameter can be specified"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:42
msgid "Host parameter must be specified"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:176
#, python-format
msgid "Aggregates does not have %s action"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:180
#: nova/api/openstack/compute/contrib/flavormanage.py:55
#: nova/api/openstack/compute/contrib/keypairs.py:86
msgid "Invalid request body"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:190
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s: not found"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:195
#, python-format
msgid "Cannot add host %(host)s in aggregate %(id)s: host exists"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:209
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s: not found"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:213
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s: invalid"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:232
msgid "The value of metadata must be a dict"
msgstr ""

#: nova/api/openstack/compute/contrib/aggregates.py:245
#, python-format
msgid "Cannot set metadata %(metadata)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:67
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:57
#, python-format
msgid "Create assisted snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/assisted_volume_snapshots.py:78
#: nova/api/openstack/compute/contrib/volumes.py:639
#: nova/api/openstack/compute/plugins/v3/assisted_volume_snapshots.py:73
#, python-format
msgid "Delete snapshot with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:79
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:82
#, python-format
msgid "Instance %(instance)s does not have a port with id %(port)s"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:104
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:109
msgid "Must not input both network_id and port_id"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:107
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:112
msgid "Must input network_id when request IP address"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:120
msgid "Attach interface"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:133
#: nova/api/openstack/compute/contrib/attach_interfaces.py:162
#: nova/api/openstack/compute/contrib/attach_interfaces.py:184
#: nova/api/openstack/compute/plugins/v3/attach_interfaces.py:179
#: nova/network/security_group/neutron_driver.py:521
#: nova/network/security_group/neutron_driver.py:525
#: nova/network/security_group/neutron_driver.py:529
#: nova/network/security_group/neutron_driver.py:533
#: nova/network/security_group/neutron_driver.py:537
msgid "Network driver does not support this function."
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:137
msgid "Failed to attach interface"
msgstr ""

#: nova/api/openstack/compute/contrib/attach_interfaces.py:153
#, python-format
msgid "Detach interface %s"
msgstr ""

#: nova/api/openstack/compute/contrib/baremetal_nodes.py:97
#: nova/api/openstack/compute/plugins/v3/baremetal_nodes.py:82
#, python-format
msgid ""
"Command Not supported. Please use Ironic command %(cmd)s to perform this "
"action."
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:250
#, python-format
msgid "Cell %(id)s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:286
msgid "Cell name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:289
msgid "Cell name cannot contain '!' or '.'"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:295
msgid "Cell type must be 'parent' or 'child'"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:331
msgid "rpc_port must be integer"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:358
#: nova/api/openstack/compute/contrib/cells.py:383
msgid "No cell information in request"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:362
msgid "No cell name in request"
msgstr ""

#: nova/api/openstack/compute/contrib/cells.py:420
msgid "Only 'updated_since', 'project_id' and 'deleted' are understood."
msgstr ""

#: nova/api/openstack/compute/contrib/certificates.py:60
#: nova/api/openstack/compute/plugins/v3/certificates.py:49
msgid "Only root certificate can be retrieved."
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe.py:152
#: nova/api/openstack/compute/plugins/v3/cloudpipe.py:136
msgid ""
"Unable to claim IP for VPN instances, ensure it isn't running, and try "
"again in a few minutes"
msgstr ""

#: nova/api/openstack/compute/contrib/cloudpipe_update.py:41
#: nova/api/openstack/compute/plugins/v3/cloudpipe.py:160
#, python-format
msgid "Unknown action %s"
msgstr ""

#: nova/api/openstack/compute/contrib/console_auth_tokens.py:40
#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:45
msgid "Token not found"
msgstr ""

#: nova/api/openstack/compute/contrib/console_auth_tokens.py:46
#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:51
msgid "The requested console type details are not accessible"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:48
msgid "os-getConsoleOutput malformed or missing from request body"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:59
msgid "Length in request body must be an integer value"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:67
msgid "Unable to get console"
msgstr ""

#: nova/api/openstack/compute/contrib/console_output.py:72
#: nova/api/openstack/compute/plugins/v3/console_output.py:65
msgid "Unable to get console log, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:50
msgid "Instance not yet ready"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:54
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:60
msgid "Unable to get vnc console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:79
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:89
msgid "Unable to get spice console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:105
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:121
msgid "Unable to get rdp console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/consoles.py:129
#: nova/api/openstack/compute/plugins/v3/remote_consoles.py:146
msgid "Unable to get serial console, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/disk_config.py:42
#: nova/api/openstack/compute/plugins/v3/disk_config.py:41
#, python-format
msgid "%s must be either 'MANUAL' or 'AUTO'."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:54
msgid "host must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:61
msgid "onSharedStorage must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:69
#: nova/api/openstack/compute/plugins/v3/evacuate.py:67
msgid "admin password can't be changed on existing disk"
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:80
#: nova/api/openstack/compute/plugins/v3/evacuate.py:78
#, python-format
msgid "Compute host %s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/evacuate.py:87
#: nova/api/openstack/compute/plugins/v3/evacuate.py:84
msgid "The target host can't be the same one."
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:43
#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:46
#, python-format
msgid "Fixed IP %s has been deleted"
msgstr ""

#: nova/api/openstack/compute/contrib/fixed_ips.py:76
#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:84
#, python-format
msgid "Fixed IP %s not found"
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:94
msgid "Flavor not found."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:99
#: nova/api/openstack/compute/plugins/v3/flavor_access.py:61
msgid "Access list not available for public flavors."
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:111
msgid "No request body"
msgstr ""

#: nova/api/openstack/compute/contrib/flavor_access.py:170
#: nova/api/openstack/compute/contrib/flavor_access.py:194
msgid "Missing tenant parameter"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:57
msgid "No Request Body"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:62
msgid "Bad extra_specs provided"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:68
msgid "Fail to validate provided extra specs keys. Expected string"
msgstr ""

#: nova/api/openstack/compute/contrib/flavorextraspecs.py:144
#: nova/api/openstack/compute/contrib/flavorextraspecs.py:160
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:115
#: nova/api/openstack/compute/plugins/v3/flavors_extraspecs.py:136
#, python-format
msgid "Flavor %(flavor_id)s has no extra specs with key %(key)s."
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:60
msgid "A valid name parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:66
msgid "A valid ram parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:71
msgid "A valid vcpus parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/flavormanage.py:76
msgid "A valid disk parameter is required"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:144
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:192
msgid "Unable to get dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:182
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:98
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:138
msgid "Unable to create dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:201
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:157
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:252
msgid "Unable to delete dns domain"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:234
msgid "Unable to get dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:238
#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:196
msgid "DNS entries not found."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:277
msgid "Unable to create dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ip_dns.py:297
msgid "Unable to delete dns entry"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:120
#: nova/api/openstack/compute/contrib/floating_ips.py:171
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:102
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:157
#, python-format
msgid "Floating ip not found for id %s"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:148
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:132
#, python-format
msgid "No more floating ips in pool %s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:150
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:134
msgid "No more floating ips available."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:154
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:138
#, python-format
msgid "IP allocation over quota in pool %s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:156
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:140
msgid "IP allocation over quota."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:204
#: nova/api/openstack/compute/contrib/floating_ips.py:274
#: nova/api/openstack/compute/contrib/security_groups.py:491
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:192
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:262
#: nova/api/openstack/compute/plugins/v3/security_groups.py:367
msgid "Missing parameter dict"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:207
#: nova/api/openstack/compute/contrib/floating_ips.py:277
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:195
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:265
msgid "Address not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:214
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:202
msgid "No nw_info cache associated with instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:219
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:207
msgid "No fixed ips associated to instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:230
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:217
msgid "Specified fixed address not assigned to instance"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:244
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:231
msgid "floating ip is already associated"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:247
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:234
msgid "l3driver call to add floating ip failed"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:250
#: nova/api/openstack/compute/contrib/floating_ips.py:285
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:237
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:273
msgid "floating ip not found"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:255
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:242
#, python-format
msgid ""
"Unable to associate floating ip %(address)s to fixed ip %(fixed_address)s"
" for instance %(id)s. Error: %(error)s"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:300
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:288
msgid "Floating ip is not associated"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips.py:304
#: nova/api/openstack/compute/plugins/v3/floating_ips.py:292
#, python-format
msgid "Floating ip %(address)s is not associated with instance %(id)s."
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:118
#: nova/api/openstack/compute/contrib/services.py:170
#: nova/api/openstack/compute/plugins/v3/floating_ips_bulk.py:123
#: nova/api/openstack/compute/plugins/v3/services.py:114
msgid "Unknown action"
msgstr ""

#: nova/api/openstack/compute/contrib/floating_ips_bulk.py:146
#: nova/api/openstack/compute/plugins/v3/floating_ips_bulk.py:146
#: nova/cmd/manage.py:416
#, python-format
msgid "/%s should be specified as single address(es) not in cidr format"
msgstr ""

#: nova/api/openstack/compute/contrib/fping.py:52
#: nova/api/openstack/compute/plugins/v3/fping.py:50
msgid "fping utility is not found."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:185
#, python-format
msgid "Invalid update setting: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:188
#, python-format
msgid "Invalid status: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:190
#, python-format
msgid "Invalid mode: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:192
msgid "'status' or 'maintenance_mode' needed for host update"
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:208
#: nova/api/openstack/compute/plugins/v3/hosts.py:135
#, python-format
msgid "Putting host %(host_name)s in maintenance mode %(mode)s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:214
#: nova/api/openstack/compute/plugins/v3/hosts.py:141
msgid "Virt driver does not implement host maintenance mode."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:231
#: nova/api/openstack/compute/plugins/v3/hosts.py:157
#, python-format
msgid "Enabling host %s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:233
#: nova/api/openstack/compute/plugins/v3/hosts.py:159
#, python-format
msgid "Disabling host %s."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:238
#: nova/api/openstack/compute/plugins/v3/hosts.py:164
msgid "Virt driver does not implement host disabled status."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:256
#: nova/api/openstack/compute/plugins/v3/hosts.py:182
msgid "Virt driver does not implement host power management."
msgstr ""

#: nova/api/openstack/compute/contrib/hosts.py:344
#: nova/api/openstack/compute/plugins/v3/hosts.py:274
msgid "Describe-resource is admin only functionality"
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:208
#: nova/api/openstack/compute/contrib/hypervisors.py:220
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:101
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:113
#, python-format
msgid "Hypervisor with ID '%s' could not be found."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:228
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:121
msgid "Virt driver does not implement uptime function."
msgstr ""

#: nova/api/openstack/compute/contrib/hypervisors.py:244
#: nova/api/openstack/compute/contrib/hypervisors.py:254
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:137
#: nova/api/openstack/compute/plugins/v3/hypervisors.py:147
#, python-format
msgid "No hypervisor matching '%s' could be found."
msgstr ""

#: nova/api/openstack/compute/contrib/instance_usage_audit_log.py:56
#: nova/api/openstack/compute/plugins/v3/instance_usage_audit_log.py:59
#, python-format
msgid "Invalid timestamp for date %s"
msgstr ""

#: nova/api/openstack/compute/contrib/keypairs.py:104
#: nova/api/openstack/compute/plugins/v3/keypairs.py:90
msgid "Quota exceeded, too many key pairs."
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:48
msgid "Missing 'networkId' argument for addFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/multinic.py:69
msgid "Missing 'address' argument for removeFixedIp"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:39
#: nova/api/openstack/compute/contrib/networks_associate.py:55
#: nova/api/openstack/compute/contrib/networks_associate.py:73
#: nova/api/openstack/compute/contrib/os_networks.py:102
#: nova/api/openstack/compute/contrib/os_networks.py:117
#: nova/api/openstack/compute/contrib/os_networks.py:129
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:103
#: nova/api/openstack/compute/contrib/os_tenant_networks.py:133
#: nova/api/openstack/compute/plugins/v3/networks.py:98
#: nova/api/openstack/compute/plugins/v3/networks.py:113
#: nova/api/openstack/compute/plugins/v3/networks.py:128
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:41
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:57
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:75
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:97
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:129
msgid "Network not found"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:42
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:44
msgid "Disassociate host is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:58
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:60
msgid "Disassociate project is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/networks_associate.py:76
#: nova/api/openstack/compute/plugins/v3/networks_associate.py:78
msgid "Associate host is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:105
#: nova/api/openstack/compute/plugins/v3/networks.py:101
msgid "Disassociate network is not implemented by the configured Network API"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:141
#: nova/api/openstack/compute/plugins/v3/networks.py:140
msgid "Missing network in body"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:145
#: nova/api/openstack/compute/plugins/v3/networks.py:144
msgid "Network label is required"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:149
#: nova/api/openstack/compute/plugins/v3/networks.py:148
msgid "Network cidr or cidr_v6 is required"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:158
#: nova/api/openstack/compute/plugins/v3/networks.py:157
#, python-format
msgid "%s is not a valid ip network"
msgstr ""

#: nova/api/openstack/compute/contrib/os_networks.py:191
#: nova/api/openstack/compute/plugins/v3/networks.py:187
msgid "VLAN support must be enabled"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:157
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:152
msgid "No CIDR requested"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:163
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:158
msgid "Requested network does not contain enough (2+) usable hosts"
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:167
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:162
msgid "CIDR is malformed."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:170
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:165
msgid "Address could not be converted."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:178
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:173
msgid "Quota exceeded, too many networks."
msgstr ""

#: nova/api/openstack/compute/contrib/os_tenant_networks.py:191
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:186
msgid "Create networks failed"
msgstr ""

#: nova/api/openstack/compute/contrib/quota_classes.py:96
#: nova/api/openstack/compute/plugins/v3/quota_classes.py:83
msgid "quota_class_set not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/quota_classes.py:111
#: nova/api/openstack/compute/contrib/quotas.py:183
#: nova/api/openstack/compute/plugins/v3/quota_classes.py:98
#, python-format
msgid "Bad key(s) %s in quota_set"
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:84
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:53
#, python-format
msgid "Quota limit %(limit)s for %(resource)s must be -1 or greater."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:93
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:62
#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be greater than or equal to "
"already used and reserved %(minimum)s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:99
#: nova/api/openstack/compute/plugins/v3/quota_sets.py:68
#, python-format
msgid ""
"Quota limit %(limit)s for %(resource)s must be less than or equal to "
"%(maximum)s."
msgstr ""

#: nova/api/openstack/compute/contrib/quotas.py:162
msgid "quota_set not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/scheduler_hints.py:37
msgid "Malformed scheduler_hints attribute"
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:126
#: nova/api/openstack/compute/contrib/security_groups.py:397
#: nova/api/openstack/compute/plugins/v3/security_group_default_rules.py:60
#: nova/api/openstack/compute/plugins/v3/security_groups.py:257
msgid "Not enough parameters to build a valid rule."
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:130
#: nova/api/openstack/compute/plugins/v3/security_group_default_rules.py:64
msgid "This default rule already exists."
msgstr ""

#: nova/api/openstack/compute/contrib/security_group_default_rules.py:154
msgid "security group default rule not found"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:265
#: nova/api/openstack/compute/plugins/v3/security_groups.py:109
msgid "The request body can't be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:269
#: nova/api/openstack/compute/plugins/v3/security_groups.py:113
#, python-format
msgid "Missing parameter %s"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:405
#: nova/api/openstack/compute/plugins/v3/security_groups.py:265
#, python-format
msgid "Bad prefix for network in cidr %s"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:494
#: nova/api/openstack/compute/plugins/v3/security_groups.py:370
msgid "Security group not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/security_groups.py:498
#: nova/api/openstack/compute/plugins/v3/security_groups.py:374
msgid "Security group name cannot be empty"
msgstr ""

#: nova/api/openstack/compute/contrib/server_diagnostics.py:58
#: nova/api/openstack/compute/plugins/v3/server_diagnostics.py:53
msgid "Unable to get diagnostics, functionality not implemented"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:93
#, python-format
msgid "event entity requires key %(key)s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:97
#, python-format
msgid "event entity contains unsupported items: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:103
#, python-format
msgid "Invalid event status `%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:126
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:86
#, python-format
msgid "Creating event %(name)s:%(tag)s for instance %(instance_uuid)s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_external_events.py:148
#: nova/api/openstack/compute/plugins/v3/server_external_events.py:108
msgid "No instances found for any event"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:168
#: nova/api/openstack/compute/plugins/v3/server_groups.py:81
msgid "Conflicting policies configured!"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:173
#: nova/api/openstack/compute/plugins/v3/server_groups.py:86
#, python-format
msgid "Invalid policies: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:178
#: nova/api/openstack/compute/plugins/v3/server_groups.py:91
msgid "Duplicate policies configured!"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:183
#: nova/api/openstack/compute/plugins/v3/server_groups.py:96
msgid "the body is invalid."
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:192
#: nova/api/openstack/compute/plugins/v3/server_groups.py:105
#, python-format
msgid "'%s' is either missing or empty."
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:198
#: nova/api/openstack/compute/plugins/v3/server_groups.py:111
#, python-format
msgid "Invalid format for name: '%s'"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:206
#: nova/api/openstack/compute/plugins/v3/server_groups.py:119
#, python-format
msgid "'%s' is not a list"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:210
#: nova/api/openstack/compute/plugins/v3/server_groups.py:123
#, python-format
msgid "unsupported fields: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/server_groups.py:291
#: nova/api/openstack/compute/plugins/v3/server_groups.py:198
msgid "Quota exceeded, too many server groups."
msgstr ""

#: nova/api/openstack/compute/contrib/server_start_stop.py:36
msgid "Instance not found"
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:143
#: nova/api/openstack/compute/plugins/v3/services.py:88
#, python-format
msgid "Service %s not found."
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:189
msgid ""
"The string containing the reason for disabling the service contains "
"invalid characters or is too long."
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:197
msgid "Invalid attribute in the request"
msgstr ""

#: nova/api/openstack/compute/contrib/services.py:199
#: nova/api/openstack/compute/plugins/v3/services.py:134
msgid "Missing disabled reason field"
msgstr ""

#: nova/api/openstack/compute/contrib/simple_tenant_usage.py:231
#: nova/api/openstack/compute/plugins/v3/simple_tenant_usage.py:198
msgid "Datetime is in invalid format"
msgstr ""

#: nova/api/openstack/compute/contrib/simple_tenant_usage.py:250
#: nova/api/openstack/compute/plugins/v3/simple_tenant_usage.py:217
msgid "Invalid start time. The start time cannot occur after the end time."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:77
#, python-format
msgid "vol=%s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:188
#, python-format
msgid "Delete volume with id: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:224
msgid "volume not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:359
#: nova/api/openstack/compute/contrib/volumes.py:512
#: nova/api/openstack/compute/plugins/v3/volumes.py:247
#: nova/api/openstack/compute/plugins/v3/volumes.py:381
#, python-format
msgid "Instance %s is not attached."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:370
#: nova/api/openstack/compute/contrib/volumes.py:490
#: nova/api/openstack/compute/contrib/volumes.py:538
#: nova/api/openstack/compute/plugins/v3/volumes.py:258
#: nova/api/openstack/compute/plugins/v3/volumes.py:410
#, python-format
msgid "volume_id not found: %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:380
#, python-format
msgid "Bad volumeId format: volumeId is not in proper format (%s)"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:392
#: nova/api/openstack/compute/contrib/volumes.py:450
msgid "volumeAttachment not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:397
#: nova/api/openstack/compute/contrib/volumes.py:459
msgid "volumeId must be specified."
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:403
#, python-format
msgid "Attach volume %(volume_id)s to instance %(server_id)s at %(device)s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:521
#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:185
#: nova/api/openstack/compute/plugins/v3/volumes.py:390
msgid "Can't detach root device volume"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:674
msgid "snapshot not specified"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:680
#, python-format
msgid "Create snapshot from volume %s"
msgstr ""

#: nova/api/openstack/compute/contrib/volumes.py:687
#, python-format
msgid "Invalid value '%s' for force."
msgstr ""

#: nova/api/openstack/compute/plugins/__init__.py:34
#, python-format
msgid "Loaded extension %s"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/aggregates.py:165
#: nova/api/openstack/compute/plugins/v3/aggregates.py:169
#, python-format
msgid "Cannot remove host %(host)s in aggregate %(id)s"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/cells.py:191
#, python-format
msgid "Cell %s doesn't exist."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/console_auth_tokens.py:40
msgid "token not provided"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:97
#: nova/api/openstack/compute/plugins/v3/volumes.py:356
msgid "The volume was either invalid or not attached to the instance."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:176
#: nova/api/openstack/compute/plugins/v3/extended_volumes.py:202
#, python-format
msgid "Volume %(volume_id)s is not attached to the instance %(server_id)s"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/fixed_ips.py:87
#, python-format
msgid "Fixed IP %s not valid"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/flavors.py:96
#, python-format
msgid "Invalid min_ram filter [%s]"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:122
msgid "you can not pass project if the scope is private"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:125
msgid "you can not pass av_zone if the scope is public"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/floating_ip_dns.py:232
msgid "Unable to update dns domain"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/instance_actions.py:73
#, python-format
msgid "Action %s not found"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/networks.py:177
#: nova/api/openstack/compute/plugins/v3/tenant_networks.py:138
msgid "Missing request body"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/pause_server.py:57
#: nova/api/openstack/compute/plugins/v3/pause_server.py:79
msgid "Virt driver does not implement pause function."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:409
msgid "Unknown argument: port"
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:412
#, python-format
msgid ""
"Specified Fixed IP '%(addr)s' cannot be used with port '%(port)s': port "
"already has a Fixed IP allocated."
msgstr ""

#: nova/api/openstack/compute/plugins/v3/servers.py:702
msgid "host_id cannot be updated."
msgstr ""

#: nova/api/validation/validators.py:107
#, python-format
msgid "Invalid input for field/attribute %(path)s. Value: %(value)s. %(message)s"
msgstr ""

#: nova/cells/messaging.py:366 nova/cells/messaging.py:374
#, python-format
msgid "destination is %(target_cell)s but routing_path is %(routing_path)s"
msgstr ""

#: nova/cells/messaging.py:386
#, python-format
msgid "Unknown %(cell_type)s when routing to %(target_cell)s"
msgstr ""

#: nova/cells/messaging.py:437
#, python-format
msgid "Failed to send message to cell: %(next_hop)s: %(exc)s"
msgstr ""

#: nova/cells/messaging.py:554
#, python-format
msgid "Error waiting for responses from neighbor cells: %(exc)s"
msgstr ""

#: nova/cells/messaging.py:665
#, python-format
msgid "Unknown method '%(method)s' in compute API"
msgstr ""

#: nova/cloudpipe/pipelib.py:47
msgid "Flavor for vpn instances"
msgstr ""

#: nova/cloudpipe/pipelib.py:50
msgid "Template for cloudpipe instance boot script"
msgstr ""

#: nova/cloudpipe/pipelib.py:53
msgid "Network to push into openvpn config"
msgstr ""

#: nova/cloudpipe/pipelib.py:56
msgid "Netmask to push into openvpn config"
msgstr ""

#: nova/cmd/manage.py:213
msgid ""
"The above error may show that the database has not been created.\n"
"Please create a database using 'nova-manage db sync' before running this "
"command."
msgstr ""

#: nova/cmd/manage.py:254
msgid "Quota limit must be -1 or greater."
msgstr ""

#: nova/cmd/manage.py:258
#, python-format
msgid "Quota limit must be greater than %s."
msgstr ""

#: nova/cmd/manage.py:261
#, python-format
msgid "Quota limit must be less than %s."
msgstr ""

#: nova/cmd/manage.py:270
#, python-format
msgid "%(key)s is not a valid quota key. Valid options are: %(options)s."
msgstr ""

#: nova/cmd/manage.py:276
msgid "Quota"
msgstr ""

#: nova/cmd/manage.py:277
msgid "Limit"
msgstr ""

#: nova/cmd/manage.py:278
msgid "In Use"
msgstr ""

#: nova/cmd/manage.py:279
msgid "Reserved"
msgstr ""

#: nova/cmd/manage.py:322 nova/cmd/manage.py:397 nova/cmd/manage.py:736
#: nova/cmd/manage.py:750 nova/cmd/manage.py:820
#, python-format
msgid "error: %s"
msgstr ""

#: nova/cmd/manage.py:330
msgid "network"
msgstr ""

#: nova/cmd/manage.py:331
msgid "IP address"
msgstr ""

#: nova/cmd/manage.py:332
msgid "hostname"
msgstr ""

#: nova/cmd/manage.py:333 nova/cmd/manage.py:876
msgid "host"
msgstr ""

#: nova/cmd/manage.py:345 nova/cmd/manage.py:369
msgid "No fixed IP found."
msgstr ""

#: nova/cmd/manage.py:361
#, python-format
msgid "WARNING: fixed ip %s allocated to missing instance"
msgstr ""

#: nova/cmd/manage.py:423
#, python-format
msgid ""
"Too many IP addresses will be generated.  Please increase /%s to reduce "
"the number generated."
msgstr ""

#: nova/cmd/manage.py:474
msgid "No floating IP addresses have been defined."
msgstr ""

#: nova/cmd/manage.py:493
msgid ""
"ERROR: Network commands are not supported when using the Neutron API.  "
"Use python-neutronclient instead."
msgstr ""

#: nova/cmd/manage.py:550 nova/tests/unit/test_nova_manage.py:220
msgid "id"
msgstr ""

#: nova/cmd/manage.py:551 nova/tests/unit/test_nova_manage.py:221
msgid "IPv4"
msgstr ""

#: nova/cmd/manage.py:552 nova/tests/unit/test_nova_manage.py:222
msgid "IPv6"
msgstr ""

#: nova/cmd/manage.py:553 nova/tests/unit/test_nova_manage.py:223
msgid "start address"
msgstr ""

#: nova/cmd/manage.py:554 nova/tests/unit/test_nova_manage.py:224
msgid "DNS1"
msgstr ""

#: nova/cmd/manage.py:555 nova/tests/unit/test_nova_manage.py:225
msgid "DNS2"
msgstr ""

#: nova/cmd/manage.py:556 nova/tests/unit/test_nova_manage.py:226
msgid "VlanID"
msgstr ""

#: nova/cmd/manage.py:557 nova/cmd/manage.py:664
#: nova/tests/unit/test_nova_manage.py:227
msgid "project"
msgstr ""

#: nova/cmd/manage.py:558 nova/tests/unit/test_nova_manage.py:228
msgid "uuid"
msgstr ""

#: nova/cmd/manage.py:565
msgid "No networks found"
msgstr ""

#: nova/cmd/manage.py:584
msgid "Please specify either fixed_range or uuid"
msgstr ""

#: nova/cmd/manage.py:589
msgid "UUID is required to delete Neutron Networks"
msgstr ""

#: nova/cmd/manage.py:592
msgid "Deleting by fixed_range is not supported with the NeutronManager"
msgstr ""

#: nova/cmd/manage.py:656
msgid "instance"
msgstr ""

#: nova/cmd/manage.py:657
msgid "node"
msgstr ""

#: nova/cmd/manage.py:658
msgid "type"
msgstr ""

#: nova/cmd/manage.py:659
msgid "state"
msgstr ""

#: nova/cmd/manage.py:660
msgid "launched"
msgstr ""

#: nova/cmd/manage.py:661
msgid "image"
msgstr ""

#: nova/cmd/manage.py:662
msgid "kernel"
msgstr ""

#: nova/cmd/manage.py:663
msgid "ramdisk"
msgstr ""

#: nova/cmd/manage.py:665
msgid "user"
msgstr ""

#: nova/cmd/manage.py:666 nova/cmd/manage.py:877
msgid "zone"
msgstr ""

#: nova/cmd/manage.py:667
msgid "index"
msgstr ""

#: nova/cmd/manage.py:711
msgid "Binary"
msgstr ""

#: nova/cmd/manage.py:712
msgid "Host"
msgstr ""

#: nova/cmd/manage.py:713
msgid "Zone"
msgstr ""

#: nova/cmd/manage.py:714
msgid "Status"
msgstr ""

#: nova/cmd/manage.py:715
msgid "State"
msgstr ""

#: nova/cmd/manage.py:716
msgid "Updated_At"
msgstr ""

#: nova/cmd/manage.py:738
#, python-format
msgid "Service %(service)s on host %(host)s enabled."
msgstr ""

#: nova/cmd/manage.py:752
#, python-format
msgid "Service %(service)s on host %(host)s disabled."
msgstr ""

#: nova/cmd/manage.py:824
msgid "An unexpected error has occurred."
msgstr ""

#: nova/cmd/manage.py:825
msgid "[Result]"
msgstr ""

#: nova/cmd/manage.py:829
msgid "HOST"
msgstr ""

#: nova/cmd/manage.py:830
msgid "PROJECT"
msgstr ""

#: nova/cmd/manage.py:831
msgid "cpu"
msgstr ""

#: nova/cmd/manage.py:832
msgid "mem(mb)"
msgstr ""

#: nova/cmd/manage.py:833
msgid "hdd"
msgstr ""

#: nova/cmd/manage.py:916
msgid "Must supply a positive value for max_rows"
msgstr ""

#: nova/cmd/manage.py:935
#, python-format
msgid "Deleted %(records)d records from table '%(table_name)s'."
msgstr ""

#: nova/cmd/manage.py:939
#, python-format
msgid ""
"There are %(records)d records in the '%(table_name)s' table where the "
"uuid or instance_uuid column is NULL. Run this command again with the "
"--delete option after you have backed up any necessary data."
msgstr ""

#: nova/cmd/manage.py:947
msgid "There were no records found where instance_uuid was NULL."
msgstr ""

#: nova/cmd/manage.py:1006
#, python-format
msgid "Hypervisor: %s"
msgstr ""

#: nova/cmd/manage.py:1055
#, python-format
msgid "Line %(linenum)d : %(line)s"
msgstr ""

#: nova/cmd/manage.py:1058
msgid "No errors in logfiles!"
msgstr ""

#: nova/cmd/manage.py:1072
msgid "Unable to find system log file!"
msgstr ""

#: nova/cmd/manage.py:1076
#, python-format
msgid "Last %s nova syslog entries:-"
msgstr ""

#: nova/cmd/manage.py:1085
msgid "No nova entries in syslog!"
msgstr ""

#: nova/cmd/manage.py:1102
#, python-format
msgid "Invalid broker_hosts value: %s. It should be in hostname:port format"
msgstr ""

#: nova/cmd/manage.py:1108
#, python-format
msgid "Invalid port value: %s. It should be an integer"
msgstr ""

#: nova/cmd/manage.py:1121
#, python-format
msgid "Invalid port value: %s. Should be an integer"
msgstr ""

#: nova/cmd/manage.py:1287
#, python-format
msgid "Could not read %s. Re-running with sudo"
msgstr ""

#: nova/cmd/manage.py:1291
msgid "sudo failed, continuing as if nothing happened"
msgstr ""

#: nova/cmd/manage.py:1293
msgid "Please re-run nova-manage as root."
msgstr ""

#: nova/cmd/manage.py:1340
msgid "Command failed, please check log for more info"
msgstr ""

#: nova/compute/api.py:419
msgid "Cannot run any more instances of this type."
msgstr ""

#: nova/compute/api.py:426
#, python-format
msgid "Can only run %s more instances of this type."
msgstr ""

#: nova/compute/api.py:463
msgid "Metadata type should be dict."
msgstr ""

#: nova/compute/api.py:485
msgid "Metadata property key greater than 255 characters"
msgstr ""

#: nova/compute/api.py:488
msgid "Metadata property value greater than 255 characters"
msgstr ""

#: nova/compute/api.py:717
#, python-format
msgid "The volume cannot be assigned the same device name as the root device %s"
msgstr ""

#: nova/compute/api.py:746
msgid "Cannot attach one or more volumes to multiple instances"
msgstr ""

#: nova/compute/api.py:786
msgid "The requested availability zone is not available"
msgstr ""

#: nova/compute/api.py:929
msgid "Quota exceeded, too many servers in group"
msgstr ""

#: nova/compute/api.py:1036
msgid "Server group scheduler hint must be a UUID."
msgstr ""

#: nova/compute/api.py:1235
msgid ""
"Images with destination_type 'volume' need to have a non-zero size "
"specified"
msgstr ""

#: nova/compute/api.py:1267
msgid "More than one swap drive requested."
msgstr ""

#: nova/compute/api.py:1413
#: nova/tests/unit/api/openstack/compute/test_servers.py:2663
#: nova/tests/unit/api/openstack/compute/plugins/v3/test_servers.py:2611
msgid ""
"Unable to launch multiple instances with a single configured port ID. "
"Please launch your instance one by one with different ports."
msgstr ""

#: nova/compute/api.py:1423
msgid "max_count cannot be greater than 1 if an fixed_ip is specified."
msgstr ""

#: nova/compute/api.py:1790
#, python-format
msgid "Ignoring volume cleanup failure due to %s"
msgstr ""

#: nova/compute/api.py:2217
#, python-format
msgid "snapshot for %s"
msgstr ""

#: nova/compute/api.py:2562
msgid "Resize to zero disk flavor is not allowed."
msgstr ""

#: nova/compute/api.py:2778
msgid "Cannot rescue a volume-backed instance"
msgstr ""

#: nova/compute/api.py:3025
msgid "Volume must be attached in order to detach."
msgstr ""

#: nova/compute/api.py:3045
msgid "Old volume is attached to a different instance."
msgstr ""

#: nova/compute/api.py:3048
msgid "New volume must be detached in order to swap."
msgstr ""

#: nova/compute/api.py:3051
msgid "New volume must be the same size or larger."
msgstr ""

#: nova/compute/api.py:3558
msgid "Host aggregate is not empty"
msgstr ""

#: nova/compute/api.py:3625
#, python-format
msgid "Unexpected aggregate action %s"
msgstr ""

#: nova/compute/api.py:3643
#, python-format
msgid "Host already in availability zone %s"
msgstr ""

#: nova/compute/api.py:3726 nova/tests/unit/compute/test_keypairs.py:138
msgid "Keypair name contains unsafe characters"
msgstr ""

#: nova/compute/api.py:3732 nova/tests/unit/compute/test_keypairs.py:128
#: nova/tests/unit/compute/test_keypairs.py:133
msgid "Keypair name must be string and between 1 and 255 characters long"
msgstr ""

#: nova/compute/api.py:3821
#, python-format
msgid "Security group %s is not a string or unicode"
msgstr ""

#: nova/compute/api.py:3831
#, python-format
msgid ""
"Value (%(value)s) for parameter Group%(property)s is invalid. Content "
"limited to '%(allowed)s'."
msgstr ""

#: nova/compute/api.py:3852
msgid "Quota exceeded, too many security groups."
msgstr ""

#: nova/compute/api.py:3855
#, python-format
msgid "Create Security Group %s"
msgstr ""

#: nova/compute/api.py:3867
#, python-format
msgid "Security group %s already exists"
msgstr ""

#: nova/compute/api.py:3880
#, python-format
msgid "Unable to update system group '%s'"
msgstr ""

#: nova/compute/api.py:3942
#, python-format
msgid "Unable to delete system group '%s'"
msgstr ""

#: nova/compute/api.py:3947
msgid "Security group is still in use"
msgstr ""

#: nova/compute/api.py:3960
#, python-format
msgid "Delete security group %s"
msgstr ""

#: nova/compute/api.py:4036
#, python-format
msgid "Rule (%s) not found"
msgstr ""

#: nova/compute/api.py:4052
msgid "Quota exceeded, too many security group rules."
msgstr ""

#: nova/compute/api.py:4055
#, python-format
msgid ""
"Security group %(name)s added %(protocol)s ingress "
"(%(from_port)s:%(to_port)s)"
msgstr ""

#: nova/compute/api.py:4070
#, python-format
msgid ""
"Security group %(name)s removed %(protocol)s ingress "
"(%(from_port)s:%(to_port)s)"
msgstr ""

#: nova/compute/api.py:4122
msgid "Security group id should be integer"
msgstr ""

#: nova/compute/claims.py:154
#, python-format
msgid "Attempting claim: memory %(memory_mb)d MB, disk %(disk_gb)d GB"
msgstr ""

#: nova/compute/claims.py:169
msgid "Claim successful"
msgstr ""

#: nova/compute/claims.py:172
msgid "memory"
msgstr ""

#: nova/compute/claims.py:181
msgid "disk"
msgstr ""

#: nova/compute/claims.py:197 nova/compute/claims.py:285
msgid "Claim pci failed."
msgstr ""

#: nova/compute/claims.py:214
msgid "Requested instance NUMA topology cannot fit the given host NUMA topology"
msgstr ""

#: nova/compute/claims.py:223
#, python-format
msgid "Total %(type)s: %(total)d %(unit)s, used: %(used).02f %(unit)s"
msgstr ""

#: nova/compute/claims.py:230
#, python-format
msgid "%(type)s limit not specified, defaulting to unlimited"
msgstr ""

#: nova/compute/claims.py:237
#, python-format
msgid "%(type)s limit: %(limit).02f %(unit)s, free: %(free).02f %(unit)s"
msgstr ""

#: nova/compute/claims.py:243
#, python-format
msgid "Free %(type)s %(free).02f %(unit)s < requested %(requested)d %(unit)s"
msgstr ""

#: nova/compute/flavors.py:114
msgid ""
"Flavor names can only contain alphanumeric characters, periods, dashes, "
"underscores and spaces."
msgstr ""

#: nova/compute/flavors.py:124
msgid "id cannot contain leading and/or trailing whitespace(s)"
msgstr ""

#: nova/compute/flavors.py:134
msgid ""
"Flavor id can only contain letters from A-Z (both cases), periods, "
"dashes, underscores and spaces."
msgstr ""

#: nova/compute/flavors.py:160
#, python-format
msgid "'rxtx_factor' argument must be a float between 0 and %g"
msgstr ""

#: nova/compute/flavors.py:171
msgid "is_public must be a boolean"
msgstr ""

#: nova/compute/flavors.py:352
msgid ""
"Key Names can only contain alphanumeric characters, periods, dashes, "
"underscores, colons and spaces."
msgstr ""

#: nova/compute/manager.py:530
msgid "Instance event failed"
msgstr ""

#: nova/compute/manager.py:637
#, python-format
msgid "%s is not a valid node managed by this compute host."
msgstr ""

#: nova/compute/manager.py:1340 nova/compute/manager.py:2226
msgid "Success"
msgstr ""

#: nova/compute/manager.py:1364
msgid "Instance disappeared before we could start it"
msgstr ""

#: nova/compute/manager.py:1391
msgid "Anti-affinity instance group policy was violated."
msgstr ""

#: nova/compute/manager.py:1487
msgid "Instance disappeared during build"
msgstr ""

#: nova/compute/manager.py:1645 nova/compute/manager.py:2038
msgid "Starting instance..."
msgstr ""

#: nova/compute/manager.py:2182
#, python-format
msgid "Failed to allocate the network(s) with error %s, not rescheduling."
msgstr ""

#: nova/compute/manager.py:2192 nova/compute/manager.py:2249
msgid "Failed to allocate the network(s), not rescheduling."
msgstr ""

#: nova/compute/manager.py:2284
msgid "Failure prepping block device."
msgstr ""

#: nova/compute/manager.py:2305
msgid "Could not clean up failed build, not rescheduling"
msgstr ""

#: nova/compute/manager.py:2403
#, python-format
msgid "%(action_str)s instance"
msgstr ""

#: nova/compute/manager.py:2768
msgid "Rebuilding instance"
msgstr ""

#: nova/compute/manager.py:2781
msgid "Invalid state of instance files on shared storage"
msgstr ""

#: nova/compute/manager.py:2935
msgid "Rebooting instance"
msgstr ""

#: nova/compute/manager.py:3076
msgid "instance snapshotting"
msgstr ""

#: nova/compute/manager.py:3120
msgid "Image not found during snapshot"
msgstr ""

#: nova/compute/manager.py:3205
#, python-format
msgid "Failed to set admin password. Instance %s is not running"
msgstr ""

#: nova/compute/manager.py:3212
msgid "Root password set"
msgstr ""

#: nova/compute/manager.py:3223
msgid "set_admin_password is not implemented by this driver or guest instance."
msgstr ""

#: nova/compute/manager.py:3238
msgid "error setting admin password"
msgstr ""

#: nova/compute/manager.py:3260
#, python-format
msgid "injecting file to %s"
msgstr ""

#: nova/compute/manager.py:3298
msgid "Rescuing"
msgstr ""

#: nova/compute/manager.py:3325
#, python-format
msgid "Driver Error: %s"
msgstr ""

#: nova/compute/manager.py:3348
msgid "Unrescuing"
msgstr ""

#: nova/compute/manager.py:3652
msgid "Instance has no source host"
msgstr ""

#: nova/compute/manager.py:3658
msgid "destination same as source!"
msgstr ""

#: nova/compute/manager.py:3675
msgid "Migrating"
msgstr ""

#: nova/compute/manager.py:4009
msgid "Pausing"
msgstr ""

#: nova/compute/manager.py:4026
msgid "Unpausing"
msgstr ""

#: nova/compute/manager.py:4065 nova/compute/manager.py:4082
msgid "Retrieving diagnostics"
msgstr ""

#: nova/compute/manager.py:4121
msgid "Resuming"
msgstr ""

#: nova/compute/manager.py:4356
msgid "Get console output"
msgstr ""

#: nova/compute/manager.py:4599
#, python-format
msgid "Attaching volume %(volume_id)s to %(mountpoint)s"
msgstr ""

#: nova/compute/manager.py:4624
#, python-format
msgid "Detach volume %(volume_id)s from mountpoint %(mp)s"
msgstr ""

#: nova/compute/manager.py:4851
#, python-format
msgid "Port %s is not attached"
msgstr ""

#: nova/compute/manager.py:5478
#, python-format
msgid "Instance %s not found"
msgstr ""

#: nova/compute/manager.py:5483
msgid "In ERROR state"
msgstr ""

#: nova/compute/manager.py:5511
#, python-format
msgid "In states %(vm_state)s/%(task_state)s, not RESIZED/None"
msgstr ""

#: nova/compute/manager.py:6032
#, python-format
msgid "Deleting orphan compute node %s"
msgstr ""

#: nova/compute/manager.py:6103
msgid "Failed to power off instance"
msgstr ""

#: nova/compute/manager.py:6121
#, python-format
msgid "Unrecognized value '%s' for CONF.running_deleted_instance_action"
msgstr ""

#: nova/compute/resource_tracker.py:312
msgid "Auditing locally available compute resources"
msgstr ""

#: nova/compute/resource_tracker.py:317
msgid ""
"Virt driver does not support 'get_available_resource'  Compute tracking "
"is disabled."
msgstr ""

#: nova/compute/resource_tracker.py:479
#, python-format
msgid ""
"Total physical ram (MB): %(pram)s, total allocated virtual ram (MB): "
"%(vram)s"
msgstr ""

#: nova/compute/resource_tracker.py:483
#, python-format
msgid ""
"Total physical disk (GB): %(pdisk)s, total allocated virtual disk (GB): "
"%(vdisk)s"
msgstr ""

#: nova/compute/resource_tracker.py:490
#, python-format
msgid "Total usable vcpus: %(tcpu)s, total allocated vcpus: %(ucpu)s"
msgstr ""

#: nova/compute/resource_tracker.py:494
msgid "Free VCPU information unavailable"
msgstr ""

#: nova/compute/resource_tracker.py:497
#, python-format
msgid "PCI stats: %s"
msgstr ""

#: nova/compute/resource_tracker.py:563
#, python-format
msgid "Updating from migration %s"
msgstr ""

#: nova/compute/resource_tracker.py:762
#, python-format
msgid "Missing keys: %s"
msgstr ""

#: nova/compute/rpcapi.py:58
msgid "No compute host specified"
msgstr ""

#: nova/compute/rpcapi.py:60
#, python-format
msgid "Unable to find host for Instance %s"
msgstr ""

#: nova/compute/stats.py:50
msgid "Unexpected type adding stats"
msgstr ""

#: nova/compute/monitors/__init__.py:176
#, python-format
msgid ""
"Excluding monitor %(monitor_name)s due to metric name overlap; "
"overlapping metrics: %(overlap)s"
msgstr ""

#: nova/compute/monitors/__init__.py:184
#, python-format
msgid "Monitor %(monitor_name)s cannot be used: %(ex)s"
msgstr ""

#: nova/conductor/manager.py:542
msgid "No valid host found for cold migrate"
msgstr ""

#: nova/conductor/manager.py:544
msgid "No valid host found for resize"
msgstr ""

#: nova/conductor/manager.py:720
#, python-format
msgid "Unshelve attempted but the image %s cannot be found."
msgstr ""

#: nova/conductor/manager.py:723
msgid "Unshelve attempted but the image_id is not provided"
msgstr ""

#: nova/conductor/tasks/live_migrate.py:113
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s to %(dest)s: Lack of "
"memory(host:%(avail)s <= instance:%(mem_inst)s)"
msgstr ""

#: nova/conductor/tasks/live_migrate.py:179
#, python-format
msgid ""
"Exceeded max scheduling retries %(max_retries)d for instance "
"%(instance_uuid)s during live migration"
msgstr ""

#: nova/console/websocketproxy.py:53
#, python-format
msgid ""
"We do not support scheme '%s' under Python < 2.7.4, please use http or "
"https"
msgstr ""

#: nova/console/websocketproxy.py:76
#, python-format
msgid "connect info: %s"
msgstr ""

#: nova/console/websocketproxy.py:81
#, python-format
msgid "connecting to: %(host)s:%(port)s"
msgstr ""

#: nova/console/websocketproxy.py:104
#, python-format
msgid "%(host)s:%(port)s: Target closed"
msgstr ""

#: nova/console/xvp.py:203
msgid "Failed to run xvp."
msgstr ""

#: nova/consoleauth/manager.py:99
#, python-format
msgid "Received Token: %(token)s, %(token_dict)s"
msgstr ""

#: nova/consoleauth/manager.py:124
#, python-format
msgid "Checking Token: %(token)s, %(token_valid)s"
msgstr ""

#: nova/db/sqlalchemy/api.py:235
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: nova/db/sqlalchemy/api.py:714
#, python-format
msgid "Invalid floating ip id %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:962
#, python-format
msgid "Invalid floating IP %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1258
#: nova/tests/unit/api/openstack/compute/contrib/test_fixed_ips.py:78
#, python-format
msgid "Invalid fixed IP Address %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1415
#, python-format
msgid "Invalid virtual interface address %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:1509
#, python-format
msgid ""
"Unknown osapi_compute_unique_server_name_scope value: %s Flag must be "
"empty, \"global\" or \"project\""
msgstr ""

#: nova/db/sqlalchemy/api.py:1691
#, python-format
msgid "Invalid instance id %s in request"
msgstr ""

#: nova/db/sqlalchemy/api.py:2046
#, python-format
msgid "Invalid field name: %s"
msgstr ""

#: nova/db/sqlalchemy/api.py:2203
msgid "Sort direction size exceeds sort key size"
msgstr ""

#: nova/db/sqlalchemy/api.py:5505
#, python-format
msgid "Add metadata failed for aggregate %(id)s after %(retries)s retries"
msgstr ""

#: nova/db/sqlalchemy/api.py:5903
#, python-format
msgid "IntegrityError detected when archiving table %s"
msgstr ""

#: nova/db/sqlalchemy/migration.py:41
msgid "version should be an integer"
msgstr ""

#: nova/db/sqlalchemy/migration.py:68
msgid "Upgrade DB using Essex release first."
msgstr ""

#: nova/db/sqlalchemy/utils.py:69
#, python-format
msgid "Missing column %(table)s.%(column)s in shadow table"
msgstr ""

#: nova/db/sqlalchemy/utils.py:75
#, python-format
msgid ""
"Different types in %(table)s.%(column)s and shadow table: %(c_type)s "
"%(shadow_c_type)s"
msgstr ""

#: nova/db/sqlalchemy/utils.py:84
#, python-format
msgid "Extra column %(table)s.%(column)s in shadow table"
msgstr ""

#: nova/db/sqlalchemy/utils.py:103
msgid "Specify `table_name` or `table` param"
msgstr ""

#: nova/db/sqlalchemy/utils.py:106
msgid "Specify only one param `table_name` `table`"
msgstr ""

#: nova/db/sqlalchemy/migrate_repo/versions/267_instance_uuid_non_nullable.py:55
#, python-format
msgid ""
"There are %(records)d records in the '%(table_name)s' table where the "
"uuid or instance_uuid column is NULL. These must be manually cleaned up "
"before the migration will pass. Consider running the 'nova-manage db "
"null_instance_uuid_scan' command."
msgstr ""

#: nova/image/glance.py:229
#, python-format
msgid ""
"Error contacting glance server '%(host)s:%(port)s' for '%(method)s', "
"%(extra)s."
msgstr ""

#: nova/image/glance.py:342
#, python-format
msgid "Successfully transferred using %s"
msgstr ""

#: nova/image/s3.py:401
#, python-format
msgid "Failed to decrypt private key: %s"
msgstr ""

#: nova/image/s3.py:408
#, python-format
msgid "Failed to decrypt initialization vector: %s"
msgstr ""

#: nova/image/s3.py:419
#, python-format
msgid "Failed to decrypt image file %(image_file)s: %(err)s"
msgstr ""

#: nova/image/s3.py:431
msgid "Unsafe filenames in image"
msgstr ""

#: nova/image/download/file.py:30
msgid ""
"List of file systems that are configured in this file in the "
"image_file_url:<list entry name> sections"
msgstr ""

#: nova/image/download/file.py:78
msgid ""
"A unique ID given to each file system.  This is value is set in Glance "
"and agreed upon here so that the operator knowns they are dealing with "
"the same file system."
msgstr ""

#: nova/image/download/file.py:83
msgid "The path at which the file system is mounted."
msgstr ""

#: nova/image/download/file.py:92
#, python-format
msgid "The group %s(group_name) must be configured with an id."
msgstr ""

#: nova/image/download/file.py:110
#, python-format
msgid "The key %s is required in all file system descriptions."
msgstr ""

#: nova/image/download/file.py:120
#, python-format
msgid ""
"The key %(r)s is required in the location metadata to access the url "
"%(url)s."
msgstr ""

#: nova/image/download/file.py:127
#, python-format
msgid "The ID %(id)s is unknown."
msgstr ""

#: nova/image/download/file.py:135
#, python-format
msgid ""
"The mount point advertised by glance: %(glance_mount)s, does not match "
"the URL path: %(path)s"
msgstr ""

#: nova/image/download/file.py:153
#, python-format
msgid "No matching ID for the URL %s was found."
msgstr ""

#: nova/ipv6/account_identifier.py:39 nova/ipv6/rfc2462.py:34
#, python-format
msgid "Bad mac for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:41 nova/ipv6/rfc2462.py:36
#, python-format
msgid "Bad prefix for to_global_ipv6: %s"
msgstr ""

#: nova/ipv6/account_identifier.py:43
#, python-format
msgid "Bad project_id for to_global_ipv6: %s"
msgstr ""

#: nova/keymgr/conf_key_mgr.py:58
msgid "keymgr.fixed_key not defined"
msgstr ""

#: nova/keymgr/single_key_mgr.py:60
msgid "cannot store arbitrary keys"
msgstr ""

#: nova/keymgr/single_key_mgr.py:70
msgid "cannot delete non-existent key"
msgstr ""

#: nova/network/base_api.py:71
msgid "instance is a required argument to use @refresh_cache"
msgstr ""

#: nova/network/ldapdns.py:322
msgid "ldap not installed"
msgstr ""

#: nova/network/ldapdns.py:333
msgid "This driver only supports type 'a' entries."
msgstr ""

#: nova/network/linux_net.py:276
#, python-format
msgid "Unknown chain: %r"
msgstr ""

#: nova/network/linux_net.py:785
#, python-format
msgid "Removed %(num)d duplicate rules for floating ip %(float)s"
msgstr ""

#: nova/network/linux_net.py:1582
#, python-format
msgid "Failed to add interface: %s"
msgstr ""

#: nova/network/manager.py:1170
#, python-format
msgid ""
"Subnet(s) too large, defaulting to /%s.  To override, specify "
"network_size flag."
msgstr ""

#: nova/network/manager.py:2038
msgid ""
"The sum between the number of networks and the vlan start cannot be "
"greater than 4094"
msgstr ""

#: nova/network/manager.py:2048
msgid "vlan must be an integer"
msgstr ""

#: nova/network/manager.py:2050
msgid "The vlan number cannot be greater than 4094"
msgstr ""

#: nova/network/manager.py:2053
msgid "The vlan number cannot be less than 1"
msgstr ""

#: nova/network/manager.py:2058
#, python-format
msgid ""
"The network range is not big enough to fit %(num_networks)s networks. "
"Network size is %(network_size)s"
msgstr ""

#: nova/network/minidns.py:75 nova/network/minidns.py:106
msgid "Invalid name"
msgstr ""

#: nova/network/minidns.py:78
msgid "This driver only supports type 'a'"
msgstr ""

#: nova/network/model.py:110
#, python-format
msgid "Invalid IP format %s"
msgstr ""

#: nova/network/neutronv2/api.py:281
#, python-format
msgid "Fixed IP %s is already in use."
msgstr ""

#: nova/network/neutronv2/api.py:359
#, python-format
msgid "empty project id for instance %s"
msgstr ""

#: nova/network/neutronv2/api.py:405 nova/network/neutronv2/api.py:864
msgid "Multiple possible networks found, use a Network ID to be more specific."
msgstr ""

#: nova/network/neutronv2/api.py:433
#, python-format
msgid ""
"Multiple security groups found matching '%s'. Use an ID to be more "
"specific."
msgstr ""

#: nova/network/neutronv2/api.py:1213
#, python-format
msgid "Multiple floating IP pools matches found for name '%s'"
msgstr ""

#: nova/network/security_group/neutron_driver.py:171
msgid "Security group id should be uuid"
msgstr ""

#: nova/network/security_group/neutron_driver.py:409
#: nova/network/security_group/neutron_driver.py:464
#, python-format
msgid "Security group %(name)s is not found for project %(project)s"
msgstr ""

#: nova/network/security_group/neutron_driver.py:425
#: nova/network/security_group/neutron_driver.py:480
#, python-format
msgid "instance_id %s could not be found as device id on any ports"
msgstr ""

#: nova/network/security_group/neutron_driver.py:508
#, python-format
msgid ""
"Security group %(security_group_name)s not associated with the instance "
"%(instance)s"
msgstr ""

#: nova/network/security_group/security_group_base.py:89
msgid "Type and Code must be integers for ICMP protocol type"
msgstr ""

#: nova/network/security_group/security_group_base.py:92
msgid "To and From ports must be integers"
msgstr ""

#: nova/network/security_group/security_group_base.py:134
#, python-format
msgid "This rule already exists in group %s"
msgstr ""

#: nova/objects/base.py:506
#, python-format
msgid "Cannot load '%s' in the base class"
msgstr ""

#: nova/objects/base.py:552
#, python-format
msgid "%(objname)s object has no attribute '%(attrname)s'"
msgstr ""

#: nova/objects/block_device.py:158
msgid "Volume does not belong to the requested instance."
msgstr ""

#: nova/objects/fields.py:30
#, python-format
msgid "Key %(key)s must be of type %(expected)s not %(actual)s"
msgstr ""

#: nova/objects/fields.py:40
#, python-format
msgid "Element %(key)s:%(val)s must be of type %(expected)s not %(actual)s"
msgstr ""

#: nova/objects/fields.py:165
#, python-format
msgid "Field `%s' cannot be None"
msgstr ""

#: nova/objects/fields.py:246
#, python-format
msgid "A string is required here, not %s"
msgstr ""

#: nova/objects/fields.py:286
msgid "A datetime.datetime is required here"
msgstr ""

#: nova/objects/fields.py:328 nova/objects/fields.py:337
#: nova/objects/fields.py:346
#, python-format
msgid "Network \"%s\" is not valid"
msgstr ""

#: nova/objects/fields.py:385
msgid "A list is required here"
msgstr ""

#: nova/objects/fields.py:405
msgid "A dict is required here"
msgstr ""

#: nova/objects/fields.py:472
msgid "A set is required here"
msgstr ""

#: nova/objects/fields.py:505
#, python-format
msgid "An object of type %s is required here"
msgstr ""

#: nova/objects/fields.py:548
msgid "A NetworkModel is required here"
msgstr ""

#: nova/objects/network.py:98
#, python-format
msgid "IPv6 netmask \"%s\" must be a netmask or integral prefix"
msgstr ""

#: nova/openstack/common/cliutils.py:40
#, python-format
msgid "Missing arguments: %s"
msgstr ""

#: nova/openstack/common/cliutils.py:158
#, python-format
msgid ""
"Field labels list %(labels)s has different number of elements than fields"
" list %(fields)s"
msgstr ""

#: nova/openstack/common/imageutils.py:76
#, python-format
msgid "Invalid input value \"%s\"."
msgstr ""

#: nova/openstack/common/imageutils.py:105
msgid "Snapshot list encountered but no header found!"
msgstr ""

#: nova/openstack/common/log.py:298
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: nova/openstack/common/log.py:406
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: nova/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: nova/openstack/common/log.py:713
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: nova/openstack/common/periodic_task.py:46
#, python-format
msgid "Unexpected argument for periodic task creation: %(arg)s."
msgstr ""

#: nova/openstack/common/policy.py:98
msgid "The JSON file that defines policies."
msgstr ""

#: nova/openstack/common/policy.py:101
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: nova/openstack/common/policy.py:105
msgid "Directories where policy configuration files are stored."
msgstr ""

#: nova/openstack/common/policy.py:125
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: nova/openstack/common/policy.py:219
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: nova/openstack/common/sslutils.py:101
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: nova/openstack/common/versionutils.py:90
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: nova/openstack/common/versionutils.py:94
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: nova/openstack/common/versionutils.py:98
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: nova/openstack/common/versionutils.py:101
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: nova/scheduler/chance.py:50
msgid "Is the appropriate service running?"
msgstr ""

#: nova/scheduler/chance.py:55
msgid "Could not find another compute"
msgstr ""

#: nova/scheduler/driver.py:124
msgid "Driver must implement select_destinations"
msgstr ""

#: nova/scheduler/filter_scheduler.py:79
msgid "There are not enough hosts available."
msgstr ""

#: nova/scheduler/host_manager.py:332
#, python-format
msgid "Host filter ignoring hosts: %s"
msgstr ""

#: nova/scheduler/host_manager.py:344
#, python-format
msgid "Host filter forcing available hosts to %s"
msgstr ""

#: nova/scheduler/host_manager.py:347
#, python-format
msgid "No hosts matched due to not matching 'force_hosts' value of '%s'"
msgstr ""

#: nova/scheduler/host_manager.py:360
#, python-format
msgid "Host filter forcing available nodes to %s"
msgstr ""

#: nova/scheduler/host_manager.py:363
#, python-format
msgid "No nodes matched due to not matching 'force_nodes' value of '%s'"
msgstr ""

#: nova/scheduler/utils.py:160
#, python-format
msgid ""
"Exceeded max scheduling attempts %(max_attempts)d for instance "
"%(instance_uuid)s. Last exception: %(exc)s"
msgstr ""

#: nova/scheduler/utils.py:193
msgid "Invalid value for 'scheduler_max_attempts', must be >= 1"
msgstr ""

#: nova/scheduler/utils.py:287
msgid "ServerGroupAffinityFilter not configured"
msgstr ""

#: nova/scheduler/utils.py:291
msgid "ServerGroupAntiAffinityFilter not configured"
msgstr ""

#: nova/servicegroup/api.py:70
#, python-format
msgid "unknown ServiceGroup driver name: %s"
msgstr ""

#: nova/servicegroup/drivers/db.py:48
msgid "service is a mandatory argument for DB based ServiceGroup driver"
msgstr ""

#: nova/servicegroup/drivers/mc.py:44
msgid "memcached_servers not defined"
msgstr ""

#: nova/servicegroup/drivers/mc.py:59
msgid "service is a mandatory argument for Memcached based ServiceGroup driver"
msgstr ""

#: nova/tests/functional/api_samples_test_base.py:116
#, python-format
msgid "%(result_str)s: %(result)s is not a dict."
msgstr ""

#: nova/tests/functional/api_samples_test_base.py:130
#, python-format
msgid ""
"Dictionary key mismatch:\n"
"Extra key(s) in template:\n"
"%(ex_delta)s\n"
"Extra key(s) in %(result_str)s:\n"
"%(res_delta)s\n"
msgstr ""

#: nova/tests/functional/api_samples_test_base.py:142
#, python-format
msgid "%(result_str)s: %(result)s is not a list."
msgstr ""

#: nova/tests/functional/api_samples_test_base.py:162
msgid "Extra list items in template:"
msgstr ""

#: nova/tests/functional/api_samples_test_base.py:166
#, python-format
msgid "Extra list items in %(result_str)s:"
msgstr ""

#: nova/tests/functional/api_samples_test_base.py:187
#: nova/tests/functional/api_samples_test_base.py:204
#, python-format
msgid ""
"Values do not match:\n"
"Template: %(expected)s\n"
"%(result_str)s: %(result)s"
msgstr ""

#: nova/tests/functional/api/client.py:38
#, python-format
msgid ""
"%(message)s\n"
"Status Code: %(_status)s\n"
"Body: %(_body)s"
msgstr ""

#: nova/tests/functional/api/client.py:49
msgid "Authentication error"
msgstr ""

#: nova/tests/functional/api/client.py:57
msgid "Authorization error"
msgstr ""

#: nova/tests/functional/api/client.py:65
msgid "Item not found"
msgstr ""

#: nova/tests/functional/api/client.py:143
msgid "Unexpected status code"
msgstr ""

#: nova/tests/unit/fake_ldap.py:34
msgid "Attempted to instantiate singleton"
msgstr ""

#: nova/tests/unit/fake_volume.py:187
msgid "status must be available"
msgstr ""

#: nova/tests/unit/fake_volume.py:191
msgid "already attached"
msgstr ""

#: nova/tests/unit/fake_volume.py:195
msgid "Instance and volume not in same availability_zone"
msgstr ""

#: nova/tests/unit/fake_volume.py:200
msgid "already detached"
msgstr ""

#: nova/tests/unit/api/test_auth.py:97
msgid "unexpected role header"
msgstr ""

#: nova/tests/unit/api/openstack/test_faults.py:47
msgid "Should be translated."
msgstr ""

#: nova/tests/unit/api/openstack/compute/test_servers.py:2743
#: nova/tests/unit/api/openstack/compute/plugins/v3/test_servers.py:2503
msgid ""
"Quota exceeded for instances: Requested 1, but already used 10 of 10 "
"instances"
msgstr ""

#: nova/tests/unit/api/openstack/compute/test_servers.py:2748
#: nova/tests/unit/api/openstack/compute/plugins/v3/test_servers.py:2508
msgid "Quota exceeded for ram: Requested 4096, but already used 8192 of 10240 ram"
msgstr ""

#: nova/tests/unit/api/openstack/compute/test_servers.py:2753
#: nova/tests/unit/api/openstack/compute/plugins/v3/test_servers.py:2513
msgid "Quota exceeded for cores: Requested 2, but already used 9 of 10 cores"
msgstr ""

#: nova/tests/unit/compute/test_compute.py:6468
msgid "wrong host/node"
msgstr ""

#: nova/tests/unit/compute/test_compute.py:11314
msgid "spawn error"
msgstr ""

#: nova/tests/unit/compute/test_keypairs.py:124
#, python-format
msgid "Keypair data is invalid: %s"
msgstr ""

#: nova/tests/unit/compute/test_resources.py:78
#, python-format
msgid "Free %(free)d < requested %(requested)d "
msgstr ""

#: nova/tests/unit/compute/test_resources.py:329
msgid "Free CPUs 2.00 VCPUs < requested 5 VCPUs"
msgstr ""

#: nova/tests/unit/db/test_migrations.py:622
#, python-format
msgid ""
"The following migrations are missing a downgrade:\n"
"\t%s"
msgstr ""

#: nova/tests/unit/virt/hyperv/test_hypervapi.py:592
msgid "Simulated failure"
msgstr ""

#: nova/tests/unit/virt/libvirt/fakelibvirt.py:1060
msgid "Expected a list for 'auth' parameter"
msgstr ""

#: nova/tests/unit/virt/libvirt/fakelibvirt.py:1064
msgid "Expected a function in 'auth[0]' parameter"
msgstr ""

#: nova/tests/unit/virt/libvirt/fakelibvirt.py:1068
msgid "Expected a function in 'auth[1]' parameter"
msgstr ""

#: nova/tests/unit/virt/libvirt/fakelibvirt.py:1079
msgid ""
"virEventRegisterDefaultImpl() must be             called before "
"connection is used."
msgstr ""

#: nova/tests/unit/virt/vmwareapi/fake.py:267
#, python-format
msgid "Property %(attr)s not set for the managed object %(name)s"
msgstr ""

#: nova/tests/unit/virt/vmwareapi/fake.py:1075
msgid "There is no VM registered"
msgstr ""

#: nova/tests/unit/virt/vmwareapi/fake.py:1077
#: nova/tests/unit/virt/vmwareapi/fake.py:1435
#, python-format
msgid "Virtual Machine with ref %s is not there"
msgstr ""

#: nova/tests/unit/virt/vmwareapi/fake.py:1226
msgid "Session Invalid"
msgstr ""

#: nova/tests/unit/virt/vmwareapi/fake.py:1432
msgid "No Virtual Machine has been registered yet"
msgstr ""

#: nova/tests/unit/virt/vmwareapi/test_ds_util.py:291
#: nova/virt/vmwareapi/ds_util.py:307
#, python-format
msgid "Datastore regex %s did not match any datastores"
msgstr ""

#: nova/tests/unit/virt/xenapi/test_vm_utils.py:520
#, python-format
msgid ""
"Sparse copy in progress, %(complete_pct).2f%% complete. %(left)s bytes "
"left to copy"
msgstr ""

#: nova/tests/unit/virt/xenapi/image/test_bittorrent.py:127
#: nova/virt/xenapi/image/bittorrent.py:80
msgid ""
"Cannot create default bittorrent URL without torrent_base_url set or "
"torrent URL fetcher extension"
msgstr ""

#: nova/tests/unit/virt/xenapi/image/test_bittorrent.py:161
#: nova/virt/xenapi/image/bittorrent.py:84
msgid "Multiple torrent URL fetcher extensions found. Failing."
msgstr ""

#: nova/virt/block_device.py:400
#, python-format
msgid "Booting with volume %(volume_id)s at %(mountpoint)s"
msgstr ""

#: nova/virt/diagnostics.py:143
#, python-format
msgid "Invalid type for %s"
msgstr ""

#: nova/virt/diagnostics.py:147
#, python-format
msgid "Invalid type for %s entry"
msgstr ""

#: nova/virt/driver.py:735
msgid "Hypervisor driver does not support post_live_migration_at_source method"
msgstr ""

#: nova/virt/driver.py:1255
msgid "Event must be an instance of nova.virt.event.Event"
msgstr ""

#: nova/virt/event.py:33
msgid "Started"
msgstr ""

#: nova/virt/event.py:34
msgid "Stopped"
msgstr ""

#: nova/virt/event.py:35
msgid "Paused"
msgstr ""

#: nova/virt/event.py:36
msgid "Resumed"
msgstr ""

#: nova/virt/event.py:108
msgid "Unknown"
msgstr ""

#: nova/virt/hardware.py:50
#, python-format
msgid "No CPUs available after parsing %r"
msgstr ""

#: nova/virt/hardware.py:82 nova/virt/hardware.py:86
#, python-format
msgid "Invalid range expression %r"
msgstr ""

#: nova/virt/hardware.py:95
#, python-format
msgid "Invalid exclusion expression %r"
msgstr ""

#: nova/virt/hardware.py:102
#, python-format
msgid "Invalid inclusion expression %r"
msgstr ""

#: nova/virt/images.py:52
#, python-format
msgid "Path does not exist %(path)s"
msgstr ""

#: nova/virt/images.py:58
#, python-format
msgid "Failed to run qemu-img info on %(path)s : %(error)s"
msgstr ""

#: nova/virt/images.py:87
msgid "'qemu-img info' parsing failed."
msgstr ""

#: nova/virt/images.py:93
#, python-format
msgid "fmt=%(fmt)s backed by: %(backing_file)s"
msgstr ""

#: nova/virt/images.py:123
#, python-format
msgid "Converted to raw, but format is now %s"
msgstr ""

#: nova/virt/disk/api.py:292
msgid "image already mounted"
msgstr ""

#: nova/virt/disk/api.py:616
msgid "Not implemented on Windows"
msgstr ""

#: nova/virt/disk/api.py:643
#, python-format
msgid "User %(username)s not found in password file."
msgstr ""

#: nova/virt/disk/api.py:659
#, python-format
msgid "User %(username)s not found in shadow file."
msgstr ""

#: nova/virt/disk/mount/api.py:145
#, python-format
msgid "partition search unsupported with %s"
msgstr ""

#: nova/virt/disk/mount/api.py:161
#, python-format
msgid "partition %s not found"
msgstr ""

#: nova/virt/disk/mount/api.py:162
#, python-format
msgid "Failed to map partitions: %s"
msgstr ""

#: nova/virt/disk/mount/api.py:197
#, python-format
msgid "Failed to mount filesystem: %s"
msgstr ""

#: nova/virt/disk/mount/loop.py:32
#, python-format
msgid "Could not attach image to loopback: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:65
msgid "nbd unavailable: module not loaded"
msgstr ""

#: nova/virt/disk/mount/nbd.py:73
msgid "No free nbd devices"
msgstr ""

#: nova/virt/disk/mount/nbd.py:90
#, python-format
msgid "qemu-nbd error: %s"
msgstr ""

#: nova/virt/disk/mount/nbd.py:103
#, python-format
msgid "nbd device %s did not show up"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:69
#, python-format
msgid "libguestfs is not installed (%s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:81
#, python-format
msgid "libguestfs installed but not usable (%s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:126
#, python-format
msgid "No operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:132
#, python-format
msgid "Multi-boot operating system found in %s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:143
#, python-format
msgid "No mount points found in %(root)s of %(imgfile)s"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:157
#, python-format
msgid ""
"Error mounting %(device)s to %(dir)s in image %(imgfile)s with libguestfs"
" (%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/guestfs.py:209
#, python-format
msgid "Error mounting %(imgfile)s with libguestfs (%(e)s)"
msgstr ""

#: nova/virt/disk/vfs/localfs.py:46
#, python-format
msgid "File path %s not valid"
msgstr ""

#: nova/virt/hyperv/driver.py:189
msgid "VIF plugging is not supported by the Hyper-V driver."
msgstr ""

#: nova/virt/hyperv/driver.py:194
msgid "VIF unplugging is not supported by the Hyper-V driver."
msgstr ""

#: nova/virt/hyperv/hostops.py:150
msgid "Host PowerOn is not supported by the Hyper-V driver"
msgstr ""

#: nova/virt/hyperv/hostutils.py:98
#, python-format
msgid "Host %(action)s is not supported by the Hyper-V driver"
msgstr ""

#: nova/virt/hyperv/imagecache.py:63
#, python-format
msgid ""
"Cannot resize the image to a size smaller than the VHD max. internal "
"size: %(vhd_size)s. Requested disk size: %(root_vhd_size)s"
msgstr ""

#: nova/virt/hyperv/livemigrationops.py:40
msgid "Live migration is supported starting with Hyper-V Server 2012"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:43
#, python-format
msgid "Live migration is not supported on target host \"%s\""
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:46
#, python-format
msgid "Target live migration host \"%s\" is unreachable"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:49
#, python-format
msgid "Live migration failed: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:61
msgid "Live migration is not enabled on this host"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:64
msgid "Live migration networks are not configured on this host"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:70 nova/virt/hyperv/vmutils.py:176
#, python-format
msgid "VM not found: %s"
msgstr ""

#: nova/virt/hyperv/livemigrationutils.py:72 nova/virt/hyperv/vmutils.py:185
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: nova/virt/hyperv/migrationops.py:109
#, python-format
msgid ""
"Cannot resize the root disk to a smaller size. Current size: "
"%(curr_root_gb)s GB. Requested size: %(new_root_gb)s GB"
msgstr ""

#: nova/virt/hyperv/migrationops.py:160
#, python-format
msgid "Config drive is required by instance: %s, but it does not exist."
msgstr ""

#: nova/virt/hyperv/migrationops.py:219
msgid "Cannot resize a VHD to a smaller size"
msgstr ""

#: nova/virt/hyperv/migrationops.py:264
#, python-format
msgid "Cannot find boot VHD file for instance: %s"
msgstr ""

#: nova/virt/hyperv/networkutils.py:45 nova/virt/hyperv/networkutilsv2.py:42
#, python-format
msgid "vswitch \"%s\" not found"
msgstr ""

#: nova/virt/hyperv/networkutils.py:58
#, python-format
msgid "Failed to create vswitch port %(port_name)s on switch %(vswitch_path)s"
msgstr ""

#: nova/virt/hyperv/networkutilsv2.py:55
msgid "No external vswitch found"
msgstr ""

#: nova/virt/hyperv/pathutils.py:81
#, python-format
msgid "The file copy from %(src)s to %(dest)s failed"
msgstr ""

#: nova/virt/hyperv/pathutils.py:204
#, python-format
msgid "Unable to mount SMBFS share: %(smbfs_share)s WMI exception: %(wmi_exc)s"
msgstr ""

#: nova/virt/hyperv/pathutils.py:230
#, python-format
msgid "Could not unmount share: %s"
msgstr ""

#: nova/virt/hyperv/utilsfactory.py:68
msgid ""
"The \"force_hyperv_utils_v1\" option cannot be set to \"True\" on Windows"
" Server / Hyper-V Server 2012 R2 or above as the WMI "
"\"root/virtualization\" namespace is no longer supported."
msgstr ""

#: nova/virt/hyperv/vhdutils.py:66 nova/virt/hyperv/vhdutilsv2.py:65
#, python-format
msgid "Unsupported disk format: %s"
msgstr ""

#: nova/virt/hyperv/vhdutils.py:162
#, python-format
msgid "Unable to obtain block size from VHD %(vhd_path)s"
msgstr ""

#: nova/virt/hyperv/vhdutils.py:209
msgid "Unsupported virtual disk format"
msgstr ""

#: nova/virt/hyperv/vhdutilsv2.py:164
#, python-format
msgid "Unable to obtain internal size from VHDX: %(vhd_path)s. Exception: %(ex)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:134
#, python-format
msgid "VIF driver not found for network_api_class: %s"
msgstr ""

#: nova/virt/hyperv/vmops.py:219
#, python-format
msgid ""
"Cannot resize a VHD to a smaller size, the original size is %(old_size)s,"
" the newer size is %(new_size)s"
msgstr ""

#: nova/virt/hyperv/vmops.py:328 nova/virt/vmwareapi/vmops.py:612
#, python-format
msgid "Invalid config_drive_format \"%s\""
msgstr ""

#: nova/virt/hyperv/vmops.py:594
#, python-format
msgid "Could not get instance console log. Error: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:147
#, python-format
msgid "Cannot get VM summary data for: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:245
msgid ""
"The Windows account running nova-compute on this Hyper-V host doesn't "
"have the required permissions to create or operate the virtual machine."
msgstr ""

#: nova/virt/hyperv/vmutils.py:563
#, python-format
msgid "Operation failed with return value: %s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:579
#, python-format
msgid ""
"WMI job failed with status %(job_state)d. Error details: %(err_sum_desc)s"
" - %(err_desc)s - Error code: %(err_code)d"
msgstr ""

#: nova/virt/hyperv/vmutils.py:590
#, python-format
msgid "WMI job failed with status %(job_state)d. Error details: %(error)s"
msgstr ""

#: nova/virt/hyperv/vmutils.py:596
#, python-format
msgid "WMI job failed with status %d. No error description available"
msgstr ""

#: nova/virt/hyperv/vmutils.py:721
msgid "Exceeded the maximum number of slots"
msgstr ""

#: nova/virt/hyperv/vmutils.py:724
msgid "Metrics collection is not supported on this version of Hyper-V"
msgstr ""

#: nova/virt/hyperv/volumeops.py:175
#, python-format
msgid ""
"Cannot log in target %(target_iqn)s. Unsupported iSCSI authentication "
"method: %(auth_method)s."
msgstr ""

#: nova/virt/hyperv/volumeops.py:300
#, python-format
msgid "Unable to find a mounted disk for target_iqn: %s"
msgstr ""

#: nova/virt/hyperv/volumeops.py:314
#, python-format
msgid ""
"Unable to find a mounted disk for target_iqn: %s. Please ensure that the "
"host's SAN policy is set to \"OfflineAll\" or \"OfflineShared\""
msgstr ""

#: nova/virt/hyperv/volumeops.py:372
#, python-format
msgid "Unable to attach volume to instance %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:50
#, python-format
msgid "An error has occurred when calling the iscsi initiator: %s"
msgstr ""

#: nova/virt/hyperv/volumeutils.py:107 nova/virt/hyperv/volumeutilsv2.py:109
#, python-format
msgid "Failed to login target %s"
msgstr ""

#: nova/virt/ironic/client_wrapper.py:73
msgid "Unable to authenticate Ironic client."
msgstr ""

#: nova/virt/ironic/client_wrapper.py:111
#, python-format
msgid ""
"Error contacting Ironic server for '%(method)s'. Attempt %(attempt)d of "
"%(total)d"
msgstr ""

#: nova/virt/ironic/driver.py:299
#, python-format
msgid ""
"Failed to add deploy parameters on node %(node)s when provisioning the "
"instance %(instance)s"
msgstr ""

#: nova/virt/ironic/driver.py:324
#, python-format
msgid "Fail to clean up node %s parameters"
msgstr ""

#: nova/virt/ironic/driver.py:349
#, python-format
msgid "Failed to provision instance %(inst)s: %(reason)s"
msgstr ""

#: nova/virt/ironic/driver.py:598
#, python-format
msgid "Ironic node uuid not supplied to driver for instance %s."
msgstr ""

#: nova/virt/ironic/driver.py:621
#, python-format
msgid ""
"Ironic node: %(id)s failed to validate. (deploy: %(deploy)s, power: "
"%(power)s)"
msgstr ""

#: nova/virt/ironic/driver.py:693
#, python-format
msgid ""
"Error destroying the instance on node %(node)s. Provision state still "
"'%(state)s'."
msgstr ""

#: nova/virt/ironic/driver.py:889
#, python-format
msgid ""
"Ironic node: %(id)s virtual to physical interface count  missmatch (Vif "
"count: %(vif_count)d, Pif count: %(pif_count)d)"
msgstr ""

#: nova/virt/ironic/driver.py:1014
#, python-format
msgid "Failed to request Ironic to rebuild instance %(inst)s: %(reason)s"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:145
#, python-format
msgid "Unable to determine disk prefix for %s"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:193
#, python-format
msgid "No free disk device names for prefix '%s'"
msgstr ""

#: nova/virt/libvirt/blockinfo.py:294
#, python-format
msgid "Unable to determine disk bus for '%s'"
msgstr ""

#: nova/virt/libvirt/driver.py:453
#, python-format
msgid ""
"Unexpected sysinfo_serial setting '%(actual)s'. Permitted values are "
"%(expect)s'"
msgstr ""

#: nova/virt/libvirt/driver.py:536
#, python-format
msgid "Nova requires libvirt version %(major)i.%(minor)i.%(micro)i or greater."
msgstr ""

#: nova/virt/libvirt/driver.py:717
msgid "operation time out"
msgstr ""

#: nova/virt/libvirt/driver.py:1069
#, python-format
msgid ""
"Volume sets block size, but the current libvirt hypervisor '%s' does not "
"support custom block size"
msgstr ""

#: nova/virt/libvirt/driver.py:1076
#, python-format
msgid "Volume sets block size, but libvirt '%s' or later is required."
msgstr ""

#: nova/virt/libvirt/driver.py:1174
msgid "Swap only supports host devices"
msgstr ""

#: nova/virt/libvirt/driver.py:1470
msgid "libvirt error while requesting blockjob info."
msgstr ""

#: nova/virt/libvirt/driver.py:1487
msgid "Only KVM and QEMU are supported"
msgstr ""

#: nova/virt/libvirt/driver.py:1491
#, python-format
msgid "Quiescing requires libvirt version %(version)s or greater"
msgstr ""

#: nova/virt/libvirt/driver.py:1497
msgid "QEMU guest agent is not enabled"
msgstr ""

#: nova/virt/libvirt/driver.py:1515
#, python-format
msgid ""
"Error from libvirt while quiescing %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:1669
msgid "Found no disk to snapshot."
msgstr ""

#: nova/virt/libvirt/driver.py:1761
#, python-format
msgid "Unknown type: %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1766
msgid "snapshot_id required in create_info"
msgstr ""

#: nova/virt/libvirt/driver.py:1823
#, python-format
msgid "Libvirt '%s' or later is required for online deletion of volume snapshots."
msgstr ""

#: nova/virt/libvirt/driver.py:1830
#, python-format
msgid "Unknown delete_info type %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1866
#, python-format
msgid "Disk with id: %s not found attached to instance."
msgstr ""

#: nova/virt/libvirt/driver.py:1875
msgid "filename cannot be None"
msgstr ""

#: nova/virt/libvirt/driver.py:1904
#, python-format
msgid "no match found for %s"
msgstr ""

#: nova/virt/libvirt/driver.py:1961
#, python-format
msgid ""
"Relative blockcommit support was not detected. Libvirt '%s' or later is "
"required for online deletion of network storage-backed volume snapshots."
msgstr ""

#: nova/virt/libvirt/driver.py:2475 nova/virt/xenapi/vmops.py:1680
msgid "Guest does not have a console available"
msgstr ""

#: nova/virt/libvirt/driver.py:2807
#, python-format
msgid "%s format is not supported"
msgstr ""

#: nova/virt/libvirt/driver.py:2914
#, python-format
msgid "Detaching PCI devices with libvirt < %(ver)s is not permitted"
msgstr ""

#: nova/virt/libvirt/driver.py:3005
#, python-format
msgid "Detaching SR-IOV ports with libvirt < %(ver)s is not permitted"
msgstr ""

#: nova/virt/libvirt/driver.py:3122
#, python-format
msgid ""
"Config requested an explicit CPU model, but the current libvirt "
"hypervisor '%s' does not support selecting CPU models"
msgstr ""

#: nova/virt/libvirt/driver.py:3128
msgid "Config requested a custom CPU model, but no model name was provided"
msgstr ""

#: nova/virt/libvirt/driver.py:3132
msgid "A CPU model name should not be set when a host CPU model is requested"
msgstr ""

#: nova/virt/libvirt/driver.py:3166
#, python-format
msgid ""
"Volume sets discard option, but libvirt %(libvirt)s or later is required,"
" qemu %(qemu)s or later is required."
msgstr ""

#: nova/virt/libvirt/driver.py:4037
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_id)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4058
#, python-format
msgid ""
"Error from libvirt while looking up %(instance_name)s: [Error Code "
"%(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4081
#, python-format
msgid ""
"Error from libvirt while getting domain info for %(instance_name)s: "
"[Error Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:4370
msgid "Invalid vcpu_pin_set config, out of hypervisor cpu range."
msgstr ""

#: nova/virt/libvirt/driver.py:4495
msgid "libvirt version is too old (does not support getVersion)"
msgstr ""

#: nova/virt/libvirt/driver.py:4931
msgid "Block migration can not be used with shared storage."
msgstr ""

#: nova/virt/libvirt/driver.py:4941
msgid "Live migration can not be used without shared storage."
msgstr ""

#: nova/virt/libvirt/driver.py:5019
#, python-format
msgid ""
"Unable to migrate %(instance_uuid)s: Disk of instance is too "
"large(available on destination host:%(available)s < need:%(necessary)s)"
msgstr ""

#: nova/virt/libvirt/driver.py:5058
#, python-format
msgid ""
"CPU doesn't have compatibility.\n"
"\n"
"%(ret)s\n"
"\n"
"Refer to %(u)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5120
#, python-format
msgid "The firewall filter for %s does not exist"
msgstr ""

#: nova/virt/libvirt/driver.py:5189
msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag "
"or your destination node does not support retrieving listen addresses.  "
"In order for live migration to work properly, you must configure the "
"graphics (VNC and/or SPICE) listen addresses to be either the catch-all "
"address (0.0.0.0 or ::) or the local address (127.0.0.1 or ::1)."
msgstr ""

#: nova/virt/libvirt/driver.py:5206
msgid ""
"Your libvirt version does not support the VIR_DOMAIN_XML_MIGRATABLE flag,"
" and the  graphics (VNC and/or SPICE) listen addresses on the destination"
" node do not match the addresses on the source node. Since the source "
"node has listen addresses set to either the catch-all address (0.0.0.0 or"
" ::) or the local address (127.0.0.1 or ::1), the live migration will "
"succeed, but the VM will continue to listen on the current addresses."
msgstr ""

#: nova/virt/libvirt/driver.py:5613
#, python-format
msgid ""
"Error from libvirt while getting description of %(instance_name)s: [Error"
" Code %(error_code)s] %(ex)s"
msgstr ""

#: nova/virt/libvirt/driver.py:5747
msgid "Unable to resize disk down."
msgstr ""

#: nova/virt/libvirt/driver.py:5758
msgid "Migration is not supported for LVM backed instances"
msgstr ""

#: nova/virt/libvirt/host.py:161
#, python-format
msgid "Can not handle authentication request for %d credentials"
msgstr ""

#: nova/virt/libvirt/host.py:242
#, python-format
msgid "Connection to libvirt lost: %s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:98
msgid ""
"Incompatible settings: ephemeral storage encryption is supported only for"
" LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:277
#, python-format
msgid "Could not load line %(line)s, got error %(error)s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:292
msgid "Attempted overwrite of an existing value."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:340
msgid "clone() is not implemented"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:511
msgid "You should specify images_volume_group flag to use LVM images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:573
msgid "Instance disk to be encrypted but no context provided"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:620
msgid "You should specify images_rbd_pool flag to use rbd images."
msgstr ""

#: nova/virt/libvirt/imagebackend.py:713
msgid "installed version of librbd does not support cloning"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:724
msgid "Image is not raw format"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:732
msgid "No image locations are accessible"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:752
#, python-format
msgid "Unknown image_type=%s"
msgstr ""

#: nova/virt/libvirt/imagebackend.py:780
#, python-format
msgid "Unknown hw_disk_discard=%s"
msgstr ""

#: nova/virt/libvirt/lvm.py:91
#, python-format
msgid ""
"Insufficient Space on Volume Group %(vg)s. Only %(free_space)db "
"available, but %(size)db required by volume %(lv)s."
msgstr ""

#: nova/virt/libvirt/lvm.py:139
#, python-format
msgid "vg %s must be LVM volume group"
msgstr ""

#: nova/virt/libvirt/lvm.py:182
#, python-format
msgid "Path %s must be LVM logical volume"
msgstr ""

#: nova/virt/libvirt/lvm.py:262
#, python-format
msgid "volume_clear='%s' is not handled"
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:105
msgid "rbd python libraries not found"
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:160
msgid "Not stored in rbd"
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:164
msgid "Blank components"
msgstr ""

#: nova/virt/libvirt/rbd_utils.py:167
msgid "Not an rbd snapshot"
msgstr ""

#: nova/virt/libvirt/utils.py:81
msgid "Cannot find any Fibre Channel HBAs"
msgstr ""

#: nova/virt/libvirt/utils.py:426
msgid "Can't retrieve root device path from instance libvirt configuration"
msgstr ""

#: nova/virt/libvirt/vif.py:346 nova/virt/libvirt/vif.py:539
#: nova/virt/libvirt/vif.py:692
msgid "vif_type parameter must be present for this vif_driver implementation"
msgstr ""

#: nova/virt/libvirt/vif.py:352 nova/virt/libvirt/vif.py:698
#, python-format
msgid "Unexpected vif_type=%s"
msgstr ""

#: nova/virt/libvirt/vif.py:545
#, python-format
msgid "Plug vif failed because of unexpected vif_type=%s"
msgstr ""

#: nova/virt/libvirt/volume.py:340
#, python-format
msgid "iSCSI device not found at %s"
msgstr ""

#: nova/virt/libvirt/volume.py:898
#, python-format
msgid "AoE device not found at %s"
msgstr ""

#: nova/virt/libvirt/volume.py:1088
msgid "We are unable to locate any Fibre Channel devices"
msgstr ""

#: nova/virt/libvirt/volume.py:1107
msgid "Fibre Channel device not found."
msgstr ""

#: nova/virt/vmwareapi/driver.py:129
msgid ""
"Must specify host_ip, host_username and host_password to use "
"vmwareapi.VMwareVCDriver"
msgstr ""

#: nova/virt/vmwareapi/driver.py:138
#, python-format
msgid "Invalid Regular Expression %s"
msgstr ""

#: nova/virt/vmwareapi/driver.py:154
#, python-format
msgid "All clusters specified %s were not found in the vCenter"
msgstr ""

#: nova/virt/vmwareapi/driver.py:394
#, python-format
msgid "The resource %s does not exist"
msgstr ""

#: nova/virt/vmwareapi/driver.py:609
msgid ""
"Multiple hosts may be managed by the VMWare vCenter driver; therefore we "
"do not return uptime for just one host."
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:47
msgid "Datastore name cannot be None"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:49
msgid "Datastore reference cannot be None"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:51
msgid "Invalid capacity"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:54
msgid "Capacity is smaller than free space"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:117
msgid "datastore name empty"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:122 nova/virt/vmwareapi/ds_util.py:158
msgid "path component cannot be None"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:175
msgid "datastore path empty"
msgstr ""

#: nova/virt/vmwareapi/ds_util.py:303
#, python-format
msgid "Storage policy %s did not match any datastores"
msgstr ""

#: nova/virt/vmwareapi/error_util.py:30
msgid "No root disk defined."
msgstr ""

#: nova/virt/vmwareapi/error_util.py:34
msgid "Default PBM policy is required if PBM is enabled."
msgstr ""

#: nova/virt/vmwareapi/error_util.py:38
msgid "The default PBM policy doesn't exist on the backend."
msgstr ""

#: nova/virt/vmwareapi/io_util.py:122
#, python-format
msgid "Glance image %s is in killed state"
msgstr ""

#: nova/virt/vmwareapi/io_util.py:130
#, python-format
msgid "Glance image %(image_id)s is in unknown state - %(state)s"
msgstr ""

#: nova/virt/vmwareapi/network_util.py:134
msgid ""
"ESX SOAP server returned an empty port group for the host system in its "
"response"
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:266
#, python-format
msgid "%s is not supported."
msgstr ""

#: nova/virt/vmwareapi/vm_util.py:1019
msgid "No host available on cluster"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:420
msgid "Image disk size greater than requested disk size"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:460
#, python-format
msgid "disk type '%s' not supported"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:840
msgid "instance is not powered on"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:968
msgid "pause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:972
msgid "unpause not supported for vmwareapi"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:990
msgid "instance is powered off and cannot be suspended."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1010
msgid "instance is not in a suspended state"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1108
msgid "Unable to shrink disk."
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1539
#, python-format
msgid "No device with interface-id %s exists on VM"
msgstr ""

#: nova/virt/vmwareapi/vmops.py:1549
#, python-format
msgid "No device with MAC address %s exists on the VM"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:334 nova/virt/vmwareapi/volumeops.py:507
#, python-format
msgid "%s does not support disk hotplug."
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:359 nova/virt/vmwareapi/volumeops.py:529
msgid "Unable to find iSCSI Target"
msgstr ""

#: nova/virt/vmwareapi/volumeops.py:481 nova/virt/vmwareapi/volumeops.py:537
msgid "Unable to find volume"
msgstr ""

#: nova/virt/xenapi/agent.py:463
#, python-format
msgid "OpenSSL error: %s"
msgstr ""

#: nova/virt/xenapi/driver.py:114
msgid ""
"Must specify connection_url, connection_username (optionally), and "
"connection_password to use compute_driver=xenapi.XenAPIDriver"
msgstr ""

#: nova/virt/xenapi/driver.py:642
msgid "Host startup on XenServer is not supported."
msgstr ""

#: nova/virt/xenapi/fake.py:826
#, python-format
msgid "xenapi.fake does not have an implementation for %s"
msgstr ""

#: nova/virt/xenapi/fake.py:934
#, python-format
msgid ""
"xenapi.fake does not have an implementation for %s or it has been called "
"with the wrong number of arguments"
msgstr ""

#: nova/virt/xenapi/host.py:89
#, python-format
msgid "Aggregate for host %(host)s count not be found."
msgstr ""

#: nova/virt/xenapi/host.py:189
msgid "Failed to parse information about a pci device for passthrough"
msgstr ""

#: nova/virt/xenapi/network_utils.py:31
#, python-format
msgid "Found non-unique network for name_label %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:49
#, python-format
msgid "Found non-unique network for bridge %s"
msgstr ""

#: nova/virt/xenapi/network_utils.py:52
#, python-format
msgid "Found no network for bridge %s"
msgstr ""

#: nova/virt/xenapi/pool.py:74 nova/virt/xenapi/pool.py:122
msgid "setup in progress"
msgstr ""

#: nova/virt/xenapi/pool.py:75 nova/virt/xenapi/pool.py:123
msgid "aggregate deleted"
msgstr ""

#: nova/virt/xenapi/pool.py:76
msgid "aggregate in error"
msgstr ""

#: nova/virt/xenapi/pool.py:121
msgid "no hosts to remove"
msgstr ""

#: nova/virt/xenapi/pool.py:145
#, python-format
msgid "Unable to eject %s from the pool; pool not empty"
msgstr ""

#: nova/virt/xenapi/pool.py:160
#, python-format
msgid "Unable to eject %s from the pool; No master found"
msgstr ""

#: nova/virt/xenapi/pool.py:180
#, python-format
msgid "Unable to join %s in the pool"
msgstr ""

#: nova/virt/xenapi/vif.py:100
#, python-format
msgid "Found no PIF for device %s"
msgstr ""

#: nova/virt/xenapi/vif.py:119
#, python-format
msgid ""
"PIF %(pif_uuid)s for network %(bridge)s has VLAN id %(pif_vlan)d. "
"Expected %(vlan_num)d"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:208
#, python-format
msgid ""
"Device id %(id)s specified is not supported by hypervisor version "
"%(version)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:403
#, python-format
msgid "Unable to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:406
#, python-format
msgid "Reached maximum number of retries trying to unplug VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:418
#, python-format
msgid "Unable to destroy VBD %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:471
#, python-format
msgid "Unable to destroy VDI %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:633
#, python-format
msgid "No primary VDI found for %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:766
#, python-format
msgid ""
"Only file-based SRs (ext/NFS) are supported by this feature.  SR %(uuid)s"
" is of type %(type)s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:900
#, python-format
msgid ""
"VDI %(vdi_ref)s is %(virtual_size)d bytes which is larger than flavor "
"size of %(new_disk_size)d bytes."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:911 nova/virt/xenapi/vmops.py:1126
msgid "Can't resize a disk to 0 GB."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:963
msgid "Disk must have only one partition."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:968
#, python-format
msgid "Disk contains a filesystem we are unable to resize: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:973
msgid "The only partition should be partition 1."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:984
#, python-format
msgid "Attempted auto_configure_disk failed because: %s"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1542
#, python-format
msgid ""
"Kernel/Ramdisk image is too large: %(vdi_size)d bytes, max %(max_size)d "
"bytes"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:1913
msgid "Cannot find SR of content-type ISO"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2119
#, python-format
msgid "VHD coalesce attempts exceeded (%d), giving up..."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2154
#, python-format
msgid "Timeout waiting for device %s to be created"
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2332
msgid ""
"Shrinking the filesystem down with resize2fs has failed, please check if "
"you have enough free space on your disk."
msgstr ""

#: nova/virt/xenapi/vm_utils.py:2491
msgid "This domU must be running on the host specified by connection_url"
msgstr ""

#: nova/virt/xenapi/vmops.py:178
msgid "Error: Agent is disabled"
msgstr ""

#: nova/virt/xenapi/vmops.py:570
msgid "Failed to spawn, rolling back"
msgstr ""

#: nova/virt/xenapi/vmops.py:581
msgid "Unable to find root VBD/VDI for VM"
msgstr ""

#: nova/virt/xenapi/vmops.py:872
msgid "Unable to terminate instance."
msgstr ""

#: nova/virt/xenapi/vmops.py:1102
msgid "Can't resize down ephemeral disks."
msgstr ""

#: nova/virt/xenapi/vmops.py:1380
msgid "instance has a kernel or ramdisk but not both"
msgstr ""

#: nova/virt/xenapi/vmops.py:1528
#, python-format
msgid "Instance is already in Rescue Mode: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:1964
#, python-format
msgid "Destination host:%s must be in the same aggregate as the source server"
msgstr ""

#: nova/virt/xenapi/vmops.py:1985
msgid "No suitable network for migrate"
msgstr ""

#: nova/virt/xenapi/vmops.py:1991
#, python-format
msgid "PIF %s does not contain IP address"
msgstr ""

#: nova/virt/xenapi/vmops.py:2004
msgid "Migrate Receive failed"
msgstr ""

#: nova/virt/xenapi/vmops.py:2078
msgid "XAPI supporting relax-xsm-sr-check=true required"
msgstr ""

#: nova/virt/xenapi/vmops.py:2089
#, python-format
msgid "assert_can_migrate failed because: %s"
msgstr ""

#: nova/virt/xenapi/vmops.py:2149
msgid "Migrate Send failed"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:86 nova/virt/xenapi/volume_utils.py:262
#, python-format
msgid "Unable to obtain target information %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:165
#, python-format
msgid "Unable to introduce VDI on SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:169
#, python-format
msgid ""
"VDI not found on SR %(sr)s (vdi_uuid %(vdi_uuid)s, target_lun "
"%(target_lun)s)"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:180
#, python-format
msgid "Unable to get record of VDI %s on"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:202
#, python-format
msgid "Unable to introduce VDI for SR %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:300
#, python-format
msgid "Unable to find SR from VBD %s"
msgstr ""

#: nova/virt/xenapi/volume_utils.py:311
#, python-format
msgid "Unable to find SR from VDI %s"
msgstr ""

#: nova/virt/xenapi/client/session.py:79
#, python-format
msgid "%(vendor)s %(product)s %(version)s"
msgstr ""

#: nova/virt/xenapi/client/session.py:87
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: nova/virt/xenapi/client/session.py:107
#, python-format
msgid "Plugin version mismatch (Expected %(exp)s, got %(got)s)"
msgstr ""

#: nova/vnc/xvp_proxy.py:94
#, python-format
msgid "Error in handshake format: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:99
#, python-format
msgid "Error in handshake: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:114
#, python-format
msgid "Invalid request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:134
#, python-format
msgid "Request: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:137
#, python-format
msgid "Request made with missing token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:147
#, python-format
msgid "Request made with invalid token: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:154
#, python-format
msgid "Unexpected error: %s"
msgstr ""

#: nova/vnc/xvp_proxy.py:174
#, python-format
msgid "Starting nova-xvpvncproxy node (version %s)"
msgstr ""

#: nova/volume/cinder.py:299
#, python-format
msgid "volume '%(vol)s' status must be 'in-use'. Currently in '%(status)s' status"
msgstr ""

#: nova/volume/cinder.py:307
#, python-format
msgid "volume '%(vol)s' status must be 'available'. Currently in '%(status)s'"
msgstr ""

#: nova/volume/cinder.py:312
#, python-format
msgid "volume %s already attached"
msgstr ""

#: nova/volume/cinder.py:323
#, python-format
msgid ""
"Instance %(instance)s and volume %(vol)s are not in the same "
"availability_zone. Instance is in %(ins_zone)s. Volume is in %(vol_zone)s"
msgstr ""

#: nova/volume/cinder.py:335
#, python-format
msgid "volume %s already detached"
msgstr ""

